(function () {
  const scenarios = [
    {
      scenario_id: 'STG-SCN-001',
      title: 'ログインからダッシュボード表示',
      role_scope: 'ユーザー',
      scenario_group: '認証・ダッシュボード',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'stgの企業ユーザー導線でログイン後にダッシュボードへ到達し、アンケート一覧の主要情報を確認できることを検証する。',
      linked_case_ids: ['LGN-001', 'DSH-001', 'DSH-004'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: 'ログイン後にダッシュボードが表示され、アンケート一覧、詳細導線、主要ナビゲーションが操作できる。',
      evidence_policy: 'ダッシュボード初期表示、一覧行、コンソールエラーなしのスクリーンショットを残す。',
      notes: '実データの会社名や個人情報は証跡に残さない。'
    },
    {
      scenario_id: 'STG-SCN-002',
      title: 'アンケート詳細とQR/回答URL確認',
      role_scope: 'ユーザー',
      scenario_group: 'QR・回答',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'ダッシュボード上のアンケートから詳細、QR、回答URLの確認導線がつながることを検証する。',
      linked_case_ids: ['DSH-003', 'QR-001', 'QR-002', 'QR-003', 'QR-004'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: 'アンケート詳細またはQR表示から回答URL相当の情報を確認でき、コピー操作後も画面が破綻しない。',
      evidence_policy: 'QRまたは回答URL表示部、コピー後トースト、コンソールエラーなしを記録する。',
      notes: 'コピー先の実URLは必要に応じて一部マスクする。'
    },
    {
      scenario_id: 'STG-SCN-003',
      title: '回答プレビューで完了表示まで確認',
      role_scope: 'ユーザー',
      scenario_group: 'QR・回答',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: '回答画面のプレビューまたは安全な確認導線で、入力から完了表示までの体験を副作用なしで確認する。',
      linked_case_ids: ['ANS-004', 'ANS-005', 'ANS-007', 'ANS-011', 'ANS-012', 'ANS-013', 'ANS-023'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: '設問表示、入力保持、送信操作後のプレビュー完了表示が確認でき、実回答保存が発生しない。',
      evidence_policy: '回答画面、入力済み状態、プレビュー完了表示を記録する。',
      notes: 'プレビュー導線がない場合は送信直前までで止め、結果は「要許可」にする。'
    },
    {
      scenario_id: 'STG-SCN-004',
      title: '回答本送信の事前確認',
      role_scope: 'ユーザー',
      scenario_group: 'QR・回答',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: '来場者回答の本送信導線が成立することを、stgデータ更新リスクを明示して確認する。',
      linked_case_ids: ['ANS-019', 'ANS-020', 'ANS-021', 'ANS-022'],
      stg_observation_status: 'stg未観測/明示許可待ち',
      expected_outcome: '必須入力後に送信確認または完了導線へ進める。明示許可がない場合は本送信せず、直前状態までを確認する。',
      evidence_policy: '送信直前状態、確認ダイアログまたは要許可判断を記録する。',
      notes: '本送信はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-005',
      title: 'アンケート作成から編集画面確認',
      role_scope: 'ユーザー',
      scenario_group: 'アンケート作成・編集',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'アンケート作成画面で基本情報、設問、設定タブの導線が一連で確認できることを検証する。',
      linked_case_ids: ['CRT-001', 'EDT-001', 'EDT-002', 'EDT-022', 'EDT-027', 'EDT-028'],
      stg_observation_status: 'stg未観測/明示許可待ち',
      expected_outcome: '新規作成または編集画面で基本情報と設問操作UIが表示され、保存が必要な操作は直前で止められる。',
      evidence_policy: '作成/編集画面、設問追加メニュー、保存直前状態を記録する。',
      notes: '保存や公開はstgデータ変更のため原則実行しない。'
    },
    {
      scenario_id: 'STG-SCN-006',
      title: '名刺データ化設定と見積表示',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: '名刺データ化設定でプラン、件数、見積、関連導線の表示を確認する。',
      linked_case_ids: ['BIZ-001', 'BIZ-002'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: 'データ化有無、想定件数、見積または料金表示が確認でき、保存が必要な操作は直前で止められる。',
      evidence_policy: '設定画面、見積表示、保存前状態を記録する。',
      notes: '料金・件数など実データは必要最小限にマスクする。'
    },
    {
      scenario_id: 'STG-SCN-007',
      title: 'お礼メール設定の表示確認',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'お礼メール設定で文面、送信対象、送信タイミング、保存入口を確認する。',
      linked_case_ids: ['THX-001', 'MAIL-001', 'MAIL-002'],
      stg_observation_status: 'stg未観測/明示許可待ち',
      expected_outcome: 'メール文面と送信対象の設定UIが表示され、保存や送信は許可がない限り実行しない。',
      evidence_policy: '設定画面、送信対象、保存/送信前状態を記録する。',
      notes: '実メール送信の可能性がある操作は必ず停止する。'
    },
    {
      scenario_id: 'STG-SCN-008',
      title: '請求一覧から請求詳細確認',
      role_scope: 'ユーザー',
      scenario_group: 'ダウンロード・請求',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: '企業ユーザー側で請求一覧、請求詳細、印刷用ビューの導線を確認する。',
      linked_case_ids: ['INV-001', 'INV-002', 'INV-003'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: '請求一覧から詳細へ遷移でき、請求先、明細、合計金額、印刷導線が表示される。',
      evidence_policy: '請求一覧、詳細、印刷ビュー入口を記録する。',
      notes: '金額や請求先などの実値はマスクする。'
    },
    {
      scenario_id: 'STG-SCN-009',
      title: '管理者ログインと主要画面巡回',
      role_scope: '管理者',
      scenario_group: '管理者共通',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/login',
      objective: '管理者ログイン後にトップへ入り、主要管理画面リンクが切れずに巡回できることを検証する。',
      linked_case_ids: ['STG-COMMON-01', 'STG-ADM-00', 'STG-AX-01', 'STG-AX-02'],
      stg_observation_status: 'stg観測資料あり/再確認待ち',
      expected_outcome: '管理者トップと主要リンクが表示され、遷移時にログインへ戻されない。',
      evidence_policy: '管理者トップ、主要リンク、代表遷移先、コンソールエラーなしを記録する。',
      notes: 'ログアウト確認は最後に実行する。'
    },
    {
      scenario_id: 'STG-SCN-010',
      title: '管理者の利用者・アンケート・請求検索',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '管理者側の主要一覧で検索、リセット、ページング、関連導線を確認する。',
      linked_case_ids: ['STG-ADM-01', 'STG-ADM-02', 'STG-ADM-03', 'STG-AX-03'],
      stg_observation_status: 'stg観測資料あり/再確認待ち',
      expected_outcome: '利用者、アンケート、請求の各一覧で条件入力とリセットができ、関連導線へ進める。',
      evidence_policy: '各一覧の検索フォーム、検索後表示、リセット後表示を記録する。',
      notes: '実データ値は証跡に残さず、編集保存や削除確定は実行しない。'
    },
    {
      scenario_id: 'STG-SCN-011',
      title: '管理者のクーポン検索と実績確認',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/coupon',
      objective: 'クーポン管理の検索/編集入口と、オペレーター実績確認の集計表示入口を確認する。',
      linked_case_ids: ['STG-ADM-04', 'STG-ADM-10'],
      stg_observation_status: 'stg観測資料あり/再確認待ち',
      expected_outcome: 'クーポン検索条件を操作でき、編集または利用履歴の入口が表示される。実績確認では期間/所属条件、集計表示、CSV入口が確認できる。',
      evidence_policy: 'クーポン検索条件、一覧、編集/利用履歴入口、実績確認の集計表示を記録する。',
      notes: 'クーポン作成や保存は実行しない。実績CSVは必要時のみ実行する。'
    },
    {
      scenario_id: 'STG-SCN-012',
      title: '管理者の営業日とオペレーター入口確認',
      role_scope: '管理者',
      scenario_group: '管理者設定',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '営業日カレンダーとオペレーター管理の更新系入口を、データ変更せず確認する。',
      linked_case_ids: ['STG-ADM-05', 'STG-ADM-09', 'STG-AX-04'],
      stg_observation_status: 'stg観測資料あり/再確認待ち',
      expected_outcome: '営業日設定UI、オペレーター検索、新規作成/編集/削除入口が表示され、確定操作は止められる。',
      evidence_policy: '営業日設定画面、オペレーター一覧、更新系入口を記録する。',
      notes: '決定、保存、削除確定は明示許可がない限り実行しない。'
    },
    {
      scenario_id: 'STG-SCN-013',
      title: '管理者の名刺入力・照合・エスカレーション導線',
      role_scope: '管理者',
      scenario_group: '管理者業務フロー',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '名刺入力、照合、エスカレーション確認の作業入口を確認する。',
      linked_case_ids: ['STG-ADM-07', 'STG-FLOW-DATA-01', 'STG-ADM-08', 'STG-FLOW-MATCH-01', 'STG-FLOW-ESCALE-01'],
      stg_observation_status: 'stg観測資料あり/一部未到達',
      expected_outcome: '名刺入力対象、作業画面入口、照合検索、エスカレーション導線が確認でき、確定/スキップは止められる。',
      evidence_policy: '一覧、作業入口、リダイレクトまたは未到達理由を記録する。',
      notes: '観測資料上、照合作業画面とエスカレーション確認は未到達のため、到達可否を結果に記録する。'
    },
    {
      scenario_id: 'STG-SCN-014',
      title: 'ユーザー作成アンケートと請求の管理者横断確認',
      role_scope: '横断',
      scenario_group: '請求横断',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'ユーザー側で確認したアンケート/請求の情報を、管理者側のアンケート検索と請求/請求書検索で追えることを確認する。',
      linked_case_ids: ['CRT-001', 'DSH-001', 'INV-001', 'INV-002', 'STG-ADM-02', 'STG-ADM-03', 'STG-ADM-06'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: 'ユーザー側のアンケート/請求表示と、管理者側のアンケート/請求検索の表示観点を比較でき、データ更新なしで導線を確認できる。',
      evidence_policy: 'ユーザー側アンケート/請求、管理者側アンケート検索、請求検索、請求書検索結果を記録する。',
      notes: 'アンケート名、金額、請求先、会社名はマスクし、同一性の厳密判定は今回の期待結果に含めない。'
    },
    {
      scenario_id: 'STG-SCN-015',
      title: 'グループ切替で別アカウントの一覧/請求を確認',
      role_scope: 'ユーザー',
      scenario_group: '認証・ダッシュボード',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'アカウント情報パネルのグループ切替で、個人アカウントとグループでアンケート一覧・請求のデータコンテキストが切り替わることを検証する。',
      linked_case_ids: ['ACC-002', 'GRP-001', 'GRP-003', 'DSH-001', 'INV-001'],
      stg_observation_status: 'stg一部観測/グループ切替の実行は未',
      expected_outcome: 'グループ選択コンボで個人とグループを切り替えると、一覧と請求の表示が切替後の内容になる。',
      evidence_policy: '切替前後の一覧・請求一覧、選択中グループ表示を記録する。',
      notes: '会社名や請求先などの実データはマスクする。'
    },
    {
      scenario_id: 'STG-SCN-016',
      title: 'グループ新規作成の通し',
      role_scope: 'ユーザー',
      scenario_group: '認証・ダッシュボード',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'アカウント情報パネルからグループ新規作成導線を起動し、作成確定の直前まで確認する。',
      linked_case_ids: ['ACC-002', 'GRP-002'],
      stg_observation_status: 'stg未観測/作成導線は未起動',
      expected_outcome: '「グループ新規作成」から作成フォームへ進める。確定はstgデータ変更のため許可がない限り実行しない。',
      evidence_policy: '作成フォーム、入力状態、確定前状態を記録する。',
      notes: 'グループ作成はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-017',
      title: 'SPEEDレビューの集計・絞り込み通し',
      role_scope: 'ユーザー',
      scenario_group: 'SPEEDレビュー',
      priority: 'P1',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/dashboard',
      objective: '回答が存在するアンケートのSPEEDレビューで、集計表示・個別回答・フィルタが確認できることを検証する。',
      linked_case_ids: ['REV-004', 'REV-005', 'REV-006', 'REV-007', 'REV-008', 'REV-009'],
      stg_observation_status: 'stg観測済(回答0件)/回答ありデータが必要',
      expected_outcome: '回答総数・集計データ・個別回答テーブルが表示され、ソート/ページング/フィルタが操作できる。',
      evidence_policy: '集計表、個別回答テーブル、フィルタ操作前後を記録する。',
      notes: '回答者の氏名・会社名はマスクする。観測時は回答0件のため、回答ありアンケートでの再確認が必要。'
    },
    {
      scenario_id: 'STG-SCN-018',
      title: '名刺データ化の見積確定直前まで',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: '名刺データ化設定でプラン選択・見込み枚数・クーポン適用に応じて見積が更新されることを、確定の直前まで確認する。',
      linked_case_ids: ['BIZ-001', 'BIZ-003', 'BIZ-004', 'BIZ-007', 'BIZ-011'],
      stg_observation_status: 'stg観測済/確定は未実行',
      expected_outcome: 'プラン・枚数・クーポンに応じて請求見込み金額が自動更新され、必須充足で確定ボタンが活性化する。確定は許可がない限り実行しない。',
      evidence_policy: 'プラン選択、見積更新、クーポン適用、確定前状態を記録する。',
      notes: '依頼確定はstgデータを変更するため、実行前にユーザー許可が必要。料金・件数は必要最小限にマスクする。'
    },
    {
      scenario_id: 'STG-SCN-019',
      title: 'お礼メール文面作成からプレビュー確認',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'お礼メール設定で送信方式選択・差し込み変数挿入・リアルタイムプレビュー同期を、保存の直前まで確認する。',
      linked_case_ids: ['MAIL-003', 'MAIL-006', 'MAIL-007', 'MAIL-012'],
      stg_observation_status: 'stg観測済(編集可状態での再確認が必要)',
      expected_outcome: '送信方式が選択でき、本文へ差し込み変数を挿入するとプレビューが置換後の文面で同期する。保存・送信は許可がない限り実行しない。',
      evidence_policy: '送信方式、本文と差し込み変数、プレビュー、保存前状態を記録する。',
      notes: '保存・送信はstgデータ変更や実送信の可能性があるため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-020',
      title: 'お礼メール期限切れ時の代替導線',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P1',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: '送信期限が終了したアンケートのお礼メール設定で、期限切れ状態の表示と対象者リスト確認の代替導線を検証する。',
      linked_case_ids: ['MAIL-011', 'MAIL-008'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '「送信期限が終了しています」バナーと各入力のdisabled、対象者リスト確認の代替導線が表示される。',
      evidence_policy: '期限切れバナー、disabled状態、対象者リスト導線を記録する。',
      notes: '対象者の実データはマスクする。'
    },
    {
      scenario_id: 'STG-SCN-021',
      title: 'アンケート詳細モーダル起点の設定画面横断',
      role_scope: 'ユーザー',
      scenario_group: '認証・ダッシュボード',
      priority: 'P1',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/dashboard',
      objective: 'ダッシュボードの行クリックで開く詳細モーダルから、名刺データ化設定・お礼メール設定への導線がつながることを検証する。',
      linked_case_ids: ['DTL-001', 'DTL-007', 'BIZ-001', 'MAIL-001'],
      stg_observation_status: 'stg観測済/横断遷移は未実行',
      expected_outcome: '詳細モーダルが開き、基本情報・URL・QRが表示され、各設定画面へ遷移して戻れる。',
      evidence_policy: '詳細モーダル、各設定画面の遷移先見出しを記録する。',
      notes: 'アンケート名や請求関連の実データはマスクする。'
    },
    {
      scenario_id: 'STG-SCN-022',
      title: '回答（名刺撮影分岐）通し',
      role_scope: 'ユーザー',
      scenario_group: 'QR・回答',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/questionnaire_answer?id={surveyId}',
      objective: '回答画面で必須入力後、名刺撮影フローと「名刺が手元に無い方」分岐を、送信の直前まで確認する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'ANS-029'],
      stg_observation_status: 'stg観測済/送信・撮影は未実行',
      expected_outcome: '必須充足で送信ボタンが活性化し、名刺撮影と名刺なしの分岐に進める。本送信は許可がない限り実行しない。',
      evidence_policy: '回答入力状態、名刺撮影/名刺なし分岐、送信直前状態を記録する。',
      notes: '本送信はstgデータ更新（実回答保存）の可能性があるため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-023',
      title: 'アンケート管理のステータス絞り込みとファイル系入口確認',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/surveys',
      objective: 'アンケート管理で検索・ステータス複数絞り込み・名刺画像ダウンロード・完了データCSVアップロードの各入口を、確定の直前まで確認する。',
      linked_case_ids: ['STG-ADM-02-01', 'STG-ADM-02-02', 'STG-ADM-02-03', 'STG-ADM-02-04'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '検索とステータス絞り込みが効き、名刺画像DLとCSVアップロード入口が確認できる。アップロード確定は許可がない限り実行しない。',
      evidence_policy: '検索結果、ステータス絞り込み、DL/アップロード入口、確定前状態を記録する。',
      notes: '完了データCSVアップロードの確定はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-024',
      title: '請求管理の直接編集とクーポン割引確認（保存直前）',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/payment',
      objective: '請求管理で検索・直接編集・クーポン割引率/メモ表示を、保存の直前まで確認する。',
      linked_case_ids: ['STG-ADM-03-01', 'STG-ADM-03-03', 'STG-ADM-03-04'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '会社名/氏名検索が効き、直接編集の入力ができ、クーポン割引率・メモが表示される。保存は許可がない限り実行しない。',
      evidence_policy: '検索結果、直接編集の入力状態、クーポン割引表示、保存前状態を記録する。',
      notes: '直接編集の保存はstgデータを変更するため、実行前にユーザー許可が必要。金額・請求先はマスクする。'
    },
    {
      scenario_id: 'STG-SCN-025',
      title: 'クーポン新規作成から利用履歴確認（作成直前）',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/coupon',
      objective: 'クーポン管理で検索・新規作成フォーム・利用履歴を、作成の直前まで確認する。',
      linked_case_ids: ['STG-ADM-04-01', 'STG-ADM-04-02', 'STG-ADM-04-04'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: 'クーポン検索が効き、新規作成フォームに入力でき、既存クーポンの利用履歴が表示される。作成確定は許可がない限り実行しない。',
      evidence_policy: '検索結果、新規作成フォーム、利用履歴、作成前状態を記録する。',
      notes: 'クーポン作成はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-026',
      title: 'オペレーター新規登録の確定直前（権限レベル/対応言語）',
      role_scope: '管理者',
      scenario_group: '管理者設定',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/operator_list',
      objective: 'オペレーター管理で新規登録フォームの権限レベル選択・対応言語複数選択を、登録の直前まで確認する。',
      linked_case_ids: ['STG-ADM-09-03', 'STG-ADM-09-04', 'STG-ADM-09-05', 'STG-ADM-09-06'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '権限レベル（レベル1〜4）と対応言語が選択でき、必須入力後に登録ボタンが活性化する。登録は許可がない限り実行しない。',
      evidence_policy: '新規登録フォーム、権限レベル選択、対応言語選択、登録前状態を記録する。',
      notes: 'オペレーター登録はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-027',
      title: 'オペレーター実績のタブ・集計・CSV入口確認',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'low',
      start_url: 'https://stg.speed-ad.com/admin/achievements',
      objective: 'オペレーター実績確認で集計タブ切替・項目別集計・CSV出力入口を確認する。',
      linked_case_ids: ['STG-ADM-10-01', 'STG-ADM-10-03', 'STG-ADM-10-05'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '所属グループ別/オペレーター別の集計表が切替表示され、項目別集計の詳細とCSV出力入口が確認できる。',
      evidence_policy: '集計タブ、項目別集計、CSV出力入口を記録する。',
      notes: 'オペレーター名・報酬額などの実データはマスクする。CSV出力は必要時のみ実行する。'
    },
    {
      scenario_id: 'STG-SCN-028',
      title: '照合の検索・KPI・作業/エスカレーション導線確認',
      role_scope: '管理者',
      scenario_group: '管理者業務フロー',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/matching_list',
      objective: '照合画面で検索・作業ステータス絞り込み・KPI表示・各作業導線を確認する。',
      linked_case_ids: ['STG-ADM-08-01', 'STG-ADM-08-02', 'STG-ADM-08-03', 'STG-ADM-08-04'],
      stg_observation_status: 'stg観測済/2026-05-31（作業画面は未進入）',
      expected_outcome: '検索とステータス絞り込みが効き、KPIとカード別の照合作業/エスカレーション/完成データ確認/全レコードDL導線が表示される。作業・DLは許可がない限り実行しない。',
      evidence_policy: '検索結果、KPI、カード別導線、到達先またはリダイレクトを記録する。',
      notes: '照合作業画面・エスカレーション確認はレコード占有等の懸念があるため、進入は許可がない限り行わない。'
    },
    {
      scenario_id: 'STG-SCN-029',
      title: 'Lv1オペレーターの到達範囲検証',
      role_scope: '管理者',
      scenario_group: '管理者権限レベル',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '権限レベル1（オペレーター）でログイン後、到達できる画面が名刺入力に限定され、他画面はリダイレクト/非表示になることを検証する。',
      linked_case_ids: ['STG-ADM-00-01', 'STG-ADM-00-03', 'STG-ADM-07-01'],
      stg_observation_status: 'stg実測済（Lv1相当アカウント）/2026-06-03再確認: メニューは名刺入力のみ、matching_list・surveys直URLは/topへ遮断（正常）。名刺入力画面の名刺画像はORBで非表示（全レベル共通）',
      expected_outcome: 'トップのメニューが名刺入力のみで、他の管理画面URLへ直接アクセスすると/topへリダイレクトされる。',
      evidence_policy: 'トップのメニュー範囲、他画面アクセス時のリダイレクト、名刺入力到達を記録する。',
      notes: '到達範囲のみ確認し、作業画面の確定/スキップは実行しない。'
    },
    {
      scenario_id: 'STG-SCN-031',
      title: 'Lv3アブロードスタッフの全画面到達検証',
      role_scope: '管理者',
      scenario_group: '管理者権限レベル',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '権限レベル3（アブロードスタッフ）でログイン後、主要12メニューに到達し各操作部品が表示されることを検証する。',
      linked_case_ids: ['STG-ADM-00-01', 'STG-ADM-00-02'],
      stg_observation_status: 'stg実測済（現アカウントLv3）/2026-06-03再確認: 10メニュー表示、照合一覧の照合作業/完成データ確認/全レコードDLの操作コントロールはLv4と同一（レベル間の可否差なし）',
      expected_outcome: 'トップにフル12メニューが表示され、各画面へ遷移して戻れる。操作部品（検索/編集/新規作成等）が表示される。',
      evidence_policy: 'トップのメニュー、各画面の到達と戻り、操作部品の表示を記録する。',
      notes: '到達・表示まで確認。保存/削除/送信の実行はしない。'
    },
    {
      scenario_id: 'STG-SCN-030',
      title: 'Lv2オペレーター管理者の到達範囲・アクセス制御検証',
      role_scope: '管理者',
      scenario_group: '管理者権限レベル',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: 'Lv2でメニューが2項目に制限される一方、メニュー非表示の管理画面へ直URLで到達できないこと（サーバ側でアクセス制御が強制されること）を検証する。',
      linked_case_ids: ['STG-ADM-00-01', 'STG-ADM-00-03', 'STG-ADM-01-01', 'STG-ADM-03-01'],
      stg_observation_status: 'stg実測済（2026-05-31・BUG-ADM-04検出）/2026-06-03再確認: メニューは名刺入力＋実績確認の2項目だが、admin/surveysへ直URLで到達し全53行（全社データ）が描画される＝BUG-ADM-04継続（アクセス制御の穴・データ漏洩）',
      expected_outcome: 'Lv2のメニューは名刺入力＋実績確認のみ。メニュー非表示の管理画面（利用者/請求/オペレーター管理等）へ直URLアクセスするとログインへリダイレクトされ到達できないこと。現状は到達できてしまうため不備（BUG-ADM-04）。',
      evidence_policy: 'メニュー表示、各直URLアクセス時のリダイレクト有無を記録する。',
      notes: '回帰検証用。現状は全10画面へ到達できる不備を検出。閲覧のみでデータ更新はしない。実データはマスクする。'
    },
    {
      scenario_id: 'STG-SCN-032',
      title: '名刺データ化の開始→完了→実データダウンロード（管理者・ユーザー両側）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/matching_list',
      objective: '名刺データ化対象アンケートで、データ化開始から照合完了・完了データ確定までを管理者側で進め、管理者側（完成データ確認／全レコードDL）とユーザー側（ダッシュボードのデータダウンロード）の双方で、完成CSV／データが実際に取得できる（CSV生成処理の成功だけでなくDL先が404にならず取得まで完了する）ことを検証する。',
      linked_case_ids: ['STG-ADM-08-04', 'STG-ADM-02-03', 'STG-ADM-02-04', 'BIZ-001', 'DSH-001'],
      stg_observation_status: 'stg未観測/新規（SPDAD2026-146の回帰検証を兼ねる）',
      expected_outcome: '管理者側で「完成データ確認」「全レコードDL」を実行するとCSV生成処理が200を返し、画面が組み立てるDL先（/storage/csv/<file>.csv 等）が404にならずCSVが取得できる。データ化完了（DATA_READY）後は、ユーザー側ダッシュボードでも完成データCSV／名刺画像ZIPのダウンロード導線が表示され、実際に取得できる。',
      evidence_policy: '各ダウンロードのリクエストURLとHTTPステータス、取得可否、CSVの先頭ヘッダ有無、ユーザー側のデータ化完了表示とDL導線を記録する。回答内容・氏名・会社名・メールはマスクする。',
      notes: 'SPDAD2026-146（CSV生成は200だがDL先404）の回帰検証。照合完了・完了データ確定はstgデータを変更するため要許可。専用のテスト用アンケートで実施し、本番相当データには行わない。'
    },
    {
      scenario_id: 'STG-SCN-033',
      title: 'オンデマンドプランの途中ダウンロード（順次納品）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/matching_list',
      objective: 'スピードプランがオンデマンドのアンケートで、名刺データ化が開始された後、全件完了前（途中）の段階でも、照合確定済みのレコード分のデータが管理者側・ユーザー側の双方で順次ダウンロードできることを検証する。',
      linked_case_ids: ['STG-ADM-08-04', 'BIZ-001', 'DSH-001'],
      stg_observation_status: 'stg未観測/新規・要オンデマンド対象アンケート（途中DL可否は仕様上※要確認）',
      expected_outcome: 'オンデマンドプランでデータ化開始後、一部レコードのみ照合完了した段階でも、確定済み分の完成CSV／データがダウンロードでき、レコードを追加で完了させると再ダウンロード時に件数が増える（順次納品される）。通常プランとの挙動差（全件完了まで不可か）も切り分けて記録する。',
      evidence_policy: '対象アンケートのスピードプラン表示、照合完了件数（途中段階／追加後）、各段階でのDL実行結果と取得件数、ユーザー側DL導線の活性状態を記録する。実データはマスクする。',
      notes: '04_data-flow.md上、オンデマンドは当日納期・最優先処理だが「会期中処理／途中DL」の有無は※要確認のため、実挙動を観測して記録する。照合完了・DLはstgデータ変更を伴うため要許可。専用のオンデマンド対象テストアンケートで実施する。'
    },
    {
      scenario_id: 'STG-SCN-034',
      title: '324アンケートの回答＋名刺送信からデータ化・両側DLまで通し（通常プラン）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/questionnaire_answer?id=324',
      objective: '通常プランの既存アンケート（324「STGシナリオテスト 長期展示会」）で、回答者の回答送信＋名刺画像送信から、管理者側の名刺データ化入力・照合、管理者側ダウンロード（名刺画像／完成データ）、ユーザー側ダウンロードまでを回答起点で一気通貫に検証する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'ANS-029', 'STG-ADM-02-01', 'STG-ADM-02-03', 'STG-ADM-07', 'STG-ADM-08-04', 'STG-ADM-02-04', 'DSH-001', 'BIZ-001'],
      stg_observation_status: 'stg実走済(2026-06-03)/324=通常プラン・完了予定日2026-06-15。回答＋名刺送信→件数計上・名刺画像ZIP DL・data_input計上・メール確定・手動照合は成功。名刺画像表示と完成CSV DLに不具合検出（notes参照）',
      expected_outcome: '回答＋名刺画像の送信で回答件数が増え、入力作業画面・照合画面に名刺画像が表示され、管理者側で名刺画像ZIPと完成データ（完成データ確認／全レコードDL）が200で実取得でき（DL先が404・未配信にならない）、完了データアップロード後のデータ化完了で、ユーザー側ダッシュボードでも完成CSV／名刺画像が取得できる。通常プランのためユーザー側DLは会期終了後（後日）になる想定。',
      evidence_policy: '回答送信完了表示、回答件数の増分、各ダウンロードのリクエストURLとHTTPステータス・取得可否（ファイルが実際に保存されるか）、CSV先頭ヘッダ有無、入力/照合画面の名刺画像表示可否、ユーザー側DL導線の活性状態を記録する。氏名・会社名・メール等はマスクする。',
      notes: '324はSTGシナリオテスト用のダミーアンケート（送信はダミー扱い・実顧客データ入力禁止）。回答送信・名刺データ化入力・照合確定・完了データアップロードはstgデータを変更するため要許可。名刺はテスト画像（fixtures/meishi_test.png）を使用。名刺入力画面への計上は名刺送信時点で行われ会期終了を待たない（照合・完成データ納品のタイミングはプラン依存）。【2026-06-03実走で検出した正常系不具合】(1)名刺入力画面(data_input_screen)・照合画面(matching_screen)で名刺画像が表示されない（files.speed-ad.comの署名画像がERR_BLOCKED_BY_ORB）。(2)完成データの「全レコードDL／完成データ確認」がPOST /csv_export2は200を返すが実ファイルが配信されずDLされない（SPDAD2026-146系）。なおadmin/surveys行の名刺画像ZIP DLは成功する。【アカウントレベル別の確認】各ステップ先頭の【】が想定実行レベル（回答者/Lv1/Lv3/Lv4/企業ユーザー）。名刺入力(data_input)はLv1〜Lv4、照合・完成DL・アンケート管理・完了アップロードはLv3/Lv4が対象（Lv1/Lv2はメニュー非表示）。「Lv3では通るがLv4では不可（またはその逆）」を防ぐため、各管理操作は担当レベルと最上位Lv4の双方で実行し、レベル間で可否・表示差が出ないことを確認する。権限到達範囲の基礎はSTG-SCN-029〜031。STG-SCN-032（汎用版）の324具体化。ユーザー側DL確認は324所有アカウントが必要。'
    },
    {
      scenario_id: 'STG-SCN-035',
      title: '325アンケートの回答＋名刺送信からデータ化・両側DLまで通し（オンデマンドプラン）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/questionnaire_answer?id=325',
      objective: 'オンデマンドプランで作成されたアンケート（325）で、STG-SCN-034と同じ回答起点の通しフローを、当日納品・順次納品（途中DL）の観点で検証する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'STG-ADM-02-01', 'STG-ADM-02-03', 'STG-ADM-07', 'STG-ADM-08-04', 'STG-ADM-02-04', 'DSH-001', 'BIZ-001'],
      stg_observation_status: 'stg実走済(2026-06-03)/325=オンデマンド・完了予定日2026-06-03（当日）。回答＋名刺送信→件数2→4・名刺画像ZIP DL・data_input計上(グループ1)・メール確定で照合一覧に出現・手動照合(確定→保存→OK)まで成功。名刺画像表示と完成CSV DLに不具合検出（notes参照）',
      expected_outcome: 'オンデマンドのため完了予定日が当日相当で、データ化を会期終了を待たず当日に進められ、入力・照合が進んだ「そこまでの分」のCSVを途中段階でも管理者側・ユーザー側で取得でき、レコード追加で再DL件数が増える（順次納品）。回答＋名刺送信・管理者DL・ユーザーDLが通常プラン（324）より早いタイミングで成立する。',
      evidence_policy: 'データ化完了予定日表示（当日）、回答件数の増分、入力/照合画面の名刺画像表示可否、途中段階／全件完了時の取得件数とHTTPステータス・実ファイル取得可否、ユーザー側DL活性タイミング（324との差）を記録する。実データはマスクする。',
      notes: '325はSTGシナリオテスト用のダミーアンケート。オンデマンドはメール確定で照合対象化され、会期終了を待たず当日処理できる（実走で確認）。送信・データ化・照合確定・DLはstgデータ変更を伴うため要許可。【2026-06-03実走で検出した正常系不具合】(1)名刺入力画面・照合画面で名刺画像が表示されない（ERR_BLOCKED_BY_ORB）。(2)「全レコードDL／完成データ確認」がPOST /csv_export2は200だが実ファイルが配信されずDLされない（SPDAD2026-146系）＝オンデマンドの途中CSVも現状は取得不可。admin/surveys行の名刺画像ZIP DLは成功。【アカウントレベル別の確認】各ステップ先頭の【】が想定実行レベル。名刺入力(data_input)はLv1〜Lv4、照合・完成DL・アンケート管理はLv3/Lv4が対象（Lv1/Lv2はメニュー非表示）。「Lv3では通るがLv4では不可（またはその逆）」を防ぐため、各管理操作は担当レベルと最上位Lv4の双方で実行し可否・表示差が無いことを確認する。権限到達範囲の基礎はSTG-SCN-029〜031。STG-SCN-033（汎用版）の325具体化。ユーザー側DL確認は325所有アカウントが必要。'
    }
  ];

  const steps = [
    ['STG-SCN-001', 1, 'stgのログイン入口を開き、既存セッションまたはログイン後の遷移先を確認する。', '企業ユーザーとしてダッシュボードへ到達する。', 'none', false, 'LGN-001'],
    ['STG-SCN-001', 2, 'ダッシュボードのアンケート一覧を確認する。', '一覧、ステータス、主要アクションが表示される。', 'none', false, 'DSH-001'],
    ['STG-SCN-001', 3, '代表アンケートの詳細または行アクションを開く。', '詳細導線が表示され、画面が崩れない。', 'none', false, 'DSH-003'],
    ['STG-SCN-001', 4, '主要ナビゲーションを1つ以上開いて戻る。', 'リンク切れや認証切れがない。', 'none', false, 'DSH-004'],
    ['STG-SCN-001', 5, 'コンソールとネットワークを確認する。', '表示を阻害するエラーがない。', 'none', false, ''],

    ['STG-SCN-002', 1, 'ダッシュボードから代表アンケートの詳細を開く。', 'アンケート概要と関連操作が確認できる。', 'none', false, 'DSH-003'],
    ['STG-SCN-002', 2, 'QRまたは回答URLの表示入口を開く。', '回答URL相当の情報が表示される。', 'none', false, 'QR-001,QR-002'],
    ['STG-SCN-002', 3, 'コピー操作を実行する。', 'コピー後トーストまたは完了表示が出る。', 'none', false, 'QR-003'],
    ['STG-SCN-002', 4, 'QR画像未設定時の表示を確認する。', '未設定時はプレースホルダーまたは無効表示になる。', 'none', false, 'QR-004'],

    ['STG-SCN-003', 1, '回答URLまたはプレビューURLを開く。', '回答画面のタイトルと説明が表示される。', 'none', false, 'ANS-004'],
    ['STG-SCN-003', 2, '設問数と必須表示を確認する。', '対象アンケートの設問が表示され、必須表示が確認できる。', 'none', false, 'ANS-005,ANS-006'],
    ['STG-SCN-003', 3, '自由記述、単一選択、複数選択など代表入力を行う。', '入力値または選択状態が保持される。', 'none', false, 'ANS-011,ANS-012,ANS-013'],
    ['STG-SCN-003', 4, 'プレビュー送信または安全な完了確認を行う。', 'プレビュー完了または送信直前状態が確認できる。', 'none', false, 'ANS-023'],

    ['STG-SCN-004', 1, '回答画面を開き、送信に必要な入力を行う。', '送信ボタンが押せる状態になる。', 'none', false, 'ANS-007'],
    ['STG-SCN-004', 2, '送信ボタン押下前に副作用の有無を確認する。', '実回答保存が発生する場合は要許可として止める。', 'medium', true, 'ANS-019'],
    ['STG-SCN-004', 3, '明示許可がある場合のみ本送信を行う。', '送信中表示から完了画面へ進む。', 'medium', true, 'ANS-020,ANS-021'],
    ['STG-SCN-004', 4, '完了表示を確認する。', '完了メッセージと完了アイコンが表示される。', 'none', false, 'ANS-021,ANS-022'],

    ['STG-SCN-005', 1, 'アンケート新規作成または編集入口を開く。', '作成/編集画面へ到達する。', 'medium', true, 'CRT-001,EDT-027'],
    ['STG-SCN-005', 2, '基本情報フィールドを確認する。', 'アンケート名や会期の入力欄が表示される。', 'none', false, 'EDT-001,EDT-022'],
    ['STG-SCN-005', 3, '設問追加メニューを開く。', '設問タイプの選択肢が表示される。', 'none', false, 'EDT-002,EDT-028'],
    ['STG-SCN-005', 4, '保存または公開が必要な操作は直前で止める。', 'stgデータ変更なしで確認を終える。', 'medium', true, 'EDT-001'],

    ['STG-SCN-006', 1, '名刺データ化設定画面を開く。', '設定画面へ到達する。', 'none', false, 'BIZ-001'],
    ['STG-SCN-006', 2, 'プラン、想定件数、料金/見積表示を確認する。', '設定に応じた見積または料金表示が確認できる。', 'none', false, 'BIZ-002'],
    ['STG-SCN-006', 3, '保存系ボタンの表示を確認する。', '保存入口が確認でき、押下は止められる。', 'medium', true, 'BIZ-002'],

    ['STG-SCN-007', 1, 'お礼メール設定画面を開く。', '文面と設定項目が表示される。', 'none', false, 'MAIL-001'],
    ['STG-SCN-007', 2, '送信対象と送信タイミングの表示を確認する。', '対象や期限の状態が確認できる。', 'none', false, 'MAIL-002'],
    ['STG-SCN-007', 3, 'サンクス画面設定または保存/送信系操作は直前で止める。', '実メール送信や保存更新を発生させない。', 'medium', true, 'THX-001,MAIL-001'],

    ['STG-SCN-008', 1, 'ユーザー側の請求一覧を開く。', '請求一覧が表示される。', 'none', false, 'INV-001'],
    ['STG-SCN-008', 2, '代表請求の詳細を開く。', '請求先、明細、合計金額、支払期日が表示される。', 'none', false, 'INV-002'],
    ['STG-SCN-008', 3, '印刷用ビュー入口を確認する。', '印刷用ビューまたは印刷導線が表示される。', 'none', false, 'INV-003'],

    ['STG-SCN-009', 1, '管理者ログイン入口を開く。', '既存セッションでトップへ入る、またはログイン画面が表示される。', 'none', false, 'STG-AX-01'],
    ['STG-SCN-009', 2, '管理者トップの主要リンクを確認する。', '主要管理画面へのリンクが表示される。', 'none', false, 'STG-COMMON-01,STG-ADM-00'],
    ['STG-SCN-009', 3, '主要画面を代表的に巡回する。', '遷移先が表示され、ログインへ戻されない。', 'none', false, 'STG-AX-02'],
    ['STG-SCN-009', 4, '最後に必要であればログアウト導線を確認する。', 'ログアウト後にログイン画面へ戻る。', 'none', false, 'STG-AX-01'],

    ['STG-SCN-010', 1, '利用者管理を開き検索/リセットを確認する。', '検索条件と一覧が表示され、リセットできる。', 'none', false, 'STG-ADM-01'],
    ['STG-SCN-010', 2, 'アンケート管理を開き検索/ステータス絞り込みを確認する。', '検索とステータス条件が操作できる。', 'none', false, 'STG-ADM-02'],
    ['STG-SCN-010', 3, '請求管理を開き検索/ページングを確認する。', '検索条件とページングが操作できる。', 'none', false, 'STG-ADM-03'],
    ['STG-SCN-010', 4, '編集、削除、保存系入口は確定前で止める。', 'stgデータ変更なしで確認を終える。', 'medium', true, 'STG-AX-03'],

    ['STG-SCN-011', 1, 'クーポン管理を開く。', '検索フォームと一覧が表示される。', 'none', false, 'STG-ADM-04'],
    ['STG-SCN-011', 2, 'ID、クーポン名、クーポンコードなどで検索/リセットを確認する。', '検索条件を操作できる。', 'none', false, 'STG-ADM-04'],
    ['STG-SCN-011', 3, '編集または利用履歴入口を確認する。', '入口が表示される。保存は実行しない。', 'medium', true, 'STG-ADM-04'],
    ['STG-SCN-011', 4, 'オペレーター実績確認を開き、期間/所属条件と集計タブを確認する。', '集計表示とCSV出力入口が確認できる。', 'none', false, 'STG-ADM-10'],

    ['STG-SCN-012', 1, '営業日カレンダーを開く。', '定休日、祝日、個別休日、決定ボタンが表示される。', 'none', false, 'STG-ADM-05'],
    ['STG-SCN-012', 2, 'オペレーター管理を開き検索/リセットを確認する。', '検索条件と一覧が表示される。', 'none', false, 'STG-ADM-09'],
    ['STG-SCN-012', 3, '新規作成、編集、削除入口を確認する。', '入口は確認でき、保存/削除確定は実行しない。', 'medium', true, 'STG-AX-04'],

    ['STG-SCN-013', 1, '名刺入力画面を開く。', 'データ入力対象一覧と作業可能件数が表示される。', 'none', false, 'STG-ADM-07'],
    ['STG-SCN-013', 2, '入力作業画面入口を開く。', '入力欄、回転、確定、スキップ、作業終了が表示される、または未到達理由を記録できる。', 'medium', true, 'STG-FLOW-DATA-01'],
    ['STG-SCN-013', 3, '照合画面を開き検索条件と作業入口を確認する。', '照合一覧、KPI、作業開始、エスカレーション導線が表示される。', 'none', false, 'STG-ADM-08'],
    ['STG-SCN-013', 4, '照合作業/エスカレーション確認導線を開く。', '到達先またはリダイレクト先を記録できる。', 'medium', true, 'STG-FLOW-MATCH-01,STG-FLOW-ESCALE-01'],

    ['STG-SCN-014', 1, 'ユーザー側で代表アンケートの一覧/詳細と請求一覧/詳細を確認する。', 'アンケート表示と請求表示が確認できる。', 'none', false, 'DSH-001,INV-001,INV-002'],
    ['STG-SCN-014', 2, '管理者側でアンケート管理を開き、対象を検索する。', 'アンケート管理一覧が表示され、検索できる。', 'none', false, 'STG-ADM-02'],
    ['STG-SCN-014', 3, '管理者側で請求管理と請求書管理を開き検索する。', '請求管理と請求書管理の条件入力、検索、リセットが確認できる。', 'none', false, 'STG-ADM-03,STG-ADM-06'],
    ['STG-SCN-014', 4, 'ユーザー側と管理者側の証跡を並べて確認する。', '表示観点を比較できる。実値の厳密一致は今回の期待に含めない。', 'none', false, ''],

    ['STG-SCN-015', 1, 'サイドバー「アカウント情報」を開き、アカウント/グループ切替パネルを表示する。', 'グループ選択コンボと「グループ新規作成」が表示される。', 'none', false, 'ACC-002'],
    ['STG-SCN-015', 2, 'グループ選択コンボで個人アカウントから別グループへ切り替える。', '選択したグループのコンテキストに切り替わる。', 'none', false, 'GRP-001'],
    ['STG-SCN-015', 3, 'アンケート一覧と請求一覧の表示が切替後の内容になっていることを確認する。', '個人とグループで一覧/請求の内容が変わる。', 'none', false, 'GRP-003,DSH-001,INV-001'],
    ['STG-SCN-015', 4, '個人アカウントへ戻す。', '元のコンテキストに戻る。', 'none', false, 'GRP-001'],

    ['STG-SCN-016', 1, 'アカウント情報パネルを開く。', 'グループ操作UIが表示される。', 'none', false, 'ACC-002'],
    ['STG-SCN-016', 2, '「グループ新規作成」を押下し、作成フォーム/モーダルを表示する。', '作成フォームが表示される。', 'none', false, 'GRP-002'],
    ['STG-SCN-016', 3, '必要項目を入力し、作成確定の直前で止める。', '入力できる。確定はstgデータ変更のため要許可で停止する。', 'medium', true, 'GRP-002'],

    ['STG-SCN-017', 1, '回答が存在するアンケートのSPEEDレビューを開く。', '回答総数とActive Questionが表示される。', 'none', false, 'REV-004,REV-005'],
    ['STG-SCN-017', 2, '時間帯別グラフと集計データ表を確認する。', 'グラフ（自動/固定切替）と集計表（選択肢/件数/割合/合計）が表示される。', 'none', false, 'REV-006,REV-007'],
    ['STG-SCN-017', 3, '個別回答テーブルのソート・ページングを操作する。', '並び替えとページングが動作する。', 'none', false, 'REV-008'],
    ['STG-SCN-017', 4, 'フィルタ（簡易/詳細・表示対象日・ステータス）で絞り込み、リセットする。', '条件で絞り込め、リセットで解除される。', 'none', false, 'REV-009'],

    ['STG-SCN-018', 1, '対象アンケートの名刺データ化設定を開く。', 'プラン一覧と見積サイドバーが表示される。', 'none', false, 'BIZ-001'],
    ['STG-SCN-018', 2, 'データ化項目プランを選択し、見込み枚数を入力する。', '選択と入力に応じて見積が自動更新される。', 'none', false, 'BIZ-003,BIZ-004'],
    ['STG-SCN-018', 3, 'クーポンコードを適用し、見積反映を確認する。', '有効コードで割引が見積に反映される。', 'none', false, 'BIZ-007'],
    ['STG-SCN-018', 4, '「設定を保存して依頼を確定する」の直前で止める。', '必須充足でボタンが活性化する。確定はstgデータ変更のため要許可で停止する。', 'medium', true, 'BIZ-011'],

    ['STG-SCN-019', 1, 'お礼メール設定を開き、送信方式を選択する。', '手動送信/自動送信/送信しないが選択できる。', 'none', false, 'MAIL-003'],
    ['STG-SCN-019', 2, '件名・本文を編集し、差し込み変数を挿入する。', 'カーソル位置に差し込み変数が挿入される。', 'none', false, 'MAIL-006'],
    ['STG-SCN-019', 3, 'リアルタイムプレビューで置換後の文面を確認する。', 'プレビューが編集内容と同期する。', 'none', false, 'MAIL-007'],
    ['STG-SCN-019', 4, '「設定を保存する」の直前で止める。', 'dirtyで活性化する。保存・送信はstgデータ変更/実送信の可能性があるため要許可で停止する。', 'medium', true, 'MAIL-012'],

    ['STG-SCN-020', 1, '送信期限が終了しているアンケートのお礼メール設定を開く。', '「送信期限が終了しています」バナーと各入力のdisabledを確認する。', 'none', false, 'MAIL-011'],
    ['STG-SCN-020', 2, '「対象者リストを見る」などの代替導線を確認する。', '対象者リスト確認の代替導線が表示される。', 'none', false, 'MAIL-008'],

    ['STG-SCN-021', 1, 'ダッシュボードでアンケート行をクリックし詳細モーダルを開く。', '詳細モーダルが開き基本情報/URL/QR/導線が表示される。', 'none', false, 'DTL-001'],
    ['STG-SCN-021', 2, 'モーダルから「名刺データ化設定へ」を開く。', '名刺データ化設定へ遷移する。', 'none', false, 'DTL-007,BIZ-001'],
    ['STG-SCN-021', 3, '戻ってモーダルから「お礼メール設定へ」を開く。', 'お礼メール設定へ遷移する。', 'none', false, 'DTL-007,MAIL-001'],

    ['STG-SCN-022', 1, '回答URLを開き、必須設問に回答する。', '設問が表示され、必須を満たすと送信ボタンが活性化する。', 'none', false, 'ANS-030'],
    ['STG-SCN-022', 2, '「名刺を撮影」フローを起動する。', '名刺撮影/アップロードのステップに進む。', 'none', false, 'ANS-028'],
    ['STG-SCN-022', 3, '「名刺が手元に無い方」分岐を確認する。', '名刺なしルートに分岐できる。', 'none', false, 'ANS-029'],
    ['STG-SCN-022', 4, '送信の直前で止める。', '送信はstgデータ更新（実回答保存）の可能性があるため要許可で停止する。', 'medium', true, 'ANS-030'],

    ['STG-SCN-023', 1, 'アンケート管理を開き、ID/会社名/氏名で検索する。', '条件に一致するアンケートが表示される。', 'none', false, 'STG-ADM-02-01'],
    ['STG-SCN-023', 2, '作業ステータスのチェック（6種）で絞り込む。', '選択したステータスの行のみ表示される。', 'none', false, 'STG-ADM-02-02'],
    ['STG-SCN-023', 3, '名刺画像ダウンロード入口を確認する。', 'ダウンロード導線が表示される。', 'low', false, 'STG-ADM-02-03'],
    ['STG-SCN-023', 4, '完了データCSVアップロードでファイルを選び、確定の直前で止める。', 'ファイル選択でき、確定はstgデータ変更のため要許可で停止する。', 'medium', true, 'STG-ADM-02-04'],

    ['STG-SCN-024', 1, '請求管理を開き、会社名/氏名で検索する。', '条件に一致する請求が表示される。', 'none', false, 'STG-ADM-03-01'],
    ['STG-SCN-024', 2, '直接編集で請求金額等を編集する。', 'インライン編集でき、保存は要許可で停止する。', 'medium', true, 'STG-ADM-03-03'],
    ['STG-SCN-024', 3, 'クーポン割引率・メモ列を確認する。', '割引率とメモが表示される。', 'none', false, 'STG-ADM-03-04'],

    ['STG-SCN-025', 1, 'クーポン管理を開き、ID/名/コード/作成日で検索する。', '条件に一致するクーポンが表示される。', 'none', false, 'STG-ADM-04-01'],
    ['STG-SCN-025', 2, '「クーポン新規作成」を開いて入力し、作成の直前で止める。', '作成フォームに入力でき、確定はstgデータ変更のため要許可で停止する。', 'medium', true, 'STG-ADM-04-02'],
    ['STG-SCN-025', 3, '既存クーポンの利用履歴を開く。', '利用履歴が表示される。', 'none', false, 'STG-ADM-04-04'],

    ['STG-SCN-026', 1, 'オペレーター管理を開き、「新規作成」フォームを表示する。', '所属/権限レベル/メール/名前/対応言語/ステータスの入力フォームが表示される。', 'none', false, 'STG-ADM-09-03'],
    ['STG-SCN-026', 2, '権限レベルを選択する。', 'レベル1〜4が選択できる。', 'none', false, 'STG-ADM-09-04'],
    ['STG-SCN-026', 3, '対応言語を複数選択する。', '複数言語が選択できる。', 'none', false, 'STG-ADM-09-05'],
    ['STG-SCN-026', 4, 'メール・名前・ステータスを入力し、登録の直前で止める。', '必須充足で登録ボタンが活性化する。登録は要許可で停止する。', 'medium', true, 'STG-ADM-09-06'],

    ['STG-SCN-027', 1, 'オペレーター実績確認を開き、集計タブを切り替える。', '所属グループ別/オペレーター別の集計表が切替表示される。', 'none', false, 'STG-ADM-10-01'],
    ['STG-SCN-027', 2, 'オペレーター別で項目別集計の「詳細」を展開する。', '項目名/作業件数/正解件数/正答率/報酬金額/スキップ回数が表示される。', 'none', false, 'STG-ADM-10-03'],
    ['STG-SCN-027', 3, 'CSV出力入口を確認する。', 'CSV出力導線が表示される。', 'low', false, 'STG-ADM-10-05'],

    ['STG-SCN-028', 1, '照合画面を開き、アンケートID/氏名/会社名で検索する。', '条件に一致するアンケートのカードが表示される。', 'none', false, 'STG-ADM-08-01'],
    ['STG-SCN-028', 2, '作業ステータスのチェックで絞り込む。', '選択した状態の対象のみ表示される。', 'none', false, 'STG-ADM-08-02'],
    ['STG-SCN-028', 3, 'KPI（進行中作業対象数・エスカレあり要確認名刺数）を確認する。', '件数が表示される。', 'none', false, 'STG-ADM-08-03'],
    ['STG-SCN-028', 4, '照合作業の開始/エスカレーション内容の確認/完成データ確認/全レコードDLの各導線を確認する。', '各導線が表示される。作業・DLは要許可で停止する。', 'medium', true, 'STG-ADM-08-04'],

    ['STG-SCN-029', 1, 'レベル1（オペレーター）相当アカウントでログインし、管理者トップを開く。', 'トップのメニューが名刺入力のみになっている。', 'none', false, 'STG-ADM-00-01'],
    ['STG-SCN-029', 2, '/admin/user など他の管理画面URLへ直接アクセスする。', '/topへリダイレクトされ、到達できない。', 'none', false, 'STG-ADM-00-03'],
    ['STG-SCN-029', 3, '名刺入力対象一覧を開く。', '名刺入力一覧へ到達できる。', 'none', false, 'STG-ADM-07-01'],

    ['STG-SCN-031', 1, 'レベル3（アブロードスタッフ）アカウントで管理者トップを開く。', 'フル12メニューが表示される。', 'none', false, 'STG-ADM-00-01'],
    ['STG-SCN-031', 2, '主要画面を順に開いて戻る。', '各画面へ到達でき、操作部品が表示され、戻れる。', 'none', false, 'STG-ADM-00-02'],

    ['STG-SCN-030', 1, 'Lv2アカウントで管理者トップを開く。', 'メニューが名刺入力＋実績確認の2項目に限定される。', 'none', false, 'STG-ADM-00-01'],
    ['STG-SCN-030', 2, 'メニュー非表示の利用者管理(/admin/user)へ直URLでアクセスする。', '本来はログインへリダイレクトされ到達できない（現状は到達できる＝BUG-ADM-04）。', 'none', false, 'STG-ADM-01-01'],
    ['STG-SCN-030', 3, '請求管理(/admin/payment)・オペレーター管理(/admin/operator_list)へ直URLでアクセスする。', '本来は遮断される（現状は全件閲覧できる＝不備）。', 'none', false, 'STG-ADM-03-01'],

    ['STG-SCN-032', 1, '管理者で対象テストアンケートを開き、名刺データ化の作業状態（データ化中）と照合一覧（総件数・一致/不一致/未入力）を確認する。', 'データ化が開始済みで、照合対象の件数が表示される。', 'none', false, 'STG-ADM-08-01'],
    ['STG-SCN-032', 2, '名刺入力・照合を進め、全レコードを照合完了状態にする（照合完了処理の実行含む）。', '照合完了し、未入力数0・不一致0など完了相当の状態になる。', 'medium', true, 'STG-ADM-08-04,STG-FLOW-MATCH-01'],
    ['STG-SCN-032', 3, '照合一覧で「完成データ確認」を実行し、生成CSVが実際に取得できるか確認する。', 'CSV生成処理が200を返し、DL先URL（/storage/csv/<file>.csv 等）が404にならずCSVが取得できる。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-032', 4, '照合一覧で「全レコードDL」を実行し、全レコードCSVが取得できるか確認する。', '全レコードCSVが200で取得でき、回答内容・設問見出し・名刺入力項目が欠落なく含まれる。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-032', 5, '完了データ確定（CSVアップロード等）でデータ化完了（DATA_READY）へ遷移させる。', 'データ化完了状態になり、完了通知が発火する（要許可）。', 'medium', true, 'STG-ADM-02-04'],
    ['STG-SCN-032', 6, 'ユーザー側ダッシュボードで対象アンケートのステータスとダウンロード導線を確認する。', '「会期終了（データ化完了）」表示になり、完成データCSV／名刺画像ZIPのダウンロード導線が表示される。', 'none', false, 'DSH-001'],
    ['STG-SCN-032', 7, 'ユーザー側でデータダウンロードを実行する。', '完成データCSV／ZIPが200で取得でき、ファイルが開ける。', 'low', false, ''],

    ['STG-SCN-033', 1, 'スピードプランがオンデマンドの対象アンケートを特定し、名刺データ化が開始済みであることを確認する。', '対象アンケートのプランがオンデマンドで、データ化中（一部のみ完了）の状態が確認できる。', 'none', false, 'BIZ-001'],
    ['STG-SCN-033', 2, '全レコードのうち一部のみを照合完了させ、未完了レコードが残る状態を作る。', '一部レコードが照合完了、残りが未完了の途中状態になる。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-033', 3, '管理者側「完成データ確認」「全レコードDL」で、確定済み分のデータが取得できるか確認する。', '全件未完了でも、確定済みレコード分のCSVが200で取得できる。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-033', 4, 'ユーザー側ダッシュボードで、全件完了前でもダウンロード導線が活性化し、確定済み分が取得できるか確認する。', 'オンデマンドでは途中段階でもDL導線が活性化し、確定済み分が取得できる（通常プランとの差を記録）。', 'low', false, 'DSH-001'],
    ['STG-SCN-033', 5, '残りレコードを追加で照合完了させ、再度ダウンロードして取得件数の変化を確認する。', '再ダウンロードで件数が増え、順次納品されていることが確認できる。', 'medium', true, 'STG-ADM-08-04'],

    ['STG-SCN-034', 1, '【回答者】324の公開回答URL（https://stg.speed-ad.com/questionnaire_answer?id=324）を開く。', '「STGシナリオテスト 長期展示会」の回答画面とSTGテスト用・ダミーデータ扱いの注記が表示される。', 'none', false, 'ANS-030'],
    ['STG-SCN-034', 2, '【回答者】Q.01〜Q.09の必須設問に回答する（単一/複数選択・自由記述・5段階・数値・プルダウン・日時・マトリクス・手書きメモ）。', '各設問の入力・選択・手書き描画が保持され、必須が埋まる。', 'none', false, 'ANS-011,ANS-013'],
    ['STG-SCN-034', 3, '【回答者】フッター「名刺を撮影」→「ストレージから選択」で名刺テスト画像（fixtures/meishi_test.png）をアップロードする。', '3ステップウィザードの表面プレビューが表示される。', 'none', false, 'ANS-028'],
    ['STG-SCN-034', 4, '【回答者】「裏面をスキップ」→最終確認で「アップロード完了」を押す。', '名刺画像（表）が添付状態になる（名刺なしは「名刺が手元に無い方」分岐を別途確認）。', 'none', false, 'ANS-028,ANS-029'],
    ['STG-SCN-034', 5, '【回答者】「送信する」を押す。', '/survey-thanks（回答完了）へ遷移し、回答＋名刺画像が保存される（stgデータ更新のため要許可）。', 'medium', true, 'ANS-030'],
    ['STG-SCN-034', 6, '【Lv3/Lv4】アンケート管理（admin/surveys）を開き、アンケートID 324 で検索する。', '324行の「実際の件数」が送信分だけ増え、名刺画像ダウンロード／完了データアップロード入口が表示される。', 'none', false, 'STG-ADM-02-01'],
    ['STG-SCN-034', 7, '【Lv3/Lv4】324行の「ダウンロード」（名刺画像）を実行する。', '名刺画像ZIP（_ncpics.zip）が200で実取得でき（ファイルが保存される）、送信した名刺画像（jpg）が含まれる。', 'low', false, 'STG-ADM-02-03'],
    ['STG-SCN-034', 8, '【Lv1】名刺入力画面（admin/data_input_list）を開き、グループ1（メールアドレス）の作業可能件数に324分が計上されることを確認する。', '会期終了を待たず名刺送信時点でグループ1の件数が増える（グループ2〜8はメール確定後に開く）。', 'none', false, 'STG-ADM-07'],
    ['STG-SCN-034', 9, '【Lv1】グループ1の入力作業画面（admin/data_input_screen?id=1）を開き、名刺画像（表）が正しく表示されることを確認する。', '【正常系チェック】名刺画像が表示されること。※2026-06-03時点はfiles.speed-ad.comの署名画像がERR_BLOCKED_BY_ORBで表示されない不具合あり。', 'none', false, 'STG-FLOW-DATA-01'],
    ['STG-SCN-034', 10, '【Lv1】メールアドレスを入力し「確定（Ctrl+Enter）」する。', '入力が保存され次レコードへ前進する。確定したレコードが照合対象（matching_list）に出現する（要許可）。', 'medium', true, 'STG-FLOW-DATA-01'],
    ['STG-SCN-034', 11, '【Lv3】照合画面（admin/matching_list）でアンケートID 324 を検索する。', '324カードが表示され、納品期日・総件数・一致/不一致/未入力数と「照合作業の開始／完成データ確認／全レコードDL」導線が出る。', 'none', false, 'STG-ADM-08-01'],
    ['STG-SCN-034', 12, '【Lv3】「照合作業の開始」（matching_screen?id=324）で各項目の「確定」をチェックし「保存」→確認モーダルで「OK」する。', '手動照合が確定し次レコードへ前進する。全項目確定で一致数が増える（要許可）。', 'medium', true, 'STG-FLOW-MATCH-01'],
    ['STG-SCN-034', 13, '【Lv3】照合一覧で「全レコードDL」「完成データ確認」を実行する。', '【正常系チェック】完成CSVが実際にDLできること。※2026-06-03時点はPOST /csv_export2が200を返すが実ファイルが配信されずDLされない不具合あり（SPDAD2026-146系）。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-034', 14, '【Lv3/Lv4】アンケート管理の「アップロード」（完了データ）で完了データを登録し、ステータスをアップ完了へ進める。', 'アップ完了になり、完了通知（SM-007）が発火する（要許可）。', 'medium', true, 'STG-ADM-02-04'],
    ['STG-SCN-034', 15, '【企業ユーザー】（324所有アカウント）でアンケート行クリック→詳細モーダル→「データダウンロード」を開く。', '「回答データ／名刺入力＋回答データ／名刺入力データ／名刺画像」の4種と各利用可否、期間（全て／期間指定）が表示される。', 'none', false, 'DSH-001'],
    ['STG-SCN-034', 16, '【企業ユーザー】データ化完了後、「名刺入力データ」「名刺画像」が"利用可能"であることを確認し、期間「全て」でダウンロードする。', '名刺入力データ・名刺画像が実取得できる（通常プランはユーザー側DLが会期終了後＝後日に利用可能化する想定）。', 'low', false, 'DSH-001'],

    ['STG-SCN-035', 1, '【回答者】325の公開回答URL（https://stg.speed-ad.com/questionnaire_answer?id=325）を開く。', '「STG照合反映テスト 1日展示会」の回答画面が表示される（既存回答あり）。', 'none', false, 'ANS-030'],
    ['STG-SCN-035', 2, '【回答者】Q.01〜Q.05の必須設問に回答する（単一/複数選択・自由記述・5段階・数値）。', '各入力が保持され、必須が埋まる。', 'none', false, 'ANS-011,ANS-013'],
    ['STG-SCN-035', 3, '【回答者】「名刺を撮影」→「ストレージから選択」で名刺テスト画像（fixtures/meishi_test.png）をアップロード→「裏面をスキップ」→「アップロード完了」。', '名刺画像（表）が添付される。', 'none', false, 'ANS-028'],
    ['STG-SCN-035', 4, '【回答者】「送信する」を押す。', '/survey-thanks へ遷移し、回答＋名刺が保存され回答件数が増える（要許可）。', 'medium', true, 'ANS-030'],
    ['STG-SCN-035', 5, '【Lv3/Lv4】アンケート管理（admin/surveys）を開き 325 を検索し、データ化完了予定日が当日（オンデマンド）であることを確認する。', '325行の完了予定日＝会期当日相当で、名刺画像ダウンロード／完了データアップロード入口が表示される。', 'none', false, 'STG-ADM-02-01'],
    ['STG-SCN-035', 6, '【Lv3/Lv4】325行の「ダウンロード」（名刺画像）を実行する。', '名刺画像ZIP（_ncpics.zip）が200で実取得できる。', 'low', false, 'STG-ADM-02-03'],
    ['STG-SCN-035', 7, '【Lv1】名刺入力画面（data_input_list）でグループ1に325分が計上されることを確認し、入力作業画面（data_input_screen?id=1）で名刺画像が表示されるか確認する。', 'グループ1件数が増える。【正常系チェック】名刺画像表示（※現状ERR_BLOCKED_BY_ORBで非表示の不具合）。', 'none', false, 'STG-ADM-07'],
    ['STG-SCN-035', 8, '【Lv1】メールアドレスを入力し「確定」する。', '入力保存・前進し、325が照合対象（matching_list）に出現する（オンデマンドは会期終了を待たず当日対象化＝実走確認済）（要許可）。', 'medium', true, 'STG-FLOW-DATA-01'],
    ['STG-SCN-035', 9, '【Lv3】照合画面（matching_list）で 325 を検索し「照合作業の開始」で一部レコードを「確定」→「保存」→「OK」する。', '手動照合が確定し、一部のみ完了の途中状態になる（要許可）。', 'medium', true, 'STG-FLOW-MATCH-01'],
    ['STG-SCN-035', 10, '【Lv3】途中段階で照合一覧の「全レコードDL」「完成データ確認」を実行する。', '【正常系チェック】オンデマンドは入力・照合が進んだ「そこまでの分」のCSVが取得できること。※現状はPOST /csv_export2が200だが実ファイルが配信されずDLされない不具合あり（SPDAD2026-146系）。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-035', 11, '【企業ユーザー】（325所有アカウント）で詳細モーダル→「データダウンロード」を開く。', '4種のダウンロードオプション（回答データ／名刺入力＋回答データ／名刺入力データ／名刺画像）と利用可否が表示される。', 'none', false, 'DSH-001'],
    ['STG-SCN-035', 12, '【企業ユーザー】オンデマンドにより全件完了前でも「名刺入力データ」「名刺画像」が"利用可能"であることを確認し、確定済み分をダウンロードする。', '会期終了／全件完了を待たず確定済み分が利用可能化し取得できる（通常プラン324との差を記録）。', 'low', false, 'DSH-001'],
    ['STG-SCN-035', 13, '【Lv3→企業ユーザー】残りレコードを照合確定し、管理者側・ユーザー側で再度ダウンロードして取得件数の増加を確認する。', '再DLで件数が増え、順次納品されることが確認できる（要許可）。', 'medium', true, 'STG-ADM-08-04']
  ].map(([scenarioId, stepNo, action, expected, sideEffect, requiresPermission, linkedCaseIds]) => ({
    scenario_id: scenarioId,
    step_id: `${scenarioId}-${String(stepNo).padStart(2, '0')}`,
    step_no: stepNo,
    action,
    expected,
    side_effect: sideEffect,
    requires_permission: requiresPermission,
    linked_case_ids: linkedCaseIds ? linkedCaseIds.split(',') : []
  }));

  const sheetSchemas = [
    {
      tab: 'scenarios',
      purpose: 'シナリオマスタ',
      columns: ['scenario_id', 'title', 'role_scope', 'scenario_group', 'priority', 'side_effect', 'start_url', 'objective', 'linked_case_ids', 'stg_observation_status', 'expected_outcome', 'evidence_policy', 'notes', 'active']
    },
    {
      tab: 'scenario_steps',
      purpose: 'シナリオ手順マスタ',
      columns: ['scenario_id', 'step_id', 'step_no', 'action', 'expected', 'side_effect', 'requires_permission', 'linked_case_ids', 'active']
    },
    {
      tab: 'scenario_runs',
      purpose: 'シナリオ実行回',
      columns: ['run_id', 'environment', 'base_url', 'tester', 'browser', 'viewport', 'started_at', 'ended_at', 'note']
    },
    {
      tab: 'scenario_step_results',
      purpose: 'シナリオ手順別結果',
      columns: ['run_id', 'scenario_id', 'step_id', 'status', 'actual', 'evidence_url', 'checked_at', 'checked_by', 'defect_link', 'note']
    }
  ];

  window.E2E_SCENARIOS = scenarios;
  window.E2E_SCENARIO_STEPS = steps;
  window.E2E_SCENARIO_SHEET_SCHEMAS = sheetSchemas;
})();
