(function () {
  const scenarios = [
    {
      scenario_id: 'STG-SCN-001',
      title: 'ログインからダッシュボード表示',
      role_scope: 'ユーザー',
      scenario_group: '認証・ダッシュボード',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'stgの企業ユーザー導線でログイン後にダッシュボードへ到達し、アンケート一覧の主要情報を確認できることを検証する。',
      linked_case_ids: ['LGN-001', 'DSH-001', 'DSH-004'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: 'ログイン後にダッシュボードが表示され、アンケート一覧、詳細導線、主要ナビゲーションが操作できる。',
      evidence_policy: 'ダッシュボード初期表示、一覧行、コンソールエラーなしのスクリーンショットを残す。',
      notes: '実データの会社名や個人情報は証跡に残さない。'
    },
    {
      scenario_id: 'STG-SCN-002',
      title: 'アンケート詳細とQR/回答URL確認',
      role_scope: 'ユーザー',
      scenario_group: 'QR・回答',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'ダッシュボード上のアンケートから詳細、QR、回答URLの確認導線がつながることを検証する。',
      linked_case_ids: ['DSH-003', 'QR-001', 'QR-002', 'QR-003', 'QR-004'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: 'アンケート詳細またはQR表示から回答URL相当の情報を確認でき、コピー操作後も画面が破綻しない。',
      evidence_policy: 'QRまたは回答URL表示部、コピー後トースト、コンソールエラーなしを記録する。',
      notes: 'コピー先の実URLは必要に応じて一部マスクする。'
    },
    {
      scenario_id: 'STG-SCN-003',
      title: '回答プレビューで完了表示まで確認',
      role_scope: 'ユーザー',
      scenario_group: 'QR・回答',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: '回答画面のプレビューまたは安全な確認導線で、入力から完了表示までの体験を副作用なしで確認する。',
      linked_case_ids: ['ANS-004', 'ANS-005', 'ANS-007', 'ANS-011', 'ANS-012', 'ANS-013', 'ANS-023'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: '設問表示、入力保持、送信操作後のプレビュー完了表示が確認でき、実回答保存が発生しない。',
      evidence_policy: '回答画面、入力済み状態、プレビュー完了表示を記録する。',
      notes: 'プレビュー導線がない場合は送信直前までで止め、結果は「要許可」にする。'
    },
    {
      scenario_id: 'STG-SCN-004',
      title: '回答本送信の事前確認',
      role_scope: 'ユーザー',
      scenario_group: 'QR・回答',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: '来場者回答の本送信導線が成立することを、stgデータ更新リスクを明示して確認する。',
      linked_case_ids: ['ANS-019', 'ANS-020', 'ANS-021', 'ANS-022'],
      stg_observation_status: 'stg未観測/明示許可待ち',
      expected_outcome: '必須入力後に送信確認または完了導線へ進める。明示許可がない場合は本送信せず、直前状態までを確認する。',
      evidence_policy: '送信直前状態、確認ダイアログまたは要許可判断を記録する。',
      notes: '本送信はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-005',
      title: 'アンケート作成から編集画面確認',
      role_scope: 'ユーザー',
      scenario_group: 'アンケート作成・編集',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'アンケート作成画面で基本情報、設問、設定タブの導線が一連で確認できることを検証する。',
      linked_case_ids: ['CRT-001', 'EDT-001', 'EDT-002', 'EDT-022', 'EDT-027', 'EDT-028'],
      stg_observation_status: 'stg未観測/明示許可待ち',
      expected_outcome: '新規作成または編集画面で基本情報と設問操作UIが表示され、保存が必要な操作は直前で止められる。',
      evidence_policy: '作成/編集画面、設問追加メニュー、保存直前状態を記録する。',
      notes: '保存や公開はstgデータ変更のため原則実行しない。'
    },
    {
      scenario_id: 'STG-SCN-006',
      title: '名刺データ化設定と見積表示',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: '名刺データ化設定でプラン、件数、見積、関連導線の表示を確認する。',
      linked_case_ids: ['BIZ-001', 'BIZ-002'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: 'データ化有無、想定件数、見積または料金表示が確認でき、保存が必要な操作は直前で止められる。',
      evidence_policy: '設定画面、見積表示、保存前状態を記録する。',
      notes: '料金・件数など実データは必要最小限にマスクする。'
    },
    {
      scenario_id: 'STG-SCN-007',
      title: 'お礼メール設定の表示確認',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'お礼メール設定で文面、送信対象、送信タイミング、保存入口を確認する。',
      linked_case_ids: ['THX-001', 'MAIL-001', 'MAIL-002'],
      stg_observation_status: 'stg未観測/明示許可待ち',
      expected_outcome: 'メール文面と送信対象の設定UIが表示され、保存や送信は許可がない限り実行しない。',
      evidence_policy: '設定画面、送信対象、保存/送信前状態を記録する。',
      notes: '実メール送信の可能性がある操作は必ず停止する。'
    },
    {
      scenario_id: 'STG-SCN-008',
      title: '請求一覧から請求詳細確認',
      role_scope: 'ユーザー',
      scenario_group: 'ダウンロード・請求',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: '企業ユーザー側で請求一覧、請求詳細、印刷用ビューの導線を確認する。',
      linked_case_ids: ['INV-001', 'INV-002', 'INV-003'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: '請求一覧から詳細へ遷移でき、請求先、明細、合計金額、印刷導線が表示される。',
      evidence_policy: '請求一覧、詳細、印刷ビュー入口を記録する。',
      notes: '金額や請求先などの実値はマスクする。'
    },
    {
      scenario_id: 'STG-SCN-009',
      title: '管理者ログインと主要画面巡回',
      role_scope: '管理者',
      scenario_group: '管理者共通',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/login',
      objective: '管理者ログイン後にトップへ入り、主要管理画面リンクが切れずに巡回できることを検証する。',
      linked_case_ids: ['STG-COMMON-01', 'STG-ADM-00', 'STG-AX-01', 'STG-AX-02'],
      stg_observation_status: 'stg観測資料あり/再確認待ち',
      expected_outcome: '管理者トップと主要リンクが表示され、遷移時にログインへ戻されない。',
      evidence_policy: '管理者トップ、主要リンク、代表遷移先、コンソールエラーなしを記録する。',
      notes: 'ログアウト確認は最後に実行する。'
    },
    {
      scenario_id: 'STG-SCN-010',
      title: '管理者の利用者・アンケート・請求検索',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '管理者側の主要一覧で検索、リセット、ページング、関連導線を確認する。',
      linked_case_ids: ['STG-ADM-01', 'STG-ADM-02', 'STG-ADM-03', 'STG-AX-03'],
      stg_observation_status: 'stg観測資料あり/再確認待ち',
      expected_outcome: '利用者、アンケート、請求の各一覧で条件入力とリセットができ、関連導線へ進める。',
      evidence_policy: '各一覧の検索フォーム、検索後表示、リセット後表示を記録する。',
      notes: '実データ値は証跡に残さず、編集保存や削除確定は実行しない。'
    },
    {
      scenario_id: 'STG-SCN-011',
      title: '管理者のクーポン検索と実績確認',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/coupon',
      objective: 'クーポン管理の検索/編集入口と、オペレーター実績確認の集計表示入口を確認する。',
      linked_case_ids: ['STG-ADM-04', 'STG-ADM-10'],
      stg_observation_status: 'stg観測資料あり/再確認待ち',
      expected_outcome: 'クーポン検索条件を操作でき、編集または利用履歴の入口が表示される。実績確認では期間/所属条件、集計表示、CSV入口が確認できる。',
      evidence_policy: 'クーポン検索条件、一覧、編集/利用履歴入口、実績確認の集計表示を記録する。',
      notes: 'クーポン作成や保存は実行しない。実績CSVは必要時のみ実行する。'
    },
    {
      scenario_id: 'STG-SCN-012',
      title: '管理者の営業日とオペレーター入口確認',
      role_scope: '管理者',
      scenario_group: '管理者設定',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '営業日カレンダーとオペレーター管理の更新系入口を、データ変更せず確認する。',
      linked_case_ids: ['STG-ADM-05', 'STG-ADM-09', 'STG-AX-04'],
      stg_observation_status: 'stg観測資料あり/再確認待ち',
      expected_outcome: '営業日設定UI、オペレーター検索、新規作成/編集/削除入口が表示され、確定操作は止められる。',
      evidence_policy: '営業日設定画面、オペレーター一覧、更新系入口を記録する。',
      notes: '決定、保存、削除確定は明示許可がない限り実行しない。'
    },
    {
      scenario_id: 'STG-SCN-013',
      title: '管理者の名刺入力・照合・エスカレーション導線',
      role_scope: '管理者',
      scenario_group: '管理者業務フロー',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '名刺入力、照合、エスカレーション確認の作業入口を確認する。',
      linked_case_ids: ['STG-ADM-07', 'STG-FLOW-DATA-01', 'STG-ADM-08', 'STG-FLOW-MATCH-01', 'STG-FLOW-ESCALE-01'],
      stg_observation_status: 'stg観測資料あり/一部未到達',
      expected_outcome: '名刺入力対象、作業画面入口、照合検索、エスカレーション導線が確認でき、確定/スキップは止められる。',
      evidence_policy: '一覧、作業入口、リダイレクトまたは未到達理由を記録する。',
      notes: '観測資料上、照合作業画面とエスカレーション確認は未到達のため、到達可否を結果に記録する。'
    },
    {
      scenario_id: 'STG-SCN-014',
      title: 'ユーザー作成アンケートと請求の管理者横断確認',
      role_scope: '横断',
      scenario_group: '請求横断',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'ユーザー側で確認したアンケート/請求の情報を、管理者側のアンケート検索と請求/請求書検索で追えることを確認する。',
      linked_case_ids: ['CRT-001', 'DSH-001', 'INV-001', 'INV-002', 'STG-ADM-02', 'STG-ADM-03', 'STG-ADM-06'],
      stg_observation_status: 'stg未観測/既存セッション確認待ち',
      expected_outcome: 'ユーザー側のアンケート/請求表示と、管理者側のアンケート/請求検索の表示観点を比較でき、データ更新なしで導線を確認できる。',
      evidence_policy: 'ユーザー側アンケート/請求、管理者側アンケート検索、請求検索、請求書検索結果を記録する。',
      notes: 'アンケート名、金額、請求先、会社名はマスクし、同一性の厳密判定は今回の期待結果に含めない。'
    },
    {
      scenario_id: 'STG-SCN-015',
      title: 'グループ切替で別アカウントの一覧/請求を確認',
      role_scope: 'ユーザー',
      scenario_group: '認証・ダッシュボード',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'アカウント情報パネルのグループ切替で、個人アカウントとグループでアンケート一覧・請求のデータコンテキストが切り替わることを検証する。',
      linked_case_ids: ['ACC-002', 'GRP-001', 'GRP-003', 'DSH-001', 'INV-001'],
      stg_observation_status: 'stg一部観測/グループ切替の実行は未',
      expected_outcome: 'グループ選択コンボで個人とグループを切り替えると、一覧と請求の表示が切替後の内容になる。',
      evidence_policy: '切替前後の一覧・請求一覧、選択中グループ表示を記録する。',
      notes: '会社名や請求先などの実データはマスクする。'
    },
    {
      scenario_id: 'STG-SCN-016',
      title: 'グループ新規作成の通し',
      role_scope: 'ユーザー',
      scenario_group: '認証・ダッシュボード',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'アカウント情報パネルからグループ新規作成導線を起動し、作成確定の直前まで確認する。',
      linked_case_ids: ['ACC-002', 'GRP-002'],
      stg_observation_status: 'stg未観測/作成導線は未起動',
      expected_outcome: '「グループ新規作成」から作成フォームへ進める。確定はstgデータ変更のため許可がない限り実行しない。',
      evidence_policy: '作成フォーム、入力状態、確定前状態を記録する。',
      notes: 'グループ作成はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-017',
      title: 'SPEEDレビューの集計・絞り込み通し',
      role_scope: 'ユーザー',
      scenario_group: 'SPEEDレビュー',
      priority: 'P1',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/dashboard',
      objective: '回答が存在するアンケートのSPEEDレビューで、集計表示・個別回答・フィルタが確認できることを検証する。',
      linked_case_ids: ['REV-004', 'REV-005', 'REV-006', 'REV-007', 'REV-008', 'REV-009'],
      stg_observation_status: 'stg観測済(回答0件)/回答ありデータが必要',
      expected_outcome: '回答総数・集計データ・個別回答テーブルが表示され、ソート/ページング/フィルタが操作できる。',
      evidence_policy: '集計表、個別回答テーブル、フィルタ操作前後を記録する。',
      notes: '回答者の氏名・会社名はマスクする。観測時は回答0件のため、回答ありアンケートでの再確認が必要。'
    },
    {
      scenario_id: 'STG-SCN-018',
      title: '名刺データ化の見積確定直前まで',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: '名刺データ化設定でプラン選択・見込み枚数・クーポン適用に応じて見積が更新されることを、確定の直前まで確認する。',
      linked_case_ids: ['BIZ-001', 'BIZ-003', 'BIZ-004', 'BIZ-007', 'BIZ-011'],
      stg_observation_status: 'stg観測済/確定は未実行',
      expected_outcome: 'プラン・枚数・クーポンに応じて請求見込み金額が自動更新され、必須充足で確定ボタンが活性化する。確定は許可がない限り実行しない。',
      evidence_policy: 'プラン選択、見積更新、クーポン適用、確定前状態を記録する。',
      notes: '依頼確定はstgデータを変更するため、実行前にユーザー許可が必要。料金・件数は必要最小限にマスクする。'
    },
    {
      scenario_id: 'STG-SCN-019',
      title: 'お礼メール文面作成からプレビュー確認',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/',
      objective: 'お礼メール設定で送信方式選択・差し込み変数挿入・リアルタイムプレビュー同期を、保存の直前まで確認する。',
      linked_case_ids: ['MAIL-003', 'MAIL-006', 'MAIL-007', 'MAIL-012'],
      stg_observation_status: 'stg観測済(編集可状態での再確認が必要)',
      expected_outcome: '送信方式が選択でき、本文へ差し込み変数を挿入するとプレビューが置換後の文面で同期する。保存・送信は許可がない限り実行しない。',
      evidence_policy: '送信方式、本文と差し込み変数、プレビュー、保存前状態を記録する。',
      notes: '保存・送信はstgデータ変更や実送信の可能性があるため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-020',
      title: 'お礼メール期限切れ時の代替導線',
      role_scope: 'ユーザー',
      scenario_group: '名刺・お礼メール',
      priority: 'P1',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/',
      objective: '送信期限が終了したアンケートのお礼メール設定で、期限切れ状態の表示と対象者リスト確認の代替導線を検証する。',
      linked_case_ids: ['MAIL-011', 'MAIL-008'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '「送信期限が終了しています」バナーと各入力のdisabled、対象者リスト確認の代替導線が表示される。',
      evidence_policy: '期限切れバナー、disabled状態、対象者リスト導線を記録する。',
      notes: '対象者の実データはマスクする。'
    },
    {
      scenario_id: 'STG-SCN-021',
      title: 'アンケート詳細モーダル起点の設定画面横断',
      role_scope: 'ユーザー',
      scenario_group: '認証・ダッシュボード',
      priority: 'P1',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/dashboard',
      objective: 'ダッシュボードの行クリックで開く詳細モーダルから、名刺データ化設定・お礼メール設定への導線がつながることを検証する。',
      linked_case_ids: ['DTL-001', 'DTL-007', 'BIZ-001', 'MAIL-001'],
      stg_observation_status: 'stg観測済/横断遷移は未実行',
      expected_outcome: '詳細モーダルが開き、基本情報・URL・QRが表示され、各設定画面へ遷移して戻れる。',
      evidence_policy: '詳細モーダル、各設定画面の遷移先見出しを記録する。',
      notes: 'アンケート名や請求関連の実データはマスクする。'
    },
    {
      scenario_id: 'STG-SCN-022',
      title: '回答（名刺撮影分岐）通し',
      role_scope: 'ユーザー',
      scenario_group: 'QR・回答',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/questionnaire_answer?id={surveyId}',
      objective: '回答画面で必須入力後、名刺撮影フローと「名刺が手元に無い方」分岐を、送信の直前まで確認する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'ANS-029'],
      stg_observation_status: 'stg観測済/送信・撮影は未実行',
      expected_outcome: '必須充足で送信ボタンが活性化し、名刺撮影と名刺なしの分岐に進める。本送信は許可がない限り実行しない。',
      evidence_policy: '回答入力状態、名刺撮影/名刺なし分岐、送信直前状態を記録する。',
      notes: '本送信はstgデータ更新（実回答保存）の可能性があるため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-023',
      title: 'アンケート管理のステータス絞り込みとファイル系入口確認',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/surveys',
      objective: 'アンケート管理で検索・ステータス複数絞り込み・名刺画像ダウンロード・完了データCSVアップロードの各入口を、確定の直前まで確認する。',
      linked_case_ids: ['STG-ADM-02-01', 'STG-ADM-02-02', 'STG-ADM-02-03', 'STG-ADM-02-04'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '検索とステータス絞り込みが効き、名刺画像DLとCSVアップロード入口が確認できる。アップロード確定は許可がない限り実行しない。',
      evidence_policy: '検索結果、ステータス絞り込み、DL/アップロード入口、確定前状態を記録する。',
      notes: '完了データCSVアップロードの確定はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-024',
      title: '請求管理の直接編集とクーポン割引確認（保存直前）',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/payment',
      objective: '請求管理で検索・直接編集・クーポン割引率/メモ表示を、保存の直前まで確認する。',
      linked_case_ids: ['STG-ADM-03-01', 'STG-ADM-03-03', 'STG-ADM-03-04'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '会社名/氏名検索が効き、直接編集の入力ができ、クーポン割引率・メモが表示される。保存は許可がない限り実行しない。',
      evidence_policy: '検索結果、直接編集の入力状態、クーポン割引表示、保存前状態を記録する。',
      notes: '直接編集の保存はstgデータを変更するため、実行前にユーザー許可が必要。金額・請求先はマスクする。'
    },
    {
      scenario_id: 'STG-SCN-025',
      title: 'クーポン新規作成から利用履歴確認（作成直前）',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/coupon',
      objective: 'クーポン管理で検索・新規作成フォーム・利用履歴を、作成の直前まで確認する。',
      linked_case_ids: ['STG-ADM-04-01', 'STG-ADM-04-02', 'STG-ADM-04-04'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: 'クーポン検索が効き、新規作成フォームに入力でき、既存クーポンの利用履歴が表示される。作成確定は許可がない限り実行しない。',
      evidence_policy: '検索結果、新規作成フォーム、利用履歴、作成前状態を記録する。',
      notes: 'クーポン作成はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-026',
      title: 'オペレーター新規登録の確定直前（権限レベル/対応言語）',
      role_scope: '管理者',
      scenario_group: '管理者設定',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/operator_list',
      objective: 'オペレーター管理で新規登録フォームの権限レベル選択・対応言語複数選択を、登録の直前まで確認する。',
      linked_case_ids: ['STG-ADM-09-03', 'STG-ADM-09-04', 'STG-ADM-09-05', 'STG-ADM-09-06'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '権限レベル（レベル1〜4）と対応言語が選択でき、必須入力後に登録ボタンが活性化する。登録は許可がない限り実行しない。',
      evidence_policy: '新規登録フォーム、権限レベル選択、対応言語選択、登録前状態を記録する。',
      notes: 'オペレーター登録はstgデータを変更するため、実行前にユーザー許可が必要。'
    },
    {
      scenario_id: 'STG-SCN-027',
      title: 'オペレーター実績のタブ・集計・CSV入口確認',
      role_scope: '管理者',
      scenario_group: '管理者一覧検索',
      priority: 'P1',
      side_effect: 'low',
      start_url: 'https://stg.speed-ad.com/admin/achievements',
      objective: 'オペレーター実績確認で集計タブ切替・項目別集計・CSV出力入口を確認する。',
      linked_case_ids: ['STG-ADM-10-01', 'STG-ADM-10-03', 'STG-ADM-10-05'],
      stg_observation_status: 'stg観測済/2026-05-31',
      expected_outcome: '所属グループ別/オペレーター別の集計表が切替表示され、項目別集計の詳細とCSV出力入口が確認できる。',
      evidence_policy: '集計タブ、項目別集計、CSV出力入口を記録する。',
      notes: 'オペレーター名・報酬額などの実データはマスクする。CSV出力は必要時のみ実行する。'
    },
    {
      scenario_id: 'STG-SCN-028',
      title: '照合の検索・KPI・作業/エスカレーション導線確認',
      role_scope: '管理者',
      scenario_group: '管理者業務フロー',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/matching_list',
      objective: '照合画面で検索・作業ステータス絞り込み・KPI表示・各作業導線を確認する。',
      linked_case_ids: ['STG-ADM-08-01', 'STG-ADM-08-02', 'STG-ADM-08-03', 'STG-ADM-08-04'],
      stg_observation_status: 'stg観測済/2026-05-31（作業画面は未進入）',
      expected_outcome: '検索とステータス絞り込みが効き、KPIとカード別の照合作業/エスカレーション/完成データ確認/全レコードDL導線が表示される。作業・DLは許可がない限り実行しない。',
      evidence_policy: '検索結果、KPI、カード別導線、到達先またはリダイレクトを記録する。',
      notes: '照合作業画面・エスカレーション確認はレコード占有等の懸念があるため、進入は許可がない限り行わない。'
    },
    {
      scenario_id: 'STG-SCN-029',
      title: 'Lv1オペレーターの到達範囲検証',
      role_scope: '管理者',
      scenario_group: '管理者権限レベル',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '権限レベル1（オペレーター）でログイン後、到達できる画面が名刺入力に限定され、他画面はリダイレクト/非表示になることを検証する。',
      linked_case_ids: ['STG-ADM-00-01', 'STG-ADM-00-03', 'STG-ADM-07-01'],
      stg_observation_status: 'stg実測済（Lv1相当アカウント）/2026-06-03再確認: メニューは名刺入力のみ、matching_list・surveys直URLは/topへ遮断（正常）。名刺入力画面の名刺画像はORBで非表示（全レベル共通）',
      expected_outcome: 'トップのメニューが名刺入力のみで、他の管理画面URLへ直接アクセスすると/topへリダイレクトされる。',
      evidence_policy: 'トップのメニュー範囲、他画面アクセス時のリダイレクト、名刺入力到達を記録する。',
      notes: '到達範囲のみ確認し、作業画面の確定/スキップは実行しない。'
    },
    {
      scenario_id: 'STG-SCN-031',
      title: 'Lv3アブロードスタッフの全画面到達検証',
      role_scope: '管理者',
      scenario_group: '管理者権限レベル',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: '権限レベル3（アブロードスタッフ）でログイン後、主要12メニューに到達し各操作部品が表示されることを検証する。',
      linked_case_ids: ['STG-ADM-00-01', 'STG-ADM-00-02'],
      stg_observation_status: 'stg実測済（現アカウントLv3）/2026-06-03再確認: 10メニュー表示、照合一覧の照合作業/完成データ確認/全レコードDLの操作コントロールはLv4と同一（レベル間の可否差なし）',
      expected_outcome: 'トップにフル12メニューが表示され、各画面へ遷移して戻れる。操作部品（検索/編集/新規作成等）が表示される。',
      evidence_policy: 'トップのメニュー、各画面の到達と戻り、操作部品の表示を記録する。',
      notes: '到達・表示まで確認。保存/削除/送信の実行はしない。'
    },
    {
      scenario_id: 'STG-SCN-030',
      title: 'Lv2オペレーター管理者の到達範囲・アクセス制御検証',
      role_scope: '管理者',
      scenario_group: '管理者権限レベル',
      priority: 'P0',
      side_effect: 'none',
      start_url: 'https://stg.speed-ad.com/admin/top',
      objective: 'Lv2でメニューが2項目に制限される一方、メニュー非表示の管理画面へ直URLで到達できないこと（サーバ側でアクセス制御が強制されること）を検証する。',
      linked_case_ids: ['STG-ADM-00-01', 'STG-ADM-00-03', 'STG-ADM-01-01', 'STG-ADM-03-01'],
      stg_observation_status: 'stg実測済（2026-05-31・BUG-ADM-04検出）/2026-06-03再確認: メニューは名刺入力＋実績確認の2項目だが、admin/surveysへ直URLで到達し全53行（全社データ）が描画される＝BUG-ADM-04継続（アクセス制御の穴・データ漏洩）',
      expected_outcome: 'Lv2のメニューは名刺入力＋実績確認のみ。メニュー非表示の管理画面（利用者/請求/オペレーター管理等）へ直URLアクセスするとログインへリダイレクトされ到達できないこと。現状は到達できてしまうため不備（BUG-ADM-04）。',
      evidence_policy: 'メニュー表示、各直URLアクセス時のリダイレクト有無を記録する。',
      notes: '回帰検証用。現状は全10画面へ到達できる不備を検出。閲覧のみでデータ更新はしない。実データはマスクする。'
    },
    {
      scenario_id: 'STG-SCN-032',
      title: '名刺データ化の開始→完了→実データダウンロード（管理者・ユーザー両側）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/matching_list',
      objective: '名刺データ化対象アンケートで、データ化開始から照合完了・完了データ確定までを管理者側で進め、管理者側（完成データ確認／全レコードDL）とユーザー側（ダッシュボードのデータダウンロード）の双方で、完成CSV／データが実際に取得できる（CSV生成処理の成功だけでなくDL先が404にならず取得まで完了する）ことを検証する。',
      linked_case_ids: ['STG-ADM-08-04', 'STG-ADM-02-03', 'STG-ADM-02-04', 'BIZ-001', 'DSH-001'],
      stg_observation_status: 'stg未観測/新規（SPDAD2026-146の回帰検証を兼ねる）',
      expected_outcome: '管理者側で「完成データ確認」「全レコードDL」を実行するとCSV生成処理が200を返し、画面が組み立てるDL先（/storage/csv/<file>.csv 等）が404にならずCSVが取得できる。データ化完了（DATA_READY）後は、ユーザー側ダッシュボードでも完成データCSV／名刺画像ZIPのダウンロード導線が表示され、実際に取得できる。',
      evidence_policy: '各ダウンロードのリクエストURLとHTTPステータス、取得可否、CSVの先頭ヘッダ有無、ユーザー側のデータ化完了表示とDL導線を記録する。回答内容・氏名・会社名・メールはマスクする。',
      notes: 'SPDAD2026-146（CSV生成は200だがDL先404）の回帰検証。照合完了・完了データ確定はstgデータを変更するため要許可。専用のテスト用アンケートで実施し、本番相当データには行わない。'
    },
    {
      scenario_id: 'STG-SCN-033',
      title: 'オンデマンドプランの途中ダウンロード（順次納品）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/admin/matching_list',
      objective: 'スピードプランがオンデマンドのアンケートで、名刺データ化が開始された後、全件完了前（途中）の段階でも、照合確定済みのレコード分のデータが管理者側・ユーザー側の双方で順次ダウンロードできることを検証する。',
      linked_case_ids: ['STG-ADM-08-04', 'BIZ-001', 'DSH-001'],
      stg_observation_status: 'stg未観測/新規・要オンデマンド対象アンケート（途中DL可否は仕様上※要確認）',
      expected_outcome: 'オンデマンドプランでデータ化開始後、一部レコードのみ照合完了した段階でも、確定済み分の完成CSV／データがダウンロードでき、レコードを追加で完了させると再ダウンロード時に件数が増える（順次納品される）。通常プランとの挙動差（全件完了まで不可か）も切り分けて記録する。',
      evidence_policy: '対象アンケートのスピードプラン表示、照合完了件数（途中段階／追加後）、各段階でのDL実行結果と取得件数、ユーザー側DL導線の活性状態を記録する。実データはマスクする。',
      notes: '04_data-flow.md上、オンデマンドは当日納期・最優先処理だが「会期中処理／途中DL」の有無は※要確認のため、実挙動を観測して記録する。照合完了・DLはstgデータ変更を伴うため要許可。専用のオンデマンド対象テストアンケートで実施する。'
    },
    {
      scenario_id: 'STG-SCN-034',
      title: '324アンケートの回答＋名刺送信からデータ化・両側DLまで通し（通常プラン）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/questionnaire_answer?id=324',
      objective: '通常プランの既存アンケート（324「STGシナリオテスト 長期展示会」）で、回答者の回答送信＋名刺画像送信から、管理者側の名刺データ化入力・照合、管理者側ダウンロード（名刺画像／完成データ）、ユーザー側ダウンロードまでを回答起点で一気通貫に検証する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'ANS-029', 'STG-ADM-02-01', 'STG-ADM-02-03', 'STG-ADM-07', 'STG-ADM-08-04', 'STG-ADM-02-04', 'DSH-001', 'BIZ-001'],
      stg_observation_status: 'stg実走済(2026-06-03)/324=通常プラン・完了予定日2026-06-15。回答＋名刺送信→件数計上・名刺画像ZIP DL・data_input計上・メール確定・手動照合は成功。名刺画像表示と完成CSV DLに不具合検出（notes参照）',
      expected_outcome: '回答＋名刺画像の送信で回答件数が増え、入力作業画面・照合画面に名刺画像が表示され、管理者側で名刺画像ZIPと完成データ（完成データ確認／全レコードDL）が200で実取得でき（DL先が404・未配信にならない）、完了データアップロード後のデータ化完了で、ユーザー側ダッシュボードでも完成CSV／名刺画像が取得できる。通常プランのためユーザー側DLは会期終了後（後日）になる想定。',
      evidence_policy: '回答送信完了表示、回答件数の増分、各ダウンロードのリクエストURLとHTTPステータス・取得可否（ファイルが実際に保存されるか）、CSV先頭ヘッダ有無、入力/照合画面の名刺画像表示可否、ユーザー側DL導線の活性状態を記録する。氏名・会社名・メール等はマスクする。',
      notes: '324はSTGシナリオテスト用のダミーアンケート（送信はダミー扱い・実顧客データ入力禁止）。回答送信・名刺データ化入力・照合確定・完了データアップロードはstgデータを変更するため要許可。名刺はテスト画像（fixtures/meishi_test.png）を使用。名刺入力画面への計上は名刺送信時点で行われ会期終了を待たない（照合・完成データ納品のタイミングはプラン依存）。【2026-06-03実走で検出した正常系不具合】(1)名刺入力画面(data_input_screen)・照合画面(matching_screen)で名刺画像が表示されない（files.speed-ad.comの署名画像がERR_BLOCKED_BY_ORB）。(2)完成データの「全レコードDL／完成データ確認」がPOST /csv_export2は200を返すが実ファイルが配信されずDLされない（SPDAD2026-146系）。なおadmin/surveys行の名刺画像ZIP DLは成功する。【アカウントレベル別の確認】各ステップ先頭の【】が想定実行レベル（回答者/Lv1/Lv3/Lv4/企業ユーザー）。名刺入力(data_input)はLv1〜Lv4、照合・完成DL・アンケート管理・完了アップロードはLv3/Lv4が対象（Lv1/Lv2はメニュー非表示）。「Lv3では通るがLv4では不可（またはその逆）」を防ぐため、各管理操作は担当レベルと最上位Lv4の双方で実行し、レベル間で可否・表示差が出ないことを確認する。権限到達範囲の基礎はSTG-SCN-029〜031。STG-SCN-032（汎用版）の324具体化。ユーザー側DL確認は324所有アカウントが必要。'
    },
    {
      scenario_id: 'STG-SCN-035',
      title: '325アンケートの回答＋名刺送信からデータ化・両側DLまで通し（オンデマンドプラン）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/questionnaire_answer?id=325',
      objective: 'オンデマンドプランで作成されたアンケート（325）で、STG-SCN-034と同じ回答起点の通しフローを、当日納品・順次納品（途中DL）の観点で検証する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'STG-ADM-02-01', 'STG-ADM-02-03', 'STG-ADM-07', 'STG-ADM-08-04', 'STG-ADM-02-04', 'DSH-001', 'BIZ-001'],
      stg_observation_status: 'stg実走済(2026-06-03)/325=オンデマンド・完了予定日2026-06-03（当日）。回答＋名刺送信→件数2→4・名刺画像ZIP DL・data_input計上(グループ1)・メール確定で照合一覧に出現・手動照合(確定→保存→OK)まで成功。名刺画像表示と完成CSV DLに不具合検出（notes参照）',
      expected_outcome: 'オンデマンドのため完了予定日が当日相当で、データ化を会期終了を待たず当日に進められ、入力・照合が進んだ「そこまでの分」のCSVを途中段階でも管理者側・ユーザー側で取得でき、レコード追加で再DL件数が増える（順次納品）。回答＋名刺送信・管理者DL・ユーザーDLが通常プラン（324）より早いタイミングで成立する。',
      evidence_policy: 'データ化完了予定日表示（当日）、回答件数の増分、入力/照合画面の名刺画像表示可否、途中段階／全件完了時の取得件数とHTTPステータス・実ファイル取得可否、ユーザー側DL活性タイミング（324との差）を記録する。実データはマスクする。',
      notes: '325はSTGシナリオテスト用のダミーアンケート。オンデマンドはメール確定で照合対象化され、会期終了を待たず当日処理できる（実走で確認）。送信・データ化・照合確定・DLはstgデータ変更を伴うため要許可。【2026-06-03実走で検出した正常系不具合】(1)名刺入力画面・照合画面で名刺画像が表示されない（ERR_BLOCKED_BY_ORB）。(2)「全レコードDL／完成データ確認」がPOST /csv_export2は200だが実ファイルが配信されずDLされない（SPDAD2026-146系）＝オンデマンドの途中CSVも現状は取得不可。admin/surveys行の名刺画像ZIP DLは成功。【アカウントレベル別の確認】各ステップ先頭の【】が想定実行レベル。名刺入力(data_input)はLv1〜Lv4、照合・完成DL・アンケート管理はLv3/Lv4が対象（Lv1/Lv2はメニュー非表示）。「Lv3では通るがLv4では不可（またはその逆）」を防ぐため、各管理操作は担当レベルと最上位Lv4の双方で実行し可否・表示差が無いことを確認する。権限到達範囲の基礎はSTG-SCN-029〜031。STG-SCN-033（汎用版）の325具体化。ユーザー側DL確認は325所有アカウントが必要。'
    },
    {
      scenario_id: 'STG-SCN-036',
      title: '新規利用者アカウント作成→作成アカウントでログイン',
      role_scope: 'ユーザー',
      scenario_group: '認証・ダッシュボード',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/login',
      objective: '新規利用者がログイン画面の「新規アカウント作成」からアカウントを作成し、作成したアカウントで実際にログインしてダッシュボードへ到達できることを検証する。',
      linked_case_ids: ['LGN-001', 'DSH-001'],
      stg_observation_status: 'stg実走済(2026-06-05)/5アカウント作成＝全件成功、作成した5アカウントとも手動ログインで/dashboard到達成功。作成直後は自動ログインせず alert「アカウントが作成されました！ログインしてください。」表示→要ログイン。メール認証なし・任意の未登録メールで作成可。',
      expected_outcome: '新規アカウントが作成でき（メール認証なし）、作成したメール/パスワードでログインしてダッシュボードに到達できる。',
      evidence_policy: 'サインアップフォーム、作成完了表示、ログイン後ダッシュボードを記録する。メール・実値はマスクする。',
      notes: '【2026-07-06フロント実装更新・要再実走】/loginの「新規アカウント作成」モーダルが仮登録→確認メールリンク（モックのデモ操作）→本登録の2段階フローに変更された。Step1(モーダル内 #signup-form): #signup-name 任意 / #signup-email / #terms-agree / #privacy-handling-agree に同意して送信すると、モーダル内でStep2（確認メール送信文言＋デモ用ボタン #signup-open-verify）に切り替わる。#signup-password / #signup-password-confirm はモーダルから撤去済み。デモボタン押下で signup-verify.html?email=... に遷移し、そこで #verify-password / #verify-password-confirm を入力・送信すると完了表示になり、#verify-go-to-login で index.html?login_email=... に戻りログイン欄がメールプリフィル済みになる。上記stg_observation_status/expected_outcomeは旧UI（単一モーダル＋password欄・alert完了）での実走記録のため、新フロー導入後にstgで再実走して整合を確認する必要がある。Googleサインアップ(OAuth)は別分岐。テスト用メールは使い捨て可。'
    },
    {
      scenario_id: 'STG-SCN-037',
      title: '通常アンケート新規作成（個人）バリエーション網羅',
      role_scope: 'ユーザー',
      scenario_group: 'アンケート作成・編集',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/dashboard',
      objective: '通常アカウント（非プレミアム）の個人コンテキストで、設問タイプとそのオプション/サイズ違い（評定尺度3/5/7段階、自由記述の単一行/複数行＋文字数、数値のmin/max/step/単位、日付/時刻の表示組合せ等）を網羅した個人アンケートを5件作成し、各設問の必須回答ON/OFFを混在させて、作成→編集→保存→個人一覧反映まで検証する。',
      linked_case_ids: ['CRT-001', 'EDT-001', 'EDT-002', 'DSH-001'],
      stg_observation_status: 'stg実走中(2026-06-07)/個人コンテキストはuser_select=個人アカウント。新規作成は#newSurveyModal(survey_name/survey_title/期間/作成する)→/survey/{id}編集。評定尺度は3/5/7段階、自由記述は単一行/複数行＋最小最大文字数、数値はmin/max/step/単位、日付/時刻は「日付を表示」「時間を表示」チェック。手書き・多言語はPremium無効。【検出】新規作成ボタンでモーダルが開かない事象あり。survey/337(個人01相当)パイロット作成済み。',
      expected_outcome: '個人で5件作成でき、各編集画面で設問追加・設問タイプ選択・オプション/サイズ設定・必須回答トグルができ、保存後に個人アンケート一覧へ反映される。',
      evidence_policy: '作成モーダル入力、作成後の/survey/{id}、各設問のタイプ/オプション/必須状態、保存完了、個人一覧の反映を記録する。アカウント名・実値はマスクする。',
      notes: 'stgデータ追加のため要許可。テスト名は「STGテスト_個人NN」で識別する。非プレミアムのため手書きスペース・多言語は対象外。評定尺度は3/5/7段階のみ。複数選択の最大選択数欄は※要確認。新規作成ボタン(.new-modal-open[data-target=new])でモーダルが開かないため、回避としてモーダル表示後に作成する。グループ版はSTG-SCN-038。'
    },
    {
      scenario_id: 'STG-SCN-038',
      title: '通常アンケート新規作成（グループ）バリエーション網羅',
      role_scope: 'ユーザー',
      scenario_group: 'アンケート作成・編集',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://stg.speed-ad.com/dashboard',
      objective: '通常アカウントでグループコンテキスト（【Abroad】テストグループ_梅田）に切替え、マトリクス（単一/複数）・説明カード・必須ON/OFF回帰・手書きサイズ網羅（Premium保留）等のバリエーションを含むグループアンケートを5件作成し、作成→編集→保存→グループ一覧反映まで検証する。',
      linked_case_ids: ['CRT-001', 'EDT-001', 'EDT-002', 'GRP-001', 'GRP-003', 'DSH-001'],
      stg_observation_status: 'stg実走中(2026-06-07)/グループ切替=user_select(個人アカウント/株式会社SpeedAd/TEST/【Abroad】テストグループ_梅田)。切替後の新規作成は当該グループへ割り振られる想定（要確認）。マトリクスは行/列可変。手書きサイズ(標準200px/小100px/中300px/大500px/カスタム50px〜)はUI実在も型がPremium無効で非プレミアム到達不可。',
      expected_outcome: 'グループに切替後5件作成でき、作成したアンケートがグループコンテキストの一覧に割り振られて表示される。手書きサイズ網羅はPremium必須のため非プレミアムでは保留する。',
      evidence_policy: '切替前後の一覧、作成モーダル入力、/survey/{id}、各設問のオプション/必須状態、保存完了、グループ一覧の反映を記録する。グループ名・実値はマスクする。',
      notes: 'stgデータ追加のため要許可。テスト名は「STGテスト_グループNN」で識別する。グループ05(手書きサイズ網羅:標準/小/中/大/カスタム)はPremium無効で非プレミアム不可のため、Premiumアカウントでのみ実走する。個人版はSTG-SCN-037。グループ割り振りの確定は実走で確認する。'
    },
    {
      scenario_id: 'PRD-SCN-001',
      title: '359アンケートの回答＋名刺送信からデータ化・照合・両側DLまで通し（本番／全設問タイプ）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://speed-ad.com/questionnaire_answer?id=359',
      objective: '本番環境（speed-ad.com）の専用テストアンケート359「本番テストアンケート」で、回答者の回答送信＋名刺画像送信から、管理者側の名刺データ化入力（OCRを含め2人以上の入力が合致したレコードのみ確定）・照合、管理者側DL（名刺画像／完成データ）、ユーザー側DLまでを、STG-SCN-035と同一フローで本番環境で検証する。STG-SCN-035との差分は、環境（stg→本番）・対象アンケート（325→359）・設問タイプ（Q.01〜Q.05のみ→Q.01〜Q.10の全タイプ＋説明カード）・テストアカウント（本番Lv1〜Lv4）。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'ANS-011', 'ANS-013', 'STG-ADM-02-01', 'STG-ADM-02-03', 'STG-ADM-07', 'STG-ADM-08-04', 'STG-FLOW-DATA-01', 'STG-FLOW-MATCH-01', 'DSH-001'],
      stg_observation_status: '本番未実行（新規作成 2026-06-17・STG-SCN-035の本番版）。id=359のプラン種別・データ化完了予定日、および各設問の必須/任意は実行時にadmin/surveysと回答画面で確認する。',
      expected_outcome: 'Q.01〜Q.10（全設問タイプ）＋名刺画像の送信で回答件数が増え、名刺入力ではOCRを含め2人以上の入力が合致したレコードのみが確定して照合対象（matching_list）に出現し、Lv3以上で照合確定が進む。管理者側で名刺画像ZIPと完成データが200で実取得でき（DL先が404・未配信にならない）、ユーザー側ダッシュボードでも完成データ／名刺画像が取得できる。照合の可否・表示はLv3とLv4で差が出ない。',
      evidence_policy: '回答画面（Q.01〜Q.10）、送信完了表示、回答件数の増分、名刺入力画面の作業可能件数の減少と「2人一致で確定」する挙動、照合一覧の件数（一致/不一致/未入力）、各DLのリクエストURLとHTTPステータス・実ファイル取得可否を記録する。本番データのため、証跡にテスト名刺以外の実顧客個人情報が映り込まないことを確認し、氏名・会社名・メール等はマスクする。DLファイルは内容確認後ローカルから削除する。',
      notes: '359は本番上のテスト専用アンケート。本番テストのため、回答送信・名刺入力・照合確定・完了データ反映・DLは直前停止せず実際に実行する（テスト専用アンケート359とテストアカウントで実施する前提）。【本番課金/メール】回答送信で完了メール等が実際に送信され、名刺データ化依頼やDLで課金が発生し得る点を承知のうえ実行する。【実行後クリーンアップ】実行後はLv4でテスト回答・名刺データを整理（無効化/削除）してよい。【テストアカウント】Lv1〜Lv4を各1アカウント使用。入力作業はLv1/Lv2/Lv3の最大3アカウント、照合作業はLv3以上。ユーザー名・パスワードは本ファイルに記載しない（.env等で別管理。本ファイルはgithub.ioで公開されるため認証情報を載せない）。【入力の確定ロジック】各レコード・各項目はOCRを含め2人以上の入力が合致したときに確定する（最大3入力）。1人入力では確定せず、2人目の一致入力で確定→照合対象化することを観測する。入力者と照合者は別アカウントで分ける（入力Lv1/Lv2/Lv3→照合Lv3）。同一案件が複数アカウント/タブで重複取得されない（排他）ことも確認する。【設問】Q.01自由記述／Q.02単一選択(3)／Q.03複数選択(3)／Q.04 5段階評定／Q.05数値／Q.06ドロップダウン／Q.07マトリクス単一(2×2)／Q.08マトリクス複数(2×2)／Q.09日付・時刻／Q.10手書き＋末尾の説明カード（回答不要）。必須/任意マーカーは画面上で確認できなかったため実行時に確認し、必須は必ず埋める。【既知不具合の扱い】stgのERR_BLOCKED_BY_ORB（名刺画像非表示）／SPDAD2026-146（csv_export2が200でも実DLされない）は参考。本番では名刺画像が表示されること・実DLできることを正常系として確認し、再現したら本番の別不具合として起票する。【ベース】STG-SCN-035（stg/325・オンデマンド）の本番版。オンデマンド／順次納品（途中DL）観点を流用するが、id=359の実プランは実行時に確認する。'
    },
    {
      scenario_id: 'PRD-SCN-420',
      title: '420アンケートの多言語回答＋名刺送信からデータ化・照合・両側DLまで通し（本番／言語ランダム切替）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://speed-ad.com/questionnaire_answer?id=420',
      objective: '本番環境の多言語設定済みテストアンケート420で、回答画面上部の言語プルダウンから言語を無作為に選択して回答＋名刺画像を送信し、管理者側の名刺データ化入力（OCRを含め2人以上の入力が合致したレコードのみ確定）・照合確定、管理者側DL（名刺画像／完成データ）、ユーザー側DLまでをSTG-SCN-035と同一の通しフローで検証する。多言語観点（言語切替表示・未翻訳時の第一言語フォールバック・完成データへの回答言語記録）に加え、入力確定タイミングのパターン検証（OCR＋人間1人の2入力目で確定／人間2人一致の3入力目で確定／3入力不一致→照合画面で手動解決）と、414実走時に未実施だった最終照合の確定までを含む。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'ANS-011', 'ANS-013', 'STG-ADM-02-01', 'STG-ADM-02-03', 'STG-ADM-07', 'STG-ADM-08-01', 'STG-ADM-08-04', 'STG-FLOW-DATA-01', 'STG-FLOW-MATCH-01', 'DSH-001'],
      stg_observation_status: '本番実走済(2026-07-10)。回答＋名刺送信×10（ja3/en4/zh-Hans3・全件200）→データ化入力→照合（一致/不一致0/未入力0）→完成CSV実DLまで一気通貫成功。確定パターンA/B/C全観測（詳細はREADME_prod420_worklog_20260710.md）。420の設定言語=ja/en/zh-Hans（繁体字なし・言語コードはwiki25のzh-CN表記と不一致）。【実走で判明した本シナリオの不足】名刺画像を全件日本語表記で作成したため、名刺言語判定（回答言語×名刺言語の組合せで決まる挙動）の検証としては不十分だった。言語判定・割り振りマトリクスの検証はPRD-SCN-420L（一致）／420M（不一致）で行う。【2026-07-15追記】未実施だったユーザー側DLを実施済み：420所有アカウントのユーザー側認証情報を入手し、回答データCSV（0042000420.csv）に「アンケートの回答言語」「名刺の入力言語」列が存在し全行に記録されていることを確認。DLモーダルに言語フィルタ（すべての言語／中国語（簡体字）／日本語／英語）を発見（未シナリオ化機能→420Mステップ6で対象化）。詳細はREADME_prod420_worklog_20260715.md。',
      expected_outcome: '回答画面上部の言語プルダウンに420へ設定された言語が列挙され、選択した言語に設問文・UI文言が切り替わり、未翻訳箇所は第一言語で表示される（フォールバック）。回答＋名刺画像の送信で回答件数が増え、入力確定は3パターンが観測できる：(A)OCR正読項目は人間1人目の一致入力＝2入力目で確定、(B)OCR誤読項目は1人目入力後も未確定のまま2人目の一致入力＝3入力目で確定、(C)3入力とも不一致の項目は確定せずmatching_listに「不一致」として出現し照合画面で手動確定できる。確定レコードが照合対象（matching_list）に出現し、Lv3の照合確定→保存が全レコード（不一致の手動解決含む）で成立してLv3/Lv4で可否・表示差が無い。管理者側で名刺画像ZIPと完成データが200で実取得でき、完成データに回答時の言語（回答言語）が記録され、ユーザー側ダッシュボードでも完成データ／名刺画像が取得できる。',
      evidence_policy: '言語プルダウンの選択肢一覧、選択した言語と切替前後の設問表示、未翻訳フォールバック箇所、送信完了表示（選択言語）、回答件数の増分、入力確定挙動（2人一致・排他）、照合一覧の件数（一致/不一致/未入力）と照合確定操作、各DLのリクエストURLとHTTPステータス・実ファイル取得可否、完成データCSVの回答言語の記録を記録する。証跡にテスト名刺以外の実顧客個人情報が映り込まないことを確認し、氏名・会社名・メール等はマスクする。DLファイルは内容確認後ローカルから削除する。',
      notes: '420は本番上のテスト専用アンケート（多言語設定済み・手書き設問なし＝手書き送信WAF 403既知不具合の対象外）。【多言語の仕様正本】Backlog Wiki「25_多言語対応方針」（対応言語 ja/en/zh-CN/zh-TW、初期表示=ユーザー言語設定>ブラウザ言語>第一言語、未翻訳は第一言語へフォールバック）および「27_データ出力・CSV方針」（回答言語・名刺入力言語のCSV追記）。【言語選択】実行ごとに言語プルダウンから無作為に1言語を選ぶ。回答を複数件送る場合は回答ごとに引き直し、最低2言語をカバーする。【テストアカウント】Lv1〜Lv4を各1アカウント使用（Lv4=管理全般・状態確認／Lv3=データ化入力・照合／Lv2・Lv1=データ化入力）。ユーザー名・パスワードは本ファイルに記載しない（別管理。本ファイルはgithub.ioで公開されるため認証情報を載せない）。入力者と照合者は別アカウントで分ける（入力Lv1/Lv2→照合Lv3）。【確定パターン設計】回答（名刺）は最低3件送信し、確定タイミングの3パターンを最低1件ずつ割り当てる：(A)2入力目で確定＝OCRが正読しやすいASCII項目（メール・URL）に名刺どおりの値を入力（OCR＋人間1の一致）／(B)3入力目で確定＝OCRが誤読しやすい項目（氏名・電話・FAX）でLv1入力後の未確定を観測してからLv2が同一値を入力（人間2人の一致。OCRが偶然正読していた場合はAと同じ挙動になるため、誤読している項目を選んで観測する）／(C)不一致＝1レコードの後段グループ項目（例: 電話番号）で意図的に3入力とも異なるダミー値にして確定させず、照合画面で名刺どおりの正値を手動確定して解決する。Cを前段グループ（G1メール）で行うとレコードが後続グループへ前進しない可能性があるため後段項目で行い、不一致時のレコード前進条件は実行時に観測して記録する（※実行時観測）。【入力の確定ロジック・自動化の注意】OCRが1入力としてカウントされ2入力一致で項目確定、確定済み項目はdisabledで再入力不可（触れると操作タイムアウト）、「作業可能件数」は全アンケート横断のグローバルキュー、無関係カードのスキップは他アンケートの実レコードに作用しうる——詳細はREADME_prod414_worklog_20260630.mdを参照。【本番課金/メール】回答送信で完了メール等が実際に送信され、名刺データ化やDLで課金が発生し得る点を承知のうえ実行する。【実行後クリーンアップ】実行後はLv4でテスト回答・名刺データを整理（無効化/削除）してよい。【既知不具合の扱い】SPDAD2026-146（csv_export2が200でも実DLされない）は参考。本番で再現したら本番の別不具合として起票する。【ベース】STG-SCN-035（stg/325）の本番多言語版。PRD-SCN-001（359・全設問タイプ）の姉妹版で、差分は多言語切替の検証・回答言語のCSV記録確認・最終照合確定までの完遂。'
    },
    {
      scenario_id: 'PRD-SCN-420L',
      title: '多言語割り振り検証【一致ケース】：回答言語＝名刺言語のレコードが対応言語の入力チームに割り振られるか（本番）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://speed-ad.com/questionnaire_answer?id=424',
      objective: '回答言語と名刺表記言語が一致する4ケース（ja×日本語名刺／en×英語名刺／zh-Hans×简体字名刺／zh-Hant×繁体字名刺）を送信し、①「名刺の入力言語」（回答データCSVの実列名）がその言語に自動判定されること、②当該言語を対応可能言語とするオペレーターの名刺入力キューにのみ計上されることを検証する。判定は入力作業前・送信時点で自動付与されることが確認済み（2026-07-15）のため、本丸は②＝判定に従った割り振り、特に英語・中国語判定レコードが英・簡対応オペレーターのキューに実際に出るか（唯一の未観測点）。不一致6ケースはPRD-SCN-420Mで別途検証する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'STG-ADM-07', 'STG-FLOW-DATA-01', 'DSH-001'],
      stg_observation_status: '判定値は3マスとも観測済み・割り振りはja×jaのみ確認済み(2026-07-10実走+2026-07-15机上検証)。回答データCSVの実測で ja×ja=「日本語」／en×en=「英語」／zh×zh=「中国語（簡体字）」の判定を確認。ja×jaは日本語対応オペレーターへの割り振り→入力→照合まで完走済み。ただし英語・中国語判定レコードが簡英設定オペレーターのキューに出るかは未観測のまま420がデータ化完了となり、キューから消滅（未入力13件を残したまま完了）。420は会期終了によりSubmitが無効化され送信不可（2026-07-15実証）のため、再検証には会期再設定または検証用アンケート新設が必要。',
      expected_outcome: '一致3ケースの「名刺の入力言語」が送信時点（入力作業前）で ja×ja→日本語／en×en→英語／zh×zh→中国語（簡体字）と自動判定され、各レコードは判定言語を対応可能言語とするオペレーターの入力キューにのみ計上される。日本語のみ設定のオペレーターには英語・中国語判定レコードが出ない。グループ前進後も割り振りが維持される。',
      evidence_policy: '送信ごとの選択言語・回答本文・名刺画像の対応表、対応可能言語設定別の各アカウントにおける名刺入力画面の作業可能件数（送信ごと・グループ消化段階ごと）、ユーザー側回答データCSVの「アンケートの回答言語」「名刺の入力言語」列の値（人間確認必須）を記録する。実データはダミーのみ使用。',
      notes: '【前提（必須）】会期中のアンケートで実行する。会期終了後は回答フォームの入力・名刺アップロードまで通るがSubmitのみ無効化され送信不可（2026-07-15実証）。420は会期終了済みのため、会期再設定（要許可）または検証用アンケート新設（要許可・420Cの简繁検証と共用可）で実施する。【判定の仕組み（2026-07-15確認）】「名刺の入力言語」は入力作業と無関係に送信時点で自動付与される（未入力13レコード全件に判定値が付与済みであることを照合一覧×回答データCSVの突合で確認）。列名は実CSV準拠：「アンケートの回答言語」「名刺の入力言語」。【送信条件（必須）】回答本文も選択言語で記述する（本文が選択言語と不一致だと判定の交絡になる=2026-07-10実走の教訓）。名刺は表記言語別のダミー名刺（実顧客PIIなし）を使い、メール/URLで一意識別する。【確認手段】ユーザー側ダッシュボード→対象行のダウンロード→「回答データ」（言語フィルタ=すべての言語）でCSV取得。手順確立済み（2026-07-15・420所有アカウントのユーザー側認証情報入手済み）。判定値の確認はCSV列の人間確認を必須とする（AI観測のみでの断定禁止=BUG-003）。【運用注意】対応可能言語の設定変更は既存キューの見え方に即時影響するため検証中は固定する。日本語を外したアカウントには日本語判定の作業が一切来なくなる（オペレーター干上がり）ことをPRD-SCN-420実走で確認済み。【関連】PRD-SCN-420M（不一致ケース）、PRD-SCN-420C（简繁分離）、README_prod420_worklog_20260710.md／README_prod420_worklog_20260715.md。【2026-07-16 検証用アンケート新設で実行可能化】本番に多言語検証用3本を新設（公開API /survey/{id}/questions で構成確認済み・会期finish_date=2026-07-31・多言語ON・capture_card_flag=1・設問は説明カード1問のみ＝入力設問なし）: 424「＠簡体字繁体字」=ja/zh-Hans/zh-Hant／425「＠英語簡体字」=ja/en/zh-Hans／426「＠英語繁体字」=ja/en/zh-Hant。各3言語（ja＋他2）で3本合わせて{簡繁}{英簡}{英繁}の全ペアを網羅。回答言語プルダウンは各supported_localesのみ選択可、名刺画像の表記言語は独立（任意画像アップロード）。「会期終了で送信不可」ブロッカー解消。一致ケース割当: ja×ja=424／zh-Hans×zh-Hans=424(or425)／zh-Hant×zh-Hant=424(or426)※繁体字追加による新規4件目／en×en=425(or426)。設問が説明カードのみで回答本文が無いため判定は「選択言語×名刺表記」に単純化（本文交絡の考慮不要）。要初日確認: ①本文なしでも回答言語がCSV記録されるか ②名刺＋説明カードのみでデータ化キューに乗るか。'
    },
    {
      scenario_id: 'PRD-SCN-420M',
      title: '多言語割り振り検証【不一致ケース】：回答言語≠名刺言語の判定ルールと判定不能レコードのフォールバック先（本番）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://speed-ad.com/questionnaire_answer?id=424',
      objective: '回答言語と名刺表記言語が一致しない6ケースの「名刺の入力言語」判定値と、判定不能レコードの割り振り先（フォールバック）を統制条件で検証する。2026-07-15の机上検証で判定ルール仮説「一致→その言語／不一致で日本語が絡む→日本語／不一致で日本語なし→判定不能」が既存29レコード全件と整合しており、本シナリオはこの仮説の統制条件での確認と、判定不能レコードがどのオペレーターのキューに出るか（全員／日本語チーム／誰にも出ない=滞留）の特定が本丸。正本Wiki（25/61/63）に判定・フォールバックのルール記載がないため、結果は仕様確認または不具合起票の判断材料とし、確定後に正本への追記を提案する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'STG-ADM-07', 'STG-FLOW-DATA-01', 'DSH-001'],
      stg_observation_status: '判定値のみ既存データで観測済み・割り振り先は未観測(2026-07-15机上検証・新設)。既存29レコードの実測: ja×英語名刺=日本語／ja×简体字名刺=日本語／en×日本語名刺=日本語／zh×日本語名刺=日本語／zh×英語名刺=判定不能／en×非英語名刺=判定不能（いずれも判定ルール仮説と整合）。判定不能レコード（5件以上）がどのアカウントのキューに出るかは、420のデータ化完了によりキューが空となり未観測。',
      expected_outcome: '（仮説・※要確認）日本語が絡む不一致4ケース（ja×en名刺／ja×zh名刺／en×ja名刺／zh×ja名刺）は「名刺の入力言語」=日本語となり日本語対応オペレーターに計上される。日本語が絡まない2ケース（en×zh名刺／zh×en名刺）は「判定不能」となる。判定不能レコードの割り振り先が特定され、挙動が一貫している。「誰にも出ない（滞留）」の場合は入力されないまま納期を迎え納品漏れに直結するため、不具合として起票する。',
      evidence_policy: '送信ごとの選択言語・回答本文・名刺画像の対応表、全アカウントの名刺入力画面の作業可能件数（送信ごと）、ユーザー側回答データCSVの「アンケートの回答言語」「名刺の入力言語」列の値（人間確認必須）、判定不能レコードの割り振り先を記録する。実データはダミーのみ使用。',
      notes: '【前提（必須）】PRD-SCN-420Lと同じ環境（会期中アンケート・オペレーター対応可能言語の分離設定・ダミー名刺・対応表）を引き継いで連続実行する。会期終了後は送信不可（2026-07-15実証）。【判定ルール仮説（2026-07-15・全29レコード整合・正本未記載※要確認）】一致→その言語／不一致で日本語が絡む→日本語／不一致で日本語なし→判定不能。判定は送信時点で自動付与（入力作業と無関係）。【重要観点】判定不能のフォールバック先は納品漏れリスクに直結する。420では判定不能5件を含む未入力13件が残ったまま「データ化完了」となった実績があり（README_prod420_worklog_20260715.md）、滞留→納期強制完了の疑いがある。【確認手段】ユーザー側回答データCSV（言語フィルタ=すべての言語）。判定値の確認は人間確認必須（BUG-003）。あわせて言語フィルタを個別言語にした場合に判定不能レコードが出力されるか（DL取りこぼし）も記録する。【関連】PRD-SCN-420L（一致ケース・環境共用）、PRD-SCN-420C（简繁分離）、README_prod420_worklog_20260715.md。【2026-07-16 検証用3本新設・不一致マトリクス割当】424=ja/zh-Hans/zh-Hant・425=ja/en/zh-Hans・426=ja/en/zh-Hant（会期2026-07-31・設問は説明カードのみ・名刺画像言語は任意）。回答言語プルダウンで選べる言語により割当: ja回答×各名刺=どの本でも可／en回答×各名刺=425 or 426／zh-Hans回答×各名刺=424 or 425／zh-Hant回答×各名刺=424 or 426。簡繁分割で従来6ケースが拡張（例: en回答×繁名刺=426、繁回答×簡名刺=424）。要初日確認: 繁体字名刺の判定値が独立の繁体字値か簡体字に畳まれるか（畳まれるなら判定不能ロジックにも波及）。'
    },
    {
      scenario_id: 'PRD-SCN-420C',
      title: '简体字・繁体字の判定・割り振り分離検証（本番・要事前準備）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://speed-ad.com/questionnaire_answer?id=424',
      objective: '简体字（zh-Hans）と繁体字（zh-TW）が別言語として判定され、それぞれの言語を対応可能とするオペレーターに取り違えなく分離して割り振られることを検証する。中国語圏の名刺は简繁で字形が近く（例: 广告/廣告、质量/質量）、OCRベースの判定で最も取り違えが起きやすい組のため、一致ケースの分離確認とクロスケース（简体字回答×繁体字名刺等）の判定挙動を観測する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'STG-ADM-07', 'STG-FLOW-DATA-01'],
      stg_observation_status: '未実行（新規作成 2026-07-10）。前提未確認2点あり: ①420の対応言語は現状 ja/en/zh-Hans のみで繁体字が無い（420への追加設定 or 繁体字入り検証用アンケートの用意が必要）②オペレーター対応可能言語マスタに简体字/繁体字が別項目として存在するか（言語マスタはDB管理・画面非提供のため要確認）。',
      expected_outcome: '繁体字回答×繁体字名刺→繁体字対応オペレーターのみに計上、简体字回答×简体字名刺→简体字対応オペレーターのみに計上され、相互に取り違えがない。クロスケース（繁体字回答×简体字名刺／简体字回答×繁体字名刺）の判定値（どちらかへの寄せ or 判定不能）とフォールバック先が一貫して記録される。CSV/DBの判定列で简繁が区別されて記録される。',
      evidence_policy: '简繁で字形が異なる語を含むダミー名刺の画像、送信対応表、简体字のみ/繁体字のみを設定した各アカウントの名刺入力画面の件数、CSV/DBの判定列の値（人間確認必須）を記録する。実データはダミーのみ使用。',
      notes: '【事前準備】①アンケートの対応言語に繁体字（zh-TW）を追加する（420に追加するか、简繁両方を設定した検証用アンケートを新設。設定変更は要許可）②オペレーター対応可能言語に「简体字」「繁体字」が別項目として存在することを確認し、テストアカウントへ「简体字のみ」「繁体字のみ」を割り当てて記録する③繁体字表記のダミー名刺を用意する（简繁の判別が付くよう、字形が异なる語を必ず含める。例: 広告→广告(简)/廣告(繁)、質量→质量(简)/質量(繁)、電話→电话(简)/電話(繁)）。【送信条件】回答本文も選択言語の字体で記述する（简体字回答は简体字本文、繁体字回答は繁体字本文）。【言語コード注意】回答画面の言語コードは zh-Hans 表記、正本Wiki25は zh-CN/zh-TW 表記でコード体系が不一致。繁体字追加時にどのコードで実装されるか（zh-Hant/zh-TW）も記録する。【判定の確認】判定値はCSV/DB列の人間確認を必須とする。【関連】PRD-SCN-420L（一致ケース）／PRD-SCN-420M（不一致ケース）— 本シナリオはその简繁特化版、Wiki 25_多言語対応方針／61_対応言語とフォールバック。【2026-07-16 前提①解消・424が本拠】検証用3本を本番新設。424「＠簡体字繁体字」は supported_locales=ja/zh-Hans/zh-Hant で回答言語プルダウンから簡体字・繁体字の両方を選べる唯一の本＝本シナリオ（簡繁分離・クロス）は424で実施（会期2026-07-31・設問は説明カードのみ・名刺画像は任意アップロード）。前提①「繁体字入りアンケート」充足。言語コードは実装 zh-Hant（今回API確認）。未解決: 前提②（オペレーター対応可能言語マスタに繁体字が簡体字と別項目で存在するか＝DB管理・画面非提供）、繁体字判定値の実体（独立値か簡体字畳み込みか）、DL言語フィルタに繁体字が出るか（420では簡体字/日本語/英語のみ観測）は初日に要確認。'
    },
    {
      scenario_id: 'PRD-SCN-420J',
      title: '日本語単一アンケート（多言語OFF）の外国語名刺 判定・割り振り基準線検証（本番・423）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P0',
      side_effect: 'medium',
      start_url: 'https://speed-ad.com/questionnaire_answer?id=423',
      objective: '多言語OFF・日本語単一設定のアンケート423（設問は説明カードのみ・回答言語プルダウンなし＝回答言語ja固定）に、日本語・英語・簡体字・繁体字の4表記のダミー名刺を送信し、①「名刺の入力言語」の自動判定値、②各名刺が対応可能言語別オペレーターのどのキューに割り振られるか、③判定不能レコードが発生するか、を検証する。本番の実顧客アンケートの大多数がこの多言語OFF構成であり、外国語名刺が来たときの挙動（想定＝全件日本語判定・日本語オペへ集約・判定不能ゼロ）を確定させる基準線。多言語ON（424-426）と同一組合せ（ja回答×外国語名刺）の判定値を突き合わせ、多言語トグルで判定が変わらないことも確認する。',
      linked_case_ids: ['ANS-030', 'ANS-028', 'STG-ADM-07', 'STG-FLOW-DATA-01', 'DSH-001'],
      stg_observation_status: '判定軸 実走済(2026-07-16)。423へ ja回答固定×名刺4表記(日/英/簡/繁)×各2枚=8件を実送信し、ユーザー側回答データCSV(0042300423.csv)で判定値を回収。結果: 全8件とも「名刺の入力言語」=日本語・「アンケートの回答言語」=日本語・判定不能0（回答ID 29139-29146連番）。英/簡/繁の名刺添付は送信直前スクショで目視確認。回答画面に言語プルダウン無し・DLモーダルに言語フィルタ無し(420との差)も実証。→本命仮説A(回答ja固定→全件日本語・滞留なし)を支持。ただし仮説A(判定が回答jaを見て寄せた)と仮説B(多言語OFFは名刺判定せずアンケート言語を機械付与)は本結果では区別不能(要424-426突き合わせ)。割り振り先の複数アカウント裏取りも実施済(2026-07-16): 同8件を4アカウントで確認し、名刺入力キューG1は Lv4-02=8/Lv3-03=8/Lv2-04=0/Lv1-05=0 → 日本語判定レコードは日本語対応アカウント(02/03)にのみ出現・非対応(04/05)には出ず、対応可能言語による振分を実証。全件日本語判定のため外国語名刺(英/簡/繁)も全て日本語オペに集約され中国語オペ(チームB/C)には回らない。データ化入力はG1〜G6全キュー0までドレイン(残留なし)、照合は一致5/不一致2/未入力2(CJK氏名/部署のOCR誤読が残・主目的達成のため作り込みは中断)。詳細=README_prod423_bizcard_lang_worklog_20260716.md。【残】423に実回答8件(29139-29146・通常回答計上)が残存→Lv4クリーンアップ要(テスト専用アンケートのため緊急性低)。構成(本日API確認): is_multilingual_enabled=false・supported_locales=[ja]・capture_card_flag=1・設問「名刺添付だけ」・会期finish_date=2026-08-14。',
      expected_outcome: '（仮説・※要検証）回答画面に言語プルダウンが出ず回答言語はjaに固定される。4表記すべての名刺で「名刺の入力言語」が『日本語』に自動判定され、判定不能はゼロ。全件が日本語対応オペレーターの入力キューに計上され、英語のみ/簡体字のみ/繁体字のみ設定のオペレーターには出ない。ユーザー側回答データCSVに回答言語・名刺入力言語が記録される。多言語ON（425のja回答×英名刺等）と判定値が一致する。※実測で判定不能や外国語判定・外国語オペへの割り振りが出た場合は、多言語OFF運用（本番大多数）に影響する不具合候補として起票する。',
      evidence_policy: '回答画面の言語プルダウン不在、送信ごとの名刺表記言語と一意識別子（メール/URL）の対応表、対応可能言語別オペレーター各アカウントの名刺入力キューの作業可能件数（送信前後）、ユーザー側回答データCSVの「アンケートの回答言語」「名刺の入力言語」列の有無と値（人間確認必須=BUG-003）、DLモーダルの言語フィルタ選択肢を記録する。実データはダミーのみ使用。本番のため証跡に実顧客PIIが映らないことを確認し、DLファイルは確認後削除する。',
      notes: '【位置づけ】424-426（多言語ON）に対する対照＝多言語OFFの基準線。本番の実顧客アンケートの大多数が多言語OFF構成のため、外国語名刺の判定・割り振りの実運用挙動をここで確定する。420Mの「判定不能→納品漏れ」リスクが多言語ON限定か日本語運用にも及ぶかの線引きが目的。【テストケース】回答ja固定×名刺4表記: J-1日本語／J-2英語／J-3簡体字／J-4繁体字を各2〜3件。名刺はメール/URLで一意識別、簡繁は字形が判別できる語を含める（广告/廣告・质量/質量）。【前提】①オペレーターを対応可能言語で分離（最低「日本語のみ」＋「英語のみ」、可能なら簡/繁のみも）。繁体字が言語マスタに別項目で存在するかは未確認（DB管理・画面非提供）。②ダミー名刺4表記（実PIIなし）。③423所有アカウントのユーザー側認証（CSV DL用・420で手順確立済み）。【手段】Playwright実画面操作のみ（DOM直叩き禁止=実機テスト方針）。【本番課金/メール】送信で完了メール実送・データ化/DLで課金が発生し得る。実行後はLv4でテスト回答・名刺を整理（無効化/削除）。【要初日確認】①説明カードのみ＋名刺のアンケートがデータ化キューに乗るか ②多言語OFFのCSVに回答言語/名刺入力言語列があるか ③繁体字のオペレーター言語設定の有無 ④繁体字判定値が独立値か簡体字畳み込みか。【関連】PRD-SCN-420L（一致・多言語ON）／420M（不一致・多言語ON）／420C（簡繁分離・424）、README_prod420_worklog_20260715.md。'
    },
    {
      scenario_id: 'PRD-SCN-420B',
      title: '裏面あり名刺の回答送信からデータ化・照合・納品までの通し（本番）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://speed-ad.com/questionnaire_answer?id=420',
      objective: '名刺の表面と裏面の両方をアップロードして回答送信し、裏面画像が後続工程（名刺画像ZIP・データ化入力作業画面・照合画面・完成データCSVの裏面ファイル名列）まで正しく流れることを検証する。表=日本語・裏=英語の実在型名刺を使い、裏面の情報がデータ化入力にどう扱われるか（入力対象になるか・参照のみか）と、裏面の言語が名刺言語判定に影響するかも観測する。',
      linked_case_ids: ['ANS-028', 'ANS-030', 'STG-ADM-02-03', 'STG-ADM-07', 'STG-FLOW-DATA-01'],
      stg_observation_status: '未実行（新規作成 2026-07-10）。既存の実走（STG-SCN-034/035・PRD-SCN-001・PRD-SCN-420）はすべて「裏面をスキップ」で送信しており、裏面ありの後続工程は完全に未観測。完成データCSV（0022200420ncd.csv）に「名刺画像ファイル名（裏）」列が存在すること、および裏面スキップ時は同列が空欄になることは2026-07-10実走で確認済み。',
      expected_outcome: '表裏2枚の名刺画像が送信され、名刺画像ZIPに裏面画像（連番_2）が含まれ、データ化入力作業画面と照合画面で裏面を表示（または表裏切替）でき、完成データCSVの「名刺画像ファイル名（裏）」列に裏面ファイル名が記録される。裏面情報を根拠にした入力（例: 裏面にのみ記載のURL）が確定まで通る。',
      evidence_policy: '表裏の名刺画像、アップロードモーダルの裏面ステップ表示、ZIP内ファイル一覧（_1/_2）、入力作業画面・照合画面での裏面表示状態、CSVの裏面ファイル名列を記録する。実データはダミーのみ使用。',
      notes: '【名刺の設計】表=日本語表記・裏=英語表記の同一人物ダミー名刺とし、一部項目（例: URL・部署の英語名）を裏面にのみ記載して「裏面を参照しないと入力できない項目」を意図的に作る。【観測ポイント】①アップロードフローの裏面ステップ（「裏面をスキップ」を押さずに裏面を選択）②入力作業画面で裏面画像の表示・切替UIの有無（表しか見えない場合、裏面のみ記載項目は入力不能=気づきとして記録）③裏面の英語表記が名刺言語判定に影響するか（※要観測。420Lの判定モデルと突き合わせる）。【前提】会期中のアンケートで実行する（会期終了後はSubmit無効=2026-07-15実証。420は会期終了済みのため会期再設定または検証用アンケートで実施）。多言語設定済み・オンデマンド。回答言語は日本語固定でよい（裏面の影響を分離するため）。【関連】PRD-SCN-420（通しフローのベース）、PRD-SCN-420L（言語判定）。'
    },
    {
      scenario_id: 'PRD-SCN-420N',
      title: '名刺なし回答（名刺が手元に無い方）の通し検証（本番）',
      role_scope: '横断',
      scenario_group: '名刺データ化納品',
      priority: 'P1',
      side_effect: 'medium',
      start_url: 'https://speed-ad.com/questionnaire_answer?id=420',
      objective: '「名刺が手元に無い方」導線で名刺を添付せずに回答送信した場合に、回答としては計上される一方でデータ化工程（名刺入力キュー・照合・名刺画像ZIP・完成データCSV）の対象外として一貫して扱われることを検証する。多言語アンケートでの言語切替（同ボタンはen: I don\'t have a business card／zh-Hans: 我没有名片 に翻訳される）と、回答言語の記録が名刺なしでも行われるかも確認する。',
      linked_case_ids: ['ANS-030', 'DSH-001', 'STG-ADM-02-01', 'STG-ADM-07'],
      stg_observation_status: '部分観測済(2026-07-10・PRD-SCN-420実走時の副次観測)。420の既存回答1件（名刺なし）について、名刺画像ZIP（11枚=名刺あり分のみ）と完成データCSV（名刺ありレコードのみ）に含まれないことを確認済み。ただし意図した統制条件での送信から通しの確認（送信時の導線・件数計上・キュー非計上・回答データCSVへの記録）は未実施。【2026-07-15追記・要確認】ユーザー側回答データCSVの実DLで、回答数30件に対しCSVは名刺あり29行のみで名刺なし回答が出力されていないことを観測（本シナリオ期待の「回答データCSVに記録される」と食い違い。仕様か不具合か要確認）。420は会期終了で送信不可のため、統制条件での通しは会期中のアンケートで実施する。',
      expected_outcome: '「名刺が手元に無い方」から回答のみ送信でき、admin/surveysの実際の件数は増えるが、名刺入力キュー（data_input_list）の作業可能件数は増えず、照合（matching_list）の総件数にも含まれず、名刺画像ZIP・完成データCSVにも出ない。回答データ（ユーザー側DLの回答データCSV）には回答内容と回答言語が記録される。',
      evidence_policy: '「名刺が手元に無い方」押下時の画面遷移、送信完了表示、送信前後の件数比較（実際の件数／作業可能件数／照合総件数）、ZIP・CSVの件数、ユーザー側回答データCSVの該当行を記録する。実データはダミーのみ使用。',
      notes: '【手順の要点】送信前後で件数4点（admin/surveysの実際の件数・data_input_listの作業可能件数・matching_listの総件数・名刺画像ZIPの枚数）を比較する。回答本文に一意識別子を入れ、ユーザー側回答データCSVで該当行を特定できるようにする。【多言語との交差】言語プルダウンでen/zh-Hansを選んだ状態でも同導線が機能し、回答言語が記録されるか確認する（サンクス画面の言語固定問題=既知の気づきと合わせて観測）。【ユーザー側確認の前提】回答データCSVの確認には420所有の企業ユーザーアカウントが必要（2026-07-10時点で認証情報未入手のため、その工程のみ保留になる可能性を明記）。【関連】PRD-SCN-420（名刺ありの通しフロー）。'
    }
  ];

  const steps = [
    ['STG-SCN-001', 1, 'stgのログイン入口を開き、既存セッションまたはログイン後の遷移先を確認する。', '企業ユーザーとしてダッシュボードへ到達する。', 'none', false, 'LGN-001'],
    ['STG-SCN-001', 2, 'ダッシュボードのアンケート一覧を確認する。', '一覧、ステータス、主要アクションが表示される。', 'none', false, 'DSH-001'],
    ['STG-SCN-001', 3, '代表アンケートの詳細または行アクションを開く。', '詳細導線が表示され、画面が崩れない。', 'none', false, 'DSH-003'],
    ['STG-SCN-001', 4, '主要ナビゲーションを1つ以上開いて戻る。', 'リンク切れや認証切れがない。', 'none', false, 'DSH-004'],
    ['STG-SCN-001', 5, 'コンソールとネットワークを確認する。', '表示を阻害するエラーがない。', 'none', false, ''],

    ['STG-SCN-002', 1, 'ダッシュボードから代表アンケートの詳細を開く。', 'アンケート概要と関連操作が確認できる。', 'none', false, 'DSH-003'],
    ['STG-SCN-002', 2, 'QRまたは回答URLの表示入口を開く。', '回答URL相当の情報が表示される。', 'none', false, 'QR-001,QR-002'],
    ['STG-SCN-002', 3, 'コピー操作を実行する。', 'コピー後トーストまたは完了表示が出る。', 'none', false, 'QR-003'],
    ['STG-SCN-002', 4, 'QR画像未設定時の表示を確認する。', '未設定時はプレースホルダーまたは無効表示になる。', 'none', false, 'QR-004'],

    ['STG-SCN-003', 1, '回答URLまたはプレビューURLを開く。', '回答画面のタイトルと説明が表示される。', 'none', false, 'ANS-004'],
    ['STG-SCN-003', 2, '設問数と必須表示を確認する。', '対象アンケートの設問が表示され、必須表示が確認できる。', 'none', false, 'ANS-005,ANS-006'],
    ['STG-SCN-003', 3, '自由記述、単一選択、複数選択など代表入力を行う。', '入力値または選択状態が保持される。', 'none', false, 'ANS-011,ANS-012,ANS-013'],
    ['STG-SCN-003', 4, 'プレビュー送信または安全な完了確認を行う。', 'プレビュー完了または送信直前状態が確認できる。', 'none', false, 'ANS-023'],

    ['STG-SCN-004', 1, '回答画面を開き、送信に必要な入力を行う。', '送信ボタンが押せる状態になる。', 'none', false, 'ANS-007'],
    ['STG-SCN-004', 2, '送信ボタン押下前に副作用の有無を確認する。', '実回答保存が発生する場合は要許可として止める。', 'medium', true, 'ANS-019'],
    ['STG-SCN-004', 3, '明示許可がある場合のみ本送信を行う。', '送信中表示から完了画面へ進む。', 'medium', true, 'ANS-020,ANS-021'],
    ['STG-SCN-004', 4, '完了表示を確認する。', '完了メッセージと完了アイコンが表示される。', 'none', false, 'ANS-021,ANS-022'],

    ['STG-SCN-005', 1, 'アンケート新規作成または編集入口を開く。', '作成/編集画面へ到達する。', 'medium', true, 'CRT-001,EDT-027'],
    ['STG-SCN-005', 2, '基本情報フィールドを確認する。', 'アンケート名や会期の入力欄が表示される。', 'none', false, 'EDT-001,EDT-022'],
    ['STG-SCN-005', 3, '設問追加メニューを開く。', '設問タイプの選択肢が表示される。', 'none', false, 'EDT-002,EDT-028'],
    ['STG-SCN-005', 4, '保存または公開が必要な操作は直前で止める。', 'stgデータ変更なしで確認を終える。', 'medium', true, 'EDT-001'],

    ['STG-SCN-006', 1, '名刺データ化設定画面を開く。', '設定画面へ到達する。', 'none', false, 'BIZ-001'],
    ['STG-SCN-006', 2, 'プラン、想定件数、料金/見積表示を確認する。', '設定に応じた見積または料金表示が確認できる。', 'none', false, 'BIZ-002'],
    ['STG-SCN-006', 3, '保存系ボタンの表示を確認する。', '保存入口が確認でき、押下は止められる。', 'medium', true, 'BIZ-002'],

    ['STG-SCN-007', 1, 'お礼メール設定画面を開く。', '文面と設定項目が表示される。', 'none', false, 'MAIL-001'],
    ['STG-SCN-007', 2, '送信対象と送信タイミングの表示を確認する。', '対象や期限の状態が確認できる。', 'none', false, 'MAIL-002'],
    ['STG-SCN-007', 3, 'サンクス画面設定または保存/送信系操作は直前で止める。', '実メール送信や保存更新を発生させない。', 'medium', true, 'THX-001,MAIL-001'],

    ['STG-SCN-008', 1, 'ユーザー側の請求一覧を開く。', '請求一覧が表示される。', 'none', false, 'INV-001'],
    ['STG-SCN-008', 2, '代表請求の詳細を開く。', '請求先、明細、合計金額、支払期日が表示される。', 'none', false, 'INV-002'],
    ['STG-SCN-008', 3, '印刷用ビュー入口を確認する。', '印刷用ビューまたは印刷導線が表示される。', 'none', false, 'INV-003'],

    ['STG-SCN-009', 1, '管理者ログイン入口を開く。', '既存セッションでトップへ入る、またはログイン画面が表示される。', 'none', false, 'STG-AX-01'],
    ['STG-SCN-009', 2, '管理者トップの主要リンクを確認する。', '主要管理画面へのリンクが表示される。', 'none', false, 'STG-COMMON-01,STG-ADM-00'],
    ['STG-SCN-009', 3, '主要画面を代表的に巡回する。', '遷移先が表示され、ログインへ戻されない。', 'none', false, 'STG-AX-02'],
    ['STG-SCN-009', 4, '最後に必要であればログアウト導線を確認する。', 'ログアウト後にログイン画面へ戻る。', 'none', false, 'STG-AX-01'],

    ['STG-SCN-010', 1, '利用者管理を開き検索/リセットを確認する。', '検索条件と一覧が表示され、リセットできる。', 'none', false, 'STG-ADM-01'],
    ['STG-SCN-010', 2, 'アンケート管理を開き検索/ステータス絞り込みを確認する。', '検索とステータス条件が操作できる。', 'none', false, 'STG-ADM-02'],
    ['STG-SCN-010', 3, '請求管理を開き検索/ページングを確認する。', '検索条件とページングが操作できる。', 'none', false, 'STG-ADM-03'],
    ['STG-SCN-010', 4, '編集、削除、保存系入口は確定前で止める。', 'stgデータ変更なしで確認を終える。', 'medium', true, 'STG-AX-03'],

    ['STG-SCN-011', 1, 'クーポン管理を開く。', '検索フォームと一覧が表示される。', 'none', false, 'STG-ADM-04'],
    ['STG-SCN-011', 2, 'ID、クーポン名、クーポンコードなどで検索/リセットを確認する。', '検索条件を操作できる。', 'none', false, 'STG-ADM-04'],
    ['STG-SCN-011', 3, '編集または利用履歴入口を確認する。', '入口が表示される。保存は実行しない。', 'medium', true, 'STG-ADM-04'],
    ['STG-SCN-011', 4, 'オペレーター実績確認を開き、期間/所属条件と集計タブを確認する。', '集計表示とCSV出力入口が確認できる。', 'none', false, 'STG-ADM-10'],

    ['STG-SCN-012', 1, '営業日カレンダーを開く。', '定休日、祝日、個別休日、決定ボタンが表示される。', 'none', false, 'STG-ADM-05'],
    ['STG-SCN-012', 2, 'オペレーター管理を開き検索/リセットを確認する。', '検索条件と一覧が表示される。', 'none', false, 'STG-ADM-09'],
    ['STG-SCN-012', 3, '新規作成、編集、削除入口を確認する。', '入口は確認でき、保存/削除確定は実行しない。', 'medium', true, 'STG-AX-04'],

    ['STG-SCN-013', 1, '名刺入力画面を開く。', 'データ入力対象一覧と作業可能件数が表示される。', 'none', false, 'STG-ADM-07'],
    ['STG-SCN-013', 2, '入力作業画面入口を開く。', '入力欄、回転、確定、スキップ、作業終了が表示される、または未到達理由を記録できる。', 'medium', true, 'STG-FLOW-DATA-01'],
    ['STG-SCN-013', 3, '照合画面を開き検索条件と作業入口を確認する。', '照合一覧、KPI、作業開始、エスカレーション導線が表示される。', 'none', false, 'STG-ADM-08'],
    ['STG-SCN-013', 4, '照合作業/エスカレーション確認導線を開く。', '到達先またはリダイレクト先を記録できる。', 'medium', true, 'STG-FLOW-MATCH-01,STG-FLOW-ESCALE-01'],

    ['STG-SCN-014', 1, 'ユーザー側で代表アンケートの一覧/詳細と請求一覧/詳細を確認する。', 'アンケート表示と請求表示が確認できる。', 'none', false, 'DSH-001,INV-001,INV-002'],
    ['STG-SCN-014', 2, '管理者側でアンケート管理を開き、対象を検索する。', 'アンケート管理一覧が表示され、検索できる。', 'none', false, 'STG-ADM-02'],
    ['STG-SCN-014', 3, '管理者側で請求管理と請求書管理を開き検索する。', '請求管理と請求書管理の条件入力、検索、リセットが確認できる。', 'none', false, 'STG-ADM-03,STG-ADM-06'],
    ['STG-SCN-014', 4, 'ユーザー側と管理者側の証跡を並べて確認する。', '表示観点を比較できる。実値の厳密一致は今回の期待に含めない。', 'none', false, ''],

    ['STG-SCN-015', 1, 'サイドバー「アカウント情報」を開き、アカウント/グループ切替パネルを表示する。', 'グループ選択コンボと「グループ新規作成」が表示される。', 'none', false, 'ACC-002'],
    ['STG-SCN-015', 2, 'グループ選択コンボで個人アカウントから別グループへ切り替える。', '選択したグループのコンテキストに切り替わる。', 'none', false, 'GRP-001'],
    ['STG-SCN-015', 3, 'アンケート一覧と請求一覧の表示が切替後の内容になっていることを確認する。', '個人とグループで一覧/請求の内容が変わる。', 'none', false, 'GRP-003,DSH-001,INV-001'],
    ['STG-SCN-015', 4, '個人アカウントへ戻す。', '元のコンテキストに戻る。', 'none', false, 'GRP-001'],

    ['STG-SCN-016', 1, 'アカウント情報パネルを開く。', 'グループ操作UIが表示される。', 'none', false, 'ACC-002'],
    ['STG-SCN-016', 2, '「グループ新規作成」を押下し、作成フォーム/モーダルを表示する。', '作成フォームが表示される。', 'none', false, 'GRP-002'],
    ['STG-SCN-016', 3, '必要項目を入力し、作成確定の直前で止める。', '入力できる。確定はstgデータ変更のため要許可で停止する。', 'medium', true, 'GRP-002'],

    ['STG-SCN-017', 1, '回答が存在するアンケートのSPEEDレビューを開く。', '回答総数とActive Questionが表示される。', 'none', false, 'REV-004,REV-005'],
    ['STG-SCN-017', 2, '時間帯別グラフと集計データ表を確認する。', 'グラフ（自動/固定切替）と集計表（選択肢/件数/割合/合計）が表示される。', 'none', false, 'REV-006,REV-007'],
    ['STG-SCN-017', 3, '個別回答テーブルのソート・ページングを操作する。', '並び替えとページングが動作する。', 'none', false, 'REV-008'],
    ['STG-SCN-017', 4, 'フィルタ（簡易/詳細・表示対象日・ステータス）で絞り込み、リセットする。', '条件で絞り込め、リセットで解除される。', 'none', false, 'REV-009'],

    ['STG-SCN-018', 1, '対象アンケートの名刺データ化設定を開く。', 'プラン一覧と見積サイドバーが表示される。', 'none', false, 'BIZ-001'],
    ['STG-SCN-018', 2, 'データ化項目プランを選択し、見込み枚数を入力する。', '選択と入力に応じて見積が自動更新される。', 'none', false, 'BIZ-003,BIZ-004'],
    ['STG-SCN-018', 3, 'クーポンコードを適用し、見積反映を確認する。', '有効コードで割引が見積に反映される。', 'none', false, 'BIZ-007'],
    ['STG-SCN-018', 4, '「設定を保存して依頼を確定する」の直前で止める。', '必須充足でボタンが活性化する。確定はstgデータ変更のため要許可で停止する。', 'medium', true, 'BIZ-011'],

    ['STG-SCN-019', 1, 'お礼メール設定を開き、送信方式を選択する。', '手動送信/自動送信/送信しないが選択できる。', 'none', false, 'MAIL-003'],
    ['STG-SCN-019', 2, '件名・本文を編集し、差し込み変数を挿入する。', 'カーソル位置に差し込み変数が挿入される。', 'none', false, 'MAIL-006'],
    ['STG-SCN-019', 3, 'リアルタイムプレビューで置換後の文面を確認する。', 'プレビューが編集内容と同期する。', 'none', false, 'MAIL-007'],
    ['STG-SCN-019', 4, '「設定を保存する」の直前で止める。', 'dirtyで活性化する。保存・送信はstgデータ変更/実送信の可能性があるため要許可で停止する。', 'medium', true, 'MAIL-012'],

    ['STG-SCN-020', 1, '送信期限が終了しているアンケートのお礼メール設定を開く。', '「送信期限が終了しています」バナーと各入力のdisabledを確認する。', 'none', false, 'MAIL-011'],
    ['STG-SCN-020', 2, '「対象者リストを見る」などの代替導線を確認する。', '対象者リスト確認の代替導線が表示される。', 'none', false, 'MAIL-008'],

    ['STG-SCN-021', 1, 'ダッシュボードでアンケート行をクリックし詳細モーダルを開く。', '詳細モーダルが開き基本情報/URL/QR/導線が表示される。', 'none', false, 'DTL-001'],
    ['STG-SCN-021', 2, 'モーダルから「名刺データ化設定へ」を開く。', '名刺データ化設定へ遷移する。', 'none', false, 'DTL-007,BIZ-001'],
    ['STG-SCN-021', 3, '戻ってモーダルから「お礼メール設定へ」を開く。', 'お礼メール設定へ遷移する。', 'none', false, 'DTL-007,MAIL-001'],

    ['STG-SCN-022', 1, '回答URLを開き、必須設問に回答する。', '設問が表示され、必須を満たすと送信ボタンが活性化する。', 'none', false, 'ANS-030'],
    ['STG-SCN-022', 2, '「名刺を撮影」フローを起動する。', '名刺撮影/アップロードのステップに進む。', 'none', false, 'ANS-028'],
    ['STG-SCN-022', 3, '「名刺が手元に無い方」分岐を確認する。', '名刺なしルートに分岐できる。', 'none', false, 'ANS-029'],
    ['STG-SCN-022', 4, '送信の直前で止める。', '送信はstgデータ更新（実回答保存）の可能性があるため要許可で停止する。', 'medium', true, 'ANS-030'],

    ['STG-SCN-023', 1, 'アンケート管理を開き、ID/会社名/氏名で検索する。', '条件に一致するアンケートが表示される。', 'none', false, 'STG-ADM-02-01'],
    ['STG-SCN-023', 2, '作業ステータスのチェック（6種）で絞り込む。', '選択したステータスの行のみ表示される。', 'none', false, 'STG-ADM-02-02'],
    ['STG-SCN-023', 3, '名刺画像ダウンロード入口を確認する。', 'ダウンロード導線が表示される。', 'low', false, 'STG-ADM-02-03'],
    ['STG-SCN-023', 4, '完了データCSVアップロードでファイルを選び、確定の直前で止める。', 'ファイル選択でき、確定はstgデータ変更のため要許可で停止する。', 'medium', true, 'STG-ADM-02-04'],

    ['STG-SCN-024', 1, '請求管理を開き、会社名/氏名で検索する。', '条件に一致する請求が表示される。', 'none', false, 'STG-ADM-03-01'],
    ['STG-SCN-024', 2, '直接編集で請求金額等を編集する。', 'インライン編集でき、保存は要許可で停止する。', 'medium', true, 'STG-ADM-03-03'],
    ['STG-SCN-024', 3, 'クーポン割引率・メモ列を確認する。', '割引率とメモが表示される。', 'none', false, 'STG-ADM-03-04'],

    ['STG-SCN-025', 1, 'クーポン管理を開き、ID/名/コード/作成日で検索する。', '条件に一致するクーポンが表示される。', 'none', false, 'STG-ADM-04-01'],
    ['STG-SCN-025', 2, '「クーポン新規作成」を開いて入力し、作成の直前で止める。', '作成フォームに入力でき、確定はstgデータ変更のため要許可で停止する。', 'medium', true, 'STG-ADM-04-02'],
    ['STG-SCN-025', 3, '既存クーポンの利用履歴を開く。', '利用履歴が表示される。', 'none', false, 'STG-ADM-04-04'],

    ['STG-SCN-026', 1, 'オペレーター管理を開き、「新規作成」フォームを表示する。', '所属/権限レベル/メール/名前/対応言語/ステータスの入力フォームが表示される。', 'none', false, 'STG-ADM-09-03'],
    ['STG-SCN-026', 2, '権限レベルを選択する。', 'レベル1〜4が選択できる。', 'none', false, 'STG-ADM-09-04'],
    ['STG-SCN-026', 3, '対応言語を複数選択する。', '複数言語が選択できる。', 'none', false, 'STG-ADM-09-05'],
    ['STG-SCN-026', 4, 'メール・名前・ステータスを入力し、登録の直前で止める。', '必須充足で登録ボタンが活性化する。登録は要許可で停止する。', 'medium', true, 'STG-ADM-09-06'],

    ['STG-SCN-027', 1, 'オペレーター実績確認を開き、集計タブを切り替える。', '所属グループ別/オペレーター別の集計表が切替表示される。', 'none', false, 'STG-ADM-10-01'],
    ['STG-SCN-027', 2, 'オペレーター別で項目別集計の「詳細」を展開する。', '項目名/作業件数/正解件数/正答率/報酬金額/スキップ回数が表示される。', 'none', false, 'STG-ADM-10-03'],
    ['STG-SCN-027', 3, 'CSV出力入口を確認する。', 'CSV出力導線が表示される。', 'low', false, 'STG-ADM-10-05'],

    ['STG-SCN-028', 1, '照合画面を開き、アンケートID/氏名/会社名で検索する。', '条件に一致するアンケートのカードが表示される。', 'none', false, 'STG-ADM-08-01'],
    ['STG-SCN-028', 2, '作業ステータスのチェックで絞り込む。', '選択した状態の対象のみ表示される。', 'none', false, 'STG-ADM-08-02'],
    ['STG-SCN-028', 3, 'KPI（進行中作業対象数・エスカレあり要確認名刺数）を確認する。', '件数が表示される。', 'none', false, 'STG-ADM-08-03'],
    ['STG-SCN-028', 4, '照合作業の開始/エスカレーション内容の確認/完成データ確認/全レコードDLの各導線を確認する。', '各導線が表示される。作業・DLは要許可で停止する。', 'medium', true, 'STG-ADM-08-04'],

    ['STG-SCN-029', 1, 'レベル1（オペレーター）相当アカウントでログインし、管理者トップを開く。', 'トップのメニューが名刺入力のみになっている。', 'none', false, 'STG-ADM-00-01'],
    ['STG-SCN-029', 2, '/admin/user など他の管理画面URLへ直接アクセスする。', '/topへリダイレクトされ、到達できない。', 'none', false, 'STG-ADM-00-03'],
    ['STG-SCN-029', 3, '名刺入力対象一覧を開く。', '名刺入力一覧へ到達できる。', 'none', false, 'STG-ADM-07-01'],

    ['STG-SCN-031', 1, 'レベル3（アブロードスタッフ）アカウントで管理者トップを開く。', 'フル12メニューが表示される。', 'none', false, 'STG-ADM-00-01'],
    ['STG-SCN-031', 2, '主要画面を順に開いて戻る。', '各画面へ到達でき、操作部品が表示され、戻れる。', 'none', false, 'STG-ADM-00-02'],

    ['STG-SCN-030', 1, 'Lv2アカウントで管理者トップを開く。', 'メニューが名刺入力＋実績確認の2項目に限定される。', 'none', false, 'STG-ADM-00-01'],
    ['STG-SCN-030', 2, 'メニュー非表示の利用者管理(/admin/user)へ直URLでアクセスする。', '本来はログインへリダイレクトされ到達できない（現状は到達できる＝BUG-ADM-04）。', 'none', false, 'STG-ADM-01-01'],
    ['STG-SCN-030', 3, '請求管理(/admin/payment)・オペレーター管理(/admin/operator_list)へ直URLでアクセスする。', '本来は遮断される（現状は全件閲覧できる＝不備）。', 'none', false, 'STG-ADM-03-01'],

    ['STG-SCN-032', 1, '管理者で対象テストアンケートを開き、名刺データ化の作業状態（データ化中）と照合一覧（総件数・一致/不一致/未入力）を確認する。', 'データ化が開始済みで、照合対象の件数が表示される。', 'none', false, 'STG-ADM-08-01'],
    ['STG-SCN-032', 2, '名刺入力・照合を進め、全レコードを照合完了状態にする（照合完了処理の実行含む）。', '照合完了し、未入力数0・不一致0など完了相当の状態になる。', 'medium', true, 'STG-ADM-08-04,STG-FLOW-MATCH-01'],
    ['STG-SCN-032', 3, '照合一覧で「完成データ確認」を実行し、生成CSVが実際に取得できるか確認する。', 'CSV生成処理が200を返し、DL先URL（/storage/csv/<file>.csv 等）が404にならずCSVが取得できる。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-032', 4, '照合一覧で「全レコードDL」を実行し、全レコードCSVが取得できるか確認する。', '全レコードCSVが200で取得でき、回答内容・設問見出し・名刺入力項目が欠落なく含まれる。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-032', 5, '完了データ確定（CSVアップロード等）でデータ化完了（DATA_READY）へ遷移させる。', 'データ化完了状態になり、完了通知が発火する（要許可）。', 'medium', true, 'STG-ADM-02-04'],
    ['STG-SCN-032', 6, 'ユーザー側ダッシュボードで対象アンケートのステータスとダウンロード導線を確認する。', '「会期終了（データ化完了）」表示になり、完成データCSV／名刺画像ZIPのダウンロード導線が表示される。', 'none', false, 'DSH-001'],
    ['STG-SCN-032', 7, 'ユーザー側でデータダウンロードを実行する。', '完成データCSV／ZIPが200で取得でき、ファイルが開ける。', 'low', false, ''],

    ['STG-SCN-033', 1, 'スピードプランがオンデマンドの対象アンケートを特定し、名刺データ化が開始済みであることを確認する。', '対象アンケートのプランがオンデマンドで、データ化中（一部のみ完了）の状態が確認できる。', 'none', false, 'BIZ-001'],
    ['STG-SCN-033', 2, '全レコードのうち一部のみを照合完了させ、未完了レコードが残る状態を作る。', '一部レコードが照合完了、残りが未完了の途中状態になる。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-033', 3, '管理者側「完成データ確認」「全レコードDL」で、確定済み分のデータが取得できるか確認する。', '全件未完了でも、確定済みレコード分のCSVが200で取得できる。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-033', 4, 'ユーザー側ダッシュボードで、全件完了前でもダウンロード導線が活性化し、確定済み分が取得できるか確認する。', 'オンデマンドでは途中段階でもDL導線が活性化し、確定済み分が取得できる（通常プランとの差を記録）。', 'low', false, 'DSH-001'],
    ['STG-SCN-033', 5, '残りレコードを追加で照合完了させ、再度ダウンロードして取得件数の変化を確認する。', '再ダウンロードで件数が増え、順次納品されていることが確認できる。', 'medium', true, 'STG-ADM-08-04'],

    ['STG-SCN-034', 1, '【回答者】324の公開回答URL（https://stg.speed-ad.com/questionnaire_answer?id=324）を開く。', '「STGシナリオテスト 長期展示会」の回答画面とSTGテスト用・ダミーデータ扱いの注記が表示される。', 'none', false, 'ANS-030'],
    ['STG-SCN-034', 2, '【回答者】Q.01〜Q.09の必須設問に回答する（単一/複数選択・自由記述・5段階・数値・プルダウン・日時・マトリクス・手書きメモ）。', '各設問の入力・選択・手書き描画が保持され、必須が埋まる。', 'none', false, 'ANS-011,ANS-013'],
    ['STG-SCN-034', 3, '【回答者】フッター「名刺を撮影」→「ストレージから選択」で名刺テスト画像（fixtures/meishi_test.png）をアップロードする。', '3ステップウィザードの表面プレビューが表示される。', 'none', false, 'ANS-028'],
    ['STG-SCN-034', 4, '【回答者】「裏面をスキップ」→最終確認で「アップロード完了」を押す。', '名刺画像（表）が添付状態になる（名刺なしは「名刺が手元に無い方」分岐を別途確認）。', 'none', false, 'ANS-028,ANS-029'],
    ['STG-SCN-034', 5, '【回答者】「送信する」を押す。', '/survey-thanks（回答完了）へ遷移し、回答＋名刺画像が保存される（stgデータ更新のため要許可）。', 'medium', true, 'ANS-030'],
    ['STG-SCN-034', 6, '【Lv3/Lv4】アンケート管理（admin/surveys）を開き、アンケートID 324 で検索する。', '324行の「実際の件数」が送信分だけ増え、名刺画像ダウンロード／完了データアップロード入口が表示される。', 'none', false, 'STG-ADM-02-01'],
    ['STG-SCN-034', 7, '【Lv3/Lv4】324行の「ダウンロード」（名刺画像）を実行する。', '名刺画像ZIP（_ncpics.zip）が200で実取得でき（ファイルが保存される）、送信した名刺画像（jpg）が含まれる。', 'low', false, 'STG-ADM-02-03'],
    ['STG-SCN-034', 8, '【Lv1】名刺入力画面（admin/data_input_list）を開き、グループ1〜8すべてに324分が計上されること、および各グループの入力作業画面で名刺画像（表）が表示されることを確認する。', '名刺送信時点でグループ1に計上され、グループ2〜8はメール確定後に開く。【正常系チェック】各作業画面で名刺画像が表示されること。', 'none', false, 'STG-ADM-07,STG-FLOW-DATA-01'],
    ['STG-SCN-034', 9, '【Lv1/Lv2/Lv3】グループ1（メールアドレス）の入力作業画面（admin/data_input_screen?id=1）で、画面の名刺を読んでメールアドレスを入力し「確定（Ctrl+Enter）」する。これを Lv1・Lv2・Lv3 の最大3アカウントで、グループ1の作業可能件数が0になるまで（入力できるものがなくなるまで）繰り返す。', '各レコードはOCRを含め2人以上の入力が合致すると確定し（最大3入力・合致ロジックはシステム内蔵）、グループ2以降へ割り振られる。グループ1の作業可能件数が0になる（要許可）。', 'medium', true, 'STG-FLOW-DATA-01'],
    ['STG-SCN-034', 10, '【Lv1/Lv2/Lv3】グループ2〜8（氏名／会社・部署・役職／郵便番号・住所／電話・携帯・FAX／URL／メモ／フリー入力）を、画面の名刺を読んで入力し「確定」する。各グループを Lv1・Lv2・Lv3 の3アカウントで、作業可能件数が0になるまで繰り返す。', '各項目もOCR含め2人以上の合致で確定し、全グループ（1〜8）の作業可能件数が0になる。全項目入力済みのレコードが照合対象（matching_list）に出現する（要許可）。', 'medium', true, 'STG-FLOW-DATA-01'],
    ['STG-SCN-034', 11, '【Lv3】照合画面（admin/matching_list）でアンケートID 324 を検索する。', '324カードが表示され、納品期日・総件数・一致/不一致/未入力数と「照合作業の開始／完成データ確認／全レコードDL」導線が出る。', 'none', false, 'STG-ADM-08-01'],
    ['STG-SCN-034', 12, '【Lv3】「照合作業の開始」（matching_screen?id=324）で各項目の「確定」をチェックし「保存」→確認モーダルで「OK」する。', '手動照合が確定し次レコードへ前進する。全項目確定で一致数が増える（要許可）。', 'medium', true, 'STG-FLOW-MATCH-01'],
    ['STG-SCN-034', 13, '【Lv3】照合一覧で「全レコードDL」「完成データ確認」を実行する。', '【正常系チェック】完成CSVが実際にDLできること。※2026-06-03時点はPOST /csv_export2が200を返すが実ファイルが配信されずDLされない不具合あり（SPDAD2026-146系）。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-034', 14, '【Lv3/Lv4】アンケート管理の「アップロード」（完了データ）で完了データを登録し、ステータスをアップ完了へ進める。', 'アップ完了になり、完了通知（SM-007）が発火する（要許可）。', 'medium', true, 'STG-ADM-02-04'],
    ['STG-SCN-034', 15, '【企業ユーザー】（324所有アカウント）でアンケート行クリック→詳細モーダル→「データダウンロード」を開く。', '「回答データ／名刺入力＋回答データ／名刺入力データ／名刺画像」の4種と各利用可否、期間（全て／期間指定）が表示される。', 'none', false, 'DSH-001'],
    ['STG-SCN-034', 16, '【企業ユーザー】データ化完了後、「名刺入力データ」「名刺画像」が"利用可能"であることを確認し、期間「全て」でダウンロードする。', '名刺入力データ・名刺画像が実取得できる（通常プランはユーザー側DLが会期終了後＝後日に利用可能化する想定）。', 'low', false, 'DSH-001'],

    ['STG-SCN-035', 1, '【回答者】325の公開回答URL（https://stg.speed-ad.com/questionnaire_answer?id=325）を開く。', '「STG照合反映テスト 1日展示会」の回答画面が表示される（既存回答あり）。', 'none', false, 'ANS-030'],
    ['STG-SCN-035', 2, '【回答者】Q.01〜Q.05の必須設問に回答する（単一/複数選択・自由記述・5段階・数値）。', '各入力が保持され、必須が埋まる。', 'none', false, 'ANS-011,ANS-013'],
    ['STG-SCN-035', 3, '【回答者】「名刺を撮影」→「ストレージから選択」で名刺テスト画像（fixtures/meishi_test.png）をアップロード→「裏面をスキップ」→「アップロード完了」。', '名刺画像（表）が添付される。', 'none', false, 'ANS-028'],
    ['STG-SCN-035', 4, '【回答者】「送信する」を押す。', '/survey-thanks へ遷移し、回答＋名刺が保存され回答件数が増える（要許可）。', 'medium', true, 'ANS-030'],
    ['STG-SCN-035', 5, '【Lv3/Lv4】アンケート管理（admin/surveys）を開き 325 を検索し、データ化完了予定日が当日（オンデマンド）であることを確認する。', '325行の完了予定日＝会期当日相当で、名刺画像ダウンロード／完了データアップロード入口が表示される。', 'none', false, 'STG-ADM-02-01'],
    ['STG-SCN-035', 6, '【Lv3/Lv4】325行の「ダウンロード」（名刺画像）を実行する。', '名刺画像ZIP（_ncpics.zip）が200で実取得できる。', 'low', false, 'STG-ADM-02-03'],
    ['STG-SCN-035', 7, '【Lv1】名刺入力画面（data_input_list）でグループ1〜8すべてに325分が計上されること、および各グループの入力作業画面で名刺画像が表示されることを確認する。', 'グループ1に計上され、グループ2〜8はメール確定後に開く。【正常系チェック】各作業画面で名刺画像が表示されること。', 'none', false, 'STG-ADM-07,STG-FLOW-DATA-01'],
    ['STG-SCN-035', 8, '【Lv1/Lv2/Lv3】グループ1（メールアドレス）→グループ2〜8の順に、画面の名刺を読んで入力し「確定」する。各グループを Lv1・Lv2・Lv3 の最大3アカウントで、作業可能件数が0になるまで（複数件あるときは入力できるものがなくなるまで）繰り返す。', '各レコードはOCRを含め2人以上の入力が合致すると確定し（最大3入力）、グループ1確定でグループ2以降へ割り振られる。全グループ（1〜8）の作業可能件数が0になり、325が照合対象（matching_list）に出現する（オンデマンドは会期終了を待たず当日対象化）（要許可）。', 'medium', true, 'STG-FLOW-DATA-01'],
    ['STG-SCN-035', 9, '【Lv3】照合画面（matching_list）で 325 を検索し「照合作業の開始」で一部レコードを「確定」→「保存」→「OK」する。', '手動照合が確定し、一部のみ完了の途中状態になる（要許可）。', 'medium', true, 'STG-FLOW-MATCH-01'],
    ['STG-SCN-035', 10, '【Lv3】途中段階で照合一覧の「全レコードDL」「完成データ確認」を実行する。', '【正常系チェック】オンデマンドは入力・照合が進んだ「そこまでの分」のCSVが取得できること。※現状はPOST /csv_export2が200だが実ファイルが配信されずDLされない不具合あり（SPDAD2026-146系）。', 'medium', true, 'STG-ADM-08-04'],
    ['STG-SCN-035', 11, '【企業ユーザー】（325所有アカウント）で詳細モーダル→「データダウンロード」を開く。', '4種のダウンロードオプション（回答データ／名刺入力＋回答データ／名刺入力データ／名刺画像）と利用可否が表示される。', 'none', false, 'DSH-001'],
    ['STG-SCN-035', 12, '【企業ユーザー】オンデマンドにより全件完了前でも「名刺入力データ」「名刺画像」が"利用可能"であることを確認し、確定済み分をダウンロードする。', '会期終了／全件完了を待たず確定済み分が利用可能化し取得できる（通常プラン324との差を記録）。', 'low', false, 'DSH-001'],
    ['STG-SCN-035', 13, '【Lv3→企業ユーザー】残りレコードを照合確定し、管理者側・ユーザー側で再度ダウンロードして取得件数の増加を確認する。', '再DLで件数が増え、順次納品されることが確認できる（要許可）。', 'medium', true, 'STG-ADM-08-04'],

    ['STG-SCN-036', 1, '【未ログイン】ログイン画面（/login）を開く。', 'ログイン画面が表示され、「新規アカウント作成」「Googleでログイン」が表示される。', 'none', false, 'LGN-001'],
    ['STG-SCN-036', 2, '【未ログイン】「新規アカウント作成」を押す。', 'サインアップモーダル（お名前・メールアドレス・パスワード・パスワード確認・利用規約同意）が表示される。', 'none', false, 'LGN-001'],
    ['STG-SCN-036', 3, '【未ログイン】お名前（任意）・メールアドレス（任意の未登録メール可）・パスワード・パスワード確認を入力する。', '各入力が保持される。', 'none', false, 'LGN-001'],
    ['STG-SCN-036', 4, '【未ログイン】「利用規約とプライバシーポリシーに同意する」にチェックする。', '「アカウント作成」ボタンが活性化する。', 'none', false, 'LGN-001'],
    ['STG-SCN-036', 5, '【未ログイン】「アカウント作成」を押す。', 'アカウントが作成される（現段階はメール認証なし）。stgデータ追加のため要許可。', 'medium', true, 'LGN-001'],
    ['STG-SCN-036', 6, '【未ログイン】作成後に自動ログインされない場合は、ログイン画面で作成したメールアドレス・パスワードを入力して「ログイン」する。', '作成したアカウントで認証が通る。', 'none', false, 'LGN-001'],
    ['STG-SCN-036', 7, '【ユーザー】ログイン結果を確認する。', '/dashboard に到達し、作成したアカウントでログインできていることを確認できる。', 'none', false, 'DSH-001'],

    ['STG-SCN-037', 1, 'ダッシュボードでアカウント切替（user_select）が「個人アカウント」になっていることを確認する。', '個人コンテキストでアンケート一覧が表示される。', 'none', false, 'DSH-001'],
    ['STG-SCN-037', 2, '「アンケート新規作成」モーダル（#newSurveyModal）を開き、アンケート名・表示タイトル・期間を入力して「作成する」を押す。', '/survey/{id} の編集画面へ遷移し、新規IDが採番される。', 'medium', true, 'CRT-001'],
    ['STG-SCN-037', 3, '個人01：自由記述を2問追加する（単一行＝必須ON／複数行＋最大文字数指定＝必須OFF）。', '設問タイプとテキストタイプ・文字数が設定でき、必須ON/OFFが反映される。', 'none', false, 'EDT-002'],
    ['STG-SCN-037', 4, '「アンケート保存」を押し、個人アンケート一覧への反映を確認する。', '保存が完了し、個人一覧に新規行（STGテスト_個人01）が表示される。', 'medium', true, 'EDT-001'],
    ['STG-SCN-037', 5, '個人02：選択肢系3問を作成して保存する（単一選択・選択肢3＝必須ON／複数選択・選択肢4＋最大選択数＝必須OFF／ドロップダウン・選択肢3＝必須ON）。', '各選択肢系の選択肢が編集でき、保存される。', 'medium', true, 'EDT-002'],
    ['STG-SCN-037', 6, '個人03：評定尺度3問を作成して保存する（3段階＝必須ON／5段階＝必須OFF／7段階＝必須ON）。', '段階数（3/5/7）と左右ラベルが設定でき、保存される。', 'medium', true, 'EDT-002'],
    ['STG-SCN-037', 7, '個人04：数値2問を作成して保存する（単位なし＝必須OFF／min・max・step・単位あり＝必須ON）。', '数値オプション（最小/最大/ステップ/単位）が設定でき、保存される。', 'medium', true, 'EDT-002'],
    ['STG-SCN-037', 8, '個人05：日付/時刻3問を作成して保存する（日付のみ＝必須ON／時刻のみ＝必須OFF／日付+時刻＝必須ON）。', '「日付を表示」「時間を表示」の組合せが設定でき、保存される。', 'medium', true, 'EDT-002'],
    ['STG-SCN-037', 9, '個人アンケート一覧で、作成した5件（個人01〜05）が表示されることを確認する。', '個人コンテキストに5件が反映される。', 'none', false, 'DSH-001'],

    ['STG-SCN-038', 1, 'ダッシュボードのアカウント切替（user_select）で「【Abroad】テストグループ_梅田」に切り替える。', 'グループコンテキストに切り替わり、一覧が当該グループ表示になる。', 'none', false, 'GRP-001'],
    ['STG-SCN-038', 2, '「アンケート新規作成」モーダル（#newSurveyModal）でアンケート名・表示タイトル・期間を入力して「作成する」を押す。', '/survey/{id} の編集画面へ遷移し、新規IDが採番される。', 'medium', true, 'CRT-001'],
    ['STG-SCN-038', 3, 'グループ01 マトリクス網羅：マトリクス（単一）行2×列3＝必須ON／マトリクス（複数）行3×列2＝必須OFF を作成して保存する。', '行・列ラベルが編集でき、保存される。', 'medium', true, 'EDT-002'],
    ['STG-SCN-038', 4, 'グループ02 説明カード＋混在：説明カード（非回答）／単一選択＝必須OFF を作成して保存する。', '説明文と選択肢が設定でき、保存される。', 'medium', true, 'EDT-002'],
    ['STG-SCN-038', 5, 'グループ03 必須全ON回帰：代表4タイプを必須ONで作成して保存する。', '全設問が必須ONで保存される。', 'medium', true, 'EDT-002'],
    ['STG-SCN-038', 6, 'グループ04 必須全OFF回帰：代表4タイプを必須OFFで作成して保存する。', '全設問が必須OFFで保存される。', 'medium', true, 'EDT-002'],
    ['STG-SCN-038', 7, 'グループ05 手書きサイズ網羅【Premium保留】：手書きスペース型がPremium無効で追加できないことを確認する（サイズ標準/小/中/大/カスタムはPremium時のみ網羅）。', '非プレミアムでは手書き型がdisabledで追加できないことを記録する。Premium時は5サイズを網羅する。', 'none', false, 'EDT-002'],
    ['STG-SCN-038', 8, 'グループ01〜04を保存し、グループ一覧への反映を確認する。', 'グループコンテキストに作成分（05はPremium保留）が反映される。', 'medium', true, 'DSH-001'],
    ['STG-SCN-038', 9, 'アカウント切替を「個人アカウント」へ戻し、グループ作成分が個人一覧に混在しないことを確認する。', '個人/グループのコンテキスト分離が保たれる。', 'none', false, 'GRP-003'],

    ['PRD-SCN-001', 1, '【回答者】359の公開回答URL（https://speed-ad.com/questionnaire_answer?id=359）を開く。', '「本番テストアンケート」の回答画面が表示され、Q.01〜Q.10と末尾の説明カードが描画される。', 'none', false, 'ANS-030'],
    ['PRD-SCN-001', 2, '【回答者】Q.01〜Q.10の各設問に回答する（Q.01自由記述／Q.02単一選択／Q.03複数選択／Q.04 5段階／Q.05数値／Q.06ドロップダウン／Q.07マトリクス単一／Q.08マトリクス複数／Q.09日付・時刻／Q.10手書き）。必須/任意は画面で確認し、必須は必ず埋める。', '各設問の入力・選択・手書き描画が保持され、送信できる状態になる。マトリクスは行ごとに選択でき、ドロップダウンは選択値が表示され、日付・時刻が入力値どおり反映される。', 'none', false, 'ANS-011,ANS-013'],
    ['PRD-SCN-001', 3, '【回答者】「名刺を撮影」→「ストレージから選択」でテスト名刺画像（fixtures/meishi_test.png）をアップロード→「裏面をスキップ」→「アップロード完了」。', '名刺画像（表）が添付される。', 'none', false, 'ANS-028'],
    ['PRD-SCN-001', 4, '【回答者】「送信する」を押す。', '/survey-thanks へ遷移し、回答＋名刺が保存され回答件数が増える（本番のため完了メール等が実際に送信される）。', 'medium', false, 'ANS-030'],
    ['PRD-SCN-001', 5, '【Lv3/Lv4】アンケート管理（admin/surveys）を開き 359 を検索し、プラン種別とデータ化完了予定日を確認する。', '359行が表示され、プラン/完了予定日と名刺画像ダウンロード／完了データアップロード入口が確認できる。', 'none', false, 'STG-ADM-02-01'],
    ['PRD-SCN-001', 6, '【Lv3/Lv4】359行の「ダウンロード」（名刺画像）を実行する。', '名刺画像ZIP（_ncpics.zip）が200で実取得でき、送信した名刺画像が含まれる（ERR_BLOCKED_BY_ORB等が出ない）。', 'low', false, 'STG-ADM-02-03'],
    ['PRD-SCN-001', 7, '【Lv1】名刺入力画面（admin/data_input_list）でグループ1〜8に359分が計上されること、および各グループの入力作業画面で名刺画像が表示されることを確認する。', 'グループ1に計上され、グループ2〜8はメール確定後に開く。各作業画面で名刺画像が表示される。', 'none', false, 'STG-ADM-07,STG-FLOW-DATA-01'],
    ['PRD-SCN-001', 8, '【Lv1/Lv2/Lv3】グループ1（メール）→グループ2〜8の順に、画面の名刺を読んで入力し「確定」する。各項目を Lv1・Lv2・Lv3 の最大3アカウントで、作業可能件数が0になるまで繰り返す。', '1人入力だけでは確定せず、OCRを含め2人以上の入力が合致したレコードのみ確定する（最大3入力）。確定すると作業可能件数が減り、グループ1確定でグループ2以降へ割り振られ、全項目確定で照合対象（matching_list）に出現する。同一案件が複数アカウント/タブで重複取得されない。', 'medium', false, 'STG-FLOW-DATA-01'],
    ['PRD-SCN-001', 9, '【Lv3/Lv4】照合画面（admin/matching_list）で 359 を検索し、Lv3・Lv4の双方で照合作業画面に到達できることを確認する。', '359カードが表示され、納品期日・総件数・一致/不一致/未入力数と「照合作業の開始／完成データ確認／全レコードDL」導線が出る。Lv3とLv4で可否・表示差が無い。', 'none', false, 'STG-ADM-08-01'],
    ['PRD-SCN-001', 10, '【Lv3】「照合作業の開始」（matching_screen）で各項目の「確定」をチェックし「保存」→確認モーダルで「OK」する（入力者と別アカウントで照合）。一部レコードを確定する。', '手動照合が確定し、一部のみ完了の途中状態になる。', 'medium', false, 'STG-FLOW-MATCH-01'],
    ['PRD-SCN-001', 11, '【Lv3】途中段階で照合一覧の「全レコードDL」「完成データ確認」を実行する。', 'オンデマンド観点では入力・照合が進んだ「そこまでの分」のCSVが200で実取得できる（空ファイルでない）。csv_export2が200でも実DLされない場合は本番不具合として起票する。', 'medium', false, 'STG-ADM-08-04'],
    ['PRD-SCN-001', 12, '【企業ユーザー】（359所有アカウント）で詳細モーダル→「データダウンロード」を開く。', '4種のダウンロードオプション（回答データ／名刺入力＋回答データ／名刺入力データ／名刺画像）と利用可否が表示される。', 'none', false, 'DSH-001'],
    ['PRD-SCN-001', 13, '【企業ユーザー】利用可能な「名刺入力データ」「名刺画像」を確定済み分ダウンロードする。', '確定済み分が実取得できる（本番のためDLに伴う課金が発生し得る）。', 'low', false, 'DSH-001'],
    ['PRD-SCN-001', 14, '【Lv3→企業ユーザー】残りレコードを照合確定し、管理者側・ユーザー側で再度ダウンロードして取得件数の増加を確認する。', '再DLでステップ13より件数が増え、順次納品されることが確認できる。', 'medium', false, 'STG-ADM-08-04'],

    ['PRD-SCN-420', 1, '【回答者】420の公開回答URL（https://speed-ad.com/questionnaire_answer?id=420）を開き、回答画面上部の言語プルダウンを確認する。', '回答画面が表示され、上部の言語プルダウンに420へ設定された言語（ja/en/zh-CN/zh-TWのうち設定分）が列挙される。設定言語の一覧を証跡に記録する。', 'none', false, 'ANS-030'],
    ['PRD-SCN-420', 2, '【回答者】言語プルダウンから無作為に1言語を選択する（実行ごとにランダム。選択した言語を証跡に記録する）。', '設問文・選択肢・ボタン等のUI文言が選択した言語に切り替わる。未翻訳の箇所がある場合は第一言語で表示される（フォールバック）。', 'none', false, ''],
    ['PRD-SCN-420', 3, '【回答者】選択した言語の表示のまま、各設問に回答する（設問構成・必須/任意は実行時に画面で確認し、必須は必ず埋める）。', '選択言語の表示のまま入力・選択が保持され、送信できる状態になる。', 'none', false, 'ANS-011,ANS-013'],
    ['PRD-SCN-420', 4, '【回答者】「名刺を撮影」→「ストレージから選択」でテスト名刺画像をアップロード→「裏面をスキップ」→「アップロード完了」。名刺は実顧客PIIなしのダミー名刺を最低3種用意し、1回答1枚で確定パターンA/B/C用に割り当てる（414実走のカード生成方式を流用可）。', '名刺画像（表）が添付される。', 'none', false, 'ANS-028'],
    ['PRD-SCN-420', 5, '【回答者】「送信する」を押す。言語プルダウンから言語を引き直してステップ2〜5を繰り返し、最低3回答・最低2言語をカバーする。', '/survey-thanks へ遷移し（完了表示も選択言語で表示される）、回答＋名刺が保存され回答件数が増える（本番のため完了メール等が実際に送信される）。', 'medium', false, 'ANS-030'],
    ['PRD-SCN-420', 6, '【Lv4】アンケート管理（admin/surveys）を開き 420 を検索し、プラン種別・データ化完了予定日・多言語設定を確認する。', '420行が表示され、プラン/完了予定日と名刺画像ダウンロード／完了データアップロード入口が確認できる。', 'none', false, 'STG-ADM-02-01'],
    ['PRD-SCN-420', 7, '【Lv3/Lv4】420行の「ダウンロード」（名刺画像）を実行する。', '名刺画像ZIP（_ncpics.zip）が200で実取得でき、送信した名刺画像が含まれる。', 'low', false, 'STG-ADM-02-03'],
    ['PRD-SCN-420', 8, '【Lv1】名刺入力画面（admin/data_input_list）でグループ1〜8に420分が計上されること、および各グループの入力作業画面で名刺画像が表示されることを確認する。', 'グループ1に計上され、グループ2〜8はメール確定後に開く。各作業画面で名刺画像が表示される。', 'none', false, 'STG-ADM-07,STG-FLOW-DATA-01'],
    ['PRD-SCN-420', 9, '【Lv1】確定パターンA（2入力目で確定）：OCRが正読しやすいASCII項目（グループ1メール・グループ6 URL）に名刺どおりの値を入力して「確定」する。', 'OCR＋人間1人目の2入力一致で項目が即確定し、入力欄がdisabled（グレーアウト）になる。人間1人の入力だけで確定するのはOCRが1入力としてカウントされるため。', 'medium', false, 'STG-FLOW-DATA-01'],
    ['PRD-SCN-420', 10, '【Lv1→Lv2】確定パターンB（3入力目で確定）：OCRが誤読しやすい項目（氏名・電話・FAX）でLv1が名刺どおりの値を入力後、項目が未確定のままであることを確認してから、Lv2が同一値を入力して「確定」する。', 'Lv1の1人入力ではOCRと不一致のため確定せず、Lv2の一致入力（3入力目）で確定する。OCRが偶然正読していた項目はパターンAと同じ挙動になるため、誤読している項目を選んで観測する。', 'medium', false, 'STG-FLOW-DATA-01'],
    ['PRD-SCN-420', 11, '【Lv1/Lv2/Lv3】確定パターンC（不一致）：1レコードの後段グループ項目（例: グループ5電話番号）で、意図的に3入力とも異なるダミー値を入力して確定させない。残りのレコード・項目はグループ1→8の順に名刺どおり入力し、作業可能件数が0になるまで繰り返す（確定済み=disabledの項目には触れない。無関係カードはスキップしない＝グローバルキューのため他アンケートに作用しうる）。', 'パターンC項目は3入力しても確定しない。残りは全項目確定し、同一案件が複数アカウント/タブで重複取得されない（排他）。不一致項目を持つレコードのmatching_listへの出現条件・前進挙動は実行時に観測して記録する（※実行時観測）。', 'medium', false, 'STG-FLOW-DATA-01'],
    ['PRD-SCN-420', 12, '【Lv3/Lv4】照合画面（admin/matching_list）で 420 を検索し、Lv3・Lv4の双方でカード表示と件数を確認する。', '420カードが表示され、納品期日・総件数・一致/不一致/未入力数と「照合作業の開始／完成データ確認／全レコードDL」導線が出る。パターンCのレコードが「不一致」としてカウントされる。Lv3とLv4で可否・表示差が無い。', 'none', false, 'STG-ADM-08-01'],
    ['PRD-SCN-420', 13, '【Lv3】「照合作業の開始」（matching_screen）で全レコードを照合する：一致レコードは各項目の「確定」をチェック、不一致レコード（パターンC）は名刺どおりの正値を手動確定し、「保存」→確認モーダルで「OK」する（入力者と別アカウントで照合）。', '手動照合が全レコード確定し、照合一覧が「一致+不一致=総件数・未入力0」の完了状態になる（414実走で未実施だった最終照合までを完遂する）。', 'medium', false, 'STG-FLOW-MATCH-01'],
    ['PRD-SCN-420', 14, '【Lv3/Lv4】照合一覧の「全レコードDL」「完成データ確認」を実行し、CSVの内容を確認する。', '完成データCSVが200で実取得でき（空ファイルでない）、回答時に選択した言語が回答言語として各レコードに記録されている（複数言語で回答した場合は言語ごとに正しく記録される。回答言語の列が存在しない場合はwiki:27_データ出力・CSV方針との不整合として記録・起票する）。パターンCの手動確定値が正値で反映されている。csv_export2が200でも実DLされない場合は本番不具合として起票する。', 'medium', false, 'STG-ADM-08-04'],
    ['PRD-SCN-420', 15, '【企業ユーザー】（420所有アカウント）で詳細モーダル→「データダウンロード」を開き、利用可能な「名刺入力データ」「名刺画像」をダウンロードする。', '4種のダウンロードオプション（回答データ／名刺入力＋回答データ／名刺入力データ／名刺画像）と利用可否が表示され、確定済み分が実取得できる（本番のためDLに伴う課金が発生し得る）。', 'low', false, 'DSH-001'],
    ['PRD-SCN-420', 16, '【Lv4】実行後クリーンアップとして、テスト回答・名刺データを整理（無効化/削除）する。', 'テストデータが整理され、本番の実運用データに影響が残らない。', 'medium', false, ''],

    ['PRD-SCN-420L', 1, '【準備】会期中の多言語アンケート（ja/en/zh-Hans設定）を用意する：420の会期再設定 または 検証用アンケート新設（いずれも要許可・420M/420Cと共用可）。', '送信可能な多言語アンケートが用意される（会期終了後はSubmitが無効化され送信不可=2026-07-15実証）。', 'medium', true, ''],
    ['PRD-SCN-420L', 2, '【準備】オペレーター4アカウントの対応可能言語設定を確認し、設定内容と適用時刻を記録する（例: 2アカウント=日本語のみ、1アカウント=英語のみ、1アカウント=簡体字のみ。検証中は変更しない）。', '各アカウントの対応可能言語が記録される。「英語のみ」を用意すると英語判定の帰属（英語独立か日本語系同梱か）を切り分けられる。', 'none', false, ''],
    ['PRD-SCN-420L', 3, '【準備】表記言語別のダミー名刺（日本語/英語/简体字・実顧客PIIなし）を用意し、対応表（回答言語×名刺言語×メール/URL識別子）を作成する。', '一致3マスの各レコードを後から一意に特定できる。', 'none', false, ''],
    ['PRD-SCN-420L', 4, '【回答者】一致3マスを送信する：ja選択＋日本語本文＋日本語名刺／en選択＋英語本文＋英語名刺／zh-Hans選択＋中国語本文＋简体字名刺（回答本文は必ず選択言語で書く）。', '3件とも送信が200で完了する。回答本文と選択言語の一致が証跡に残る。', 'medium', false, 'ANS-030,ANS-028'],
    ['PRD-SCN-420L', 5, '【企業ユーザー】入力作業を始める前に回答データCSVをDL（言語フィルタ=すべての言語）し、「名刺の入力言語」を人間確認する。', '入力作業をしていない時点で ja×ja=日本語／en×en=英語／zh×zh=中国語（簡体字）が自動付与されている（判定は送信時自動=2026-07-15確認の再現）。', 'low', false, 'DSH-001'],
    ['PRD-SCN-420L', 6, '【全アカウント】各アカウントの名刺入力画面（admin/data_input_list）の作業可能件数を確認し、一致3マスの割り振り先を記録する。', '本丸の判定: en×enが英語対応アカウントに、zh×zhが简体字対応アカウントに計上され、日本語のみのアカウントには出ない。ja×jaは日本語対応アカウントに計上される。', 'none', false, 'STG-ADM-07'],
    ['PRD-SCN-420L', 7, '【割振先アカウント】グループ1（メール）を消化し、グループ2以降の各消化段階で再度全アカウントの見え方を確認する。', 'グループ前進後も割り振り先が判定結果と整合し、途中で振り直しが起きない（または起きる場合の条件が記録される）。', 'medium', false, 'STG-FLOW-DATA-01'],
    ['PRD-SCN-420L', 8, '結果を「仕様どおり（正本Wiki 25/63への割り振りルール追記提案）」または「不具合（起票）」に暫定分類する。', '一致3マスの判定・割り振り結果が整理され、420Mの不一致6マスと合わせるマトリクスの土台が揃う。', 'none', false, ''],

    ['PRD-SCN-420M', 1, '【準備】PRD-SCN-420Lと同じ環境（会期中アンケート・オペレーター言語設定・ダミー名刺・対応表）を引き継ぐ。対応表に判定ルール仮説（一致→その言語／日本語絡み不一致→日本語／日本語なし不一致→判定不能）の期待値を添える。', '不一致6マスの各レコードを一意特定でき、期待値が事前に固定される。', 'none', false, ''],
    ['PRD-SCN-420M', 2, '【回答者】日本語が絡む不一致4マスを送信する：ja選択×英語名刺／ja選択×简体字名刺／en選択×日本語名刺／zh-Hans選択×日本語名刺（回答本文は選択言語で書く）。', '4件とも送信が200で完了する。', 'medium', false, 'ANS-030,ANS-028'],
    ['PRD-SCN-420M', 3, '【回答者】日本語が絡まない不一致2マスを送信する：en選択×简体字名刺／zh-Hans選択×英語名刺。', '2件とも送信が200で完了する。', 'medium', false, 'ANS-030,ANS-028'],
    ['PRD-SCN-420M', 4, '【企業ユーザー】入力作業を始める前に回答データCSVをDL（言語フィルタ=すべての言語）し、「名刺の入力言語」を人間確認する。', '（仮説の検証）日本語絡み4マス=日本語／日本語なし2マス=判定不能。仮説と異なる判定が出た場合はそのまま記録し、判定ルールを再構築する。', 'low', false, 'DSH-001'],
    ['PRD-SCN-420M', 5, '【全アカウント】名刺入力画面の作業可能件数を確認し、不一致6マスの割り振り先を記録する。特に判定不能レコードがどのアカウントに出るか（全員／日本語チーム／誰にも出ない=滞留）を特定する。', '判定不能レコードのフォールバック先が一貫して記録される。「誰にも出ない=滞留」の場合は入力されないまま納期を迎え納品漏れに直結するため不具合として起票する。', 'none', false, 'STG-ADM-07'],
    ['PRD-SCN-420M', 6, '【企業ユーザー】言語フィルタを個別言語（日本語のみ等）にして回答データCSVをDLし、判定不能レコードが出力されるかを確認する。', '判定不能レコードの言語フィルタDLでの扱い（すべての言語でのみ出る／どこにも出ない等）が記録される。個別言語DLで取りこぼされる場合は納品データ欠落として起票する。', 'low', false, 'DSH-001'],
    ['PRD-SCN-420M', 7, '結果を420Lの一致3マスと統合した9マスマトリクスにまとめ、「仕様確認（正本Wiki 25/63への判定・フォールバックルール追記提案）」または「不具合（起票）」に分類する。', '9マス全体の判定・割り振り結果が1枚のマトリクスに整理され、起票または正本追記の判断材料が揃う。', 'none', false, ''],

    ['PRD-SCN-420C', 1, '【準備】简繁両方を対応言語に設定した検証用アンケートを新設する（要許可）。多言語設定はアンケート作成後に変更不可（2026-07-16確認）のため、既存アンケートへの追加はできず新設一択。作成時に多言語設定を忘れると作り直しになる点に注意。実装された言語コード（zh-Hant/zh-TW等）を記録する。', '繁体字で回答できるアンケートが用意され、回答画面の言語プルダウンに繁体字が表示される。', 'medium', true, ''],
    ['PRD-SCN-420C', 2, '【準備】オペレーター対応可能言語マスタに「简体字」「繁体字」が別項目として存在することを確認し、テストアカウントへ「简体字のみ」「繁体字のみ」を割り当てて設定内容と適用時刻を記録する。', '简体字のみ・繁体字のみのオペレーターが各1以上用意される。マスタに繁体字項目が無い場合はその時点で仕様確認として整理する。', 'medium', true, ''],
    ['PRD-SCN-420C', 3, '【準備】简繁で字形が異なる語（例: 广告/廣告、质量/質量、电话/電話）を含む简体字名刺・繁体字名刺のダミーを用意する。', '简繁を判別可能なダミー名刺2種が用意され、メール/URLで一意識別できる。', 'none', false, ''],
    ['PRD-SCN-420C', 4, '【回答者】一致2ケースを送信する：繁体字選択＋繁体字本文＋繁体字名刺／简体字選択＋简体字本文＋简体字名刺。', '2件とも送信が200で完了する。', 'medium', false, 'ANS-030,ANS-028'],
    ['PRD-SCN-420C', 5, '【全アカウント】名刺入力画面の作業可能件数を確認する。', '繁体字レコードは繁体字のみのオペレーターに、简体字レコードは简体字のみのオペレーターに分離して計上され、相互の取り違え（简体字名刺が繁体字チームへ等）がない。', 'none', false, 'STG-ADM-07'],
    ['PRD-SCN-420C', 6, '【回答者→全アカウント】クロス2ケース（繁体字回答×简体字名刺／简体字回答×繁体字名刺）を送信し、判定値と計上先を確認する。', 'クロスケースの判定（どちらかへの寄せ or 判定不能）とフォールバック先が一貫して記録される。', 'medium', false, 'ANS-030,ANS-028'],
    ['PRD-SCN-420C', 7, '【人間確認】CSV/DBの回答言語列・名刺言語判定列で简体字と繁体字が区別されて記録されているか確認し、結果を仕様確認/不具合に暫定分類する。', '简繁の判定・割り振りの観測結果が整理され、起票または正本（Wiki 25/61）追記の判断材料が揃う。', 'none', false, ''],

    ['PRD-SCN-420B', 1, '【準備】表=日本語表記・裏=英語表記の同一人物ダミー名刺（表裏2枚）を用意する。一部項目（例: URL）は裏面にのみ記載し、「裏面を参照しないと入力できない項目」を意図的に作る。', '表裏の名刺画像2枚が用意され、メール/URLで一意識別できる。', 'none', false, ''],
    ['PRD-SCN-420B', 2, '【回答者】420の回答画面で設問に回答し、「名刺を撮影」→表面をアップロード→裏面ステップで「裏面をスキップ」を押さずに裏面画像をアップロード→「アップロード完了」→送信する。', '表裏2枚が添付された状態で送信が200で完了し、/survey-thanksへ遷移する。', 'medium', false, 'ANS-028,ANS-030'],
    ['PRD-SCN-420B', 3, '【Lv3/Lv4】アンケート管理（admin/surveys）の420行から名刺画像ZIPをダウンロードし、ファイル一覧を確認する。', '当該レコードの表面（連番_1）と裏面（連番_2）の両方がZIPに含まれる。', 'low', false, 'STG-ADM-02-03'],
    ['PRD-SCN-420B', 4, '【入力担当】名刺入力の作業画面（data_input_screen）で当該レコードを開き、裏面画像の表示・切替UIの有無を確認する。裏面にのみ記載した項目（URL等）を裏面を参照して入力・確定する。', '作業画面で裏面が表示（または表裏切替）でき、裏面情報を根拠にした入力が確定まで通る。裏面が表示できない場合は「裏面のみ記載項目が入力不能」として気づきに記録する。', 'medium', false, 'STG-ADM-07,STG-FLOW-DATA-01'],
    ['PRD-SCN-420B', 5, '【Lv3】照合画面（matching_screen）で当該レコードを開き、裏面画像の表示可否と入力値を確認して照合を確定する。', '照合画面でも裏面が参照でき、全項目確定して保存できる。', 'medium', false, 'STG-FLOW-MATCH-01'],
    ['PRD-SCN-420B', 6, '【Lv3/Lv4】完成データCSV（全レコードDL/完成データ確認）を取得し、「名刺画像ファイル名（裏）」列を確認する。', '当該レコードの裏面ファイル名が記録されている（裏面スキップの既存レコードは空欄のまま）。', 'medium', false, 'STG-ADM-08-04'],
    ['PRD-SCN-420B', 7, '【観測】当該レコードの名刺言語判定と入力キューの割り振り先を確認する（表=日本語・裏=英語がどう判定されるか）。', '裏面の英語表記が言語判定・割り振りに与える影響が記録される（※要観測。420Lの判定モデルと突き合わせる）。', 'none', false, ''],

    ['PRD-SCN-420N', 1, '【準備】送信前の件数4点を記録する：admin/surveysの420行「実際の件数」／data_input_listの各グループ作業可能件数／matching_listの420カード総件数／名刺画像ZIPの枚数。', '送信前のベースラインが揃う。', 'none', false, 'STG-ADM-02-01,STG-ADM-07'],
    ['PRD-SCN-420N', 2, '【回答者】420の回答画面で設問に回答し（本文に一意識別子を含める）、名刺を添付せず「名刺が手元に無い方」から送信する。', '名刺なしで送信が200で完了し、/survey-thanksへ遷移する。', 'medium', false, 'ANS-030'],
    ['PRD-SCN-420N', 3, '【回答者】言語プルダウンでen（I don\'t have a business card）またはzh-Hans（我没有名片）を選択した状態でも、同導線で名刺なし送信ができることを確認する。', '翻訳されたボタンから同様に送信でき、回答言語が記録される（記録はCSV/DBで人間確認）。', 'medium', false, 'ANS-030'],
    ['PRD-SCN-420N', 4, '【Lv3/Lv4】送信後の件数4点を再取得し、送信前と比較する。', 'admin/surveysの実際の件数のみ増加し、data_input_listの作業可能件数・matching_listの総件数・名刺画像ZIPの枚数は増えない（名刺なし回答はデータ化工程の対象外）。', 'none', false, 'STG-ADM-02-01,STG-ADM-07'],
    ['PRD-SCN-420N', 5, '【Lv3/Lv4】完成データCSV（全レコードDL/完成データ確認）を取得し、名刺なしレコードが含まれないことを確認する。', '完成データCSVは名刺ありレコードのみで構成される。', 'medium', false, 'STG-ADM-08-04'],
    ['PRD-SCN-420N', 6, '【企業ユーザー】（420所有アカウント）回答データCSVをダウンロードし、名刺なし回答の行（一意識別子で特定）と回答言語の記録を確認する。', '回答データには名刺なし回答が回答内容・回答言語つきで記録されている（所有アカウント未入手の場合はこの工程のみ保留とする）。', 'low', false, 'DSH-001']
  ].map(([scenarioId, stepNo, action, expected, sideEffect, requiresPermission, linkedCaseIds]) => ({
    scenario_id: scenarioId,
    step_id: `${scenarioId}-${String(stepNo).padStart(2, '0')}`,
    step_no: stepNo,
    action,
    expected,
    side_effect: sideEffect,
    requires_permission: requiresPermission,
    linked_case_ids: linkedCaseIds ? linkedCaseIds.split(',') : []
  }));

  const sheetSchemas = [
    {
      tab: 'scenarios',
      purpose: 'シナリオマスタ',
      columns: ['scenario_id', 'title', 'role_scope', 'scenario_group', 'priority', 'side_effect', 'start_url', 'objective', 'linked_case_ids', 'stg_observation_status', 'expected_outcome', 'evidence_policy', 'notes', 'active']
    },
    {
      tab: 'scenario_steps',
      purpose: 'シナリオ手順マスタ',
      columns: ['scenario_id', 'step_id', 'step_no', 'action', 'expected', 'side_effect', 'requires_permission', 'linked_case_ids', 'active']
    },
    {
      tab: 'scenario_runs',
      purpose: 'シナリオ実行回',
      columns: ['run_id', 'environment', 'base_url', 'tester', 'browser', 'viewport', 'started_at', 'ended_at', 'note']
    },
    {
      tab: 'scenario_step_results',
      purpose: 'シナリオ手順別結果',
      columns: ['run_id', 'scenario_id', 'step_id', 'status', 'actual', 'evidence_url', 'checked_at', 'checked_by', 'defect_link', 'note']
    }
  ];

  window.E2E_SCENARIOS = scenarios;
  window.E2E_SCENARIO_STEPS = steps;
  window.E2E_SCENARIO_SHEET_SCHEMAS = sheetSchemas;
})();
